function fig = gui_fl_regdim1d()
% This is the machine-generated representation of a MATLAB object
% and its children.  Note that handle values may change when these
% objects are re-created. This may cause problems with some callbacks.
% The command syntax may be supported in the future, but is currently 
% incomplete and subject to change.
%
% To re-open this system, just type the name of the m-file at the MATLAB
% prompt. The M-file and its associtated MAT-file must be on your path.

% Modified by Christian Choque Cortez, March 2010
% Modified by Pierrick Legrand, November 2016

% FracLab 2.05 Beta, Copyright © 1996 - 2009 by INRIA
% -- --
% For details on use and redistribution refer to $fraclab/licence.txt
%--------------------------------------------------------------------------

a = figure('Name','Reg Dimension - 1D','Tag','Fig_gui_fl_regdim1d', ...
	'MenuBar','none','IntegerHandle','off','NumberTitle','off', ...
	'Position',[20 38 420 300]);

%%%%%%%%%%%%%%%%%%% CREATE FRAME %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
uicontrol('Parent',a,'Style','frame','Tag','Frame_title', ...
	'Units','normalized','Position',[0.03 0.9 0.94 0.09]);

uicontrol('Parent',a,'Style','frame','Tag','Frame_input', ...
	'Units','normalized','Position',[0.03 0.75 0.94 0.14]);

uicontrol('Parent',a,'Style','frame','Tag','Frame_parameters', ...
	'Units','normalized','Position',[0.03 0.24 0.94 0.5]);

%%%%%%%%%%%%%%%%%%% TITLE FRAME %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
uicontrol('Parent',a,'Style','text','Tag','StaticText_title', ...
	'Units','normalized','Position',[0.14 0.905 0.7 0.07], ...
	'FontUnits','normalized','FontWeight','bold','FontSize',0.6, ...
	'String','Regularization Dimension - 1D');

%%%%%%%%%%%%%%%%%%% INPUT SIGNAL %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
uicontrol('Parent',a,'Style','text','Tag','StaticText_input', ...
	'Units','normalized','Position',[0.08 0.77 0.2 0.07], ...
	'FontUnits','normalized','FontWeight','bold','FontSize',0.6, ...
	'String','Input Signal','HorizontalAlignment','left');

uicontrol('Parent',a,'Style','edit','Tag','EditText_input', ...
	'Units','normalized','Position',[0.3 0.785 0.4 0.07], ...
	'FontUnits','normalized','FontSize',0.6, ...
    'String','', ...
	'Enable','inactive');

uicontrol('Parent',a,'Tag','Button_refresh', ...
	'Units','normalized','Position',[0.77 0.765 0.17 0.11], ...
	'FontUnits','normalized','FontWeight','bold','FontSize',0.4, ...
    'String','Refresh', ...
    'Callback','fl_regdim1d_compute(''refresh'');');

%%%%%%%%%%%%%%%%%%%% GLOBAL PARAMETERS %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
uicontrol('Parent',a,'Style','text','Tag','StaticText_nmin', ...
	'Units','normalized','Position',[0.05 0.63 0.15 0.07], ...
	'FontUnits','normalized','FontSize',0.6, ...
	'String','Nmin','HorizontalAlignment','left');

uicontrol('Parent',a,'Style','edit','Tag','EditText_nmin', ...
	'Units','normalized','Position',[0.16 0.65 0.12 0.07], ...
	'FontUnits','normalized','FontSize',0.6, ...
    'String','5', ...
	'Callback','fl_regdim1d_compute(''edit_nmin'');');

uicontrol('Parent',a,'Style','popupmenu','Tag','PopupMenu_nmin', ...
	'Units','normalized','Position',[0.31 0.65 0.15 0.07], ...
	'FontUnits','normalized','FontSize',0.6, ...
	'Callback','fl_regdim1d_compute(''popmenu_nmin'');', ...
	'String',{'5', '64', '128', '256', '512'}, ...
	'Value',1);

uicontrol('Parent',a,'Style','text','Tag','StaticText_nmax', ...
	'Units','normalized','Position',[0.53 0.63 0.15 0.07], ...
	'FontUnits','normalized','FontSize',0.6, ...
	'String','Nmax','HorizontalAlignment','left');

uicontrol('Parent',a,'Style','edit','Tag','EditText_nmax', ...
	'Units','normalized','Position',[0.64 0.65 0.12 0.07], ...
	'FontUnits','normalized','FontSize',0.6, ...
	'Callback','fl_regdim1d_compute(''edit_nmax'');', ...
	'String','512');

uicontrol('Parent',a,'Style','popupmenu','Tag','PopupMenu_nmax', ...
	'Units','normalized','Position',[0.79 0.65 0.15 0.07], ...
	'FontUnits','normalized','FontSize',0.6, ...
	'Callback','fl_regdim1d_compute(''popmenu_nmax'');', ...
	'String',{'128', '256', '512', '1024', '2048'}, ...
	'Value',3);

uicontrol('Parent',a,'Style','text','Tag','StaticText_voices', ...
	'Units','normalized','Position',[0.05 0.53 0.15 0.07], ...
	'FontUnits','normalized','FontSize',0.6, ...
	'String','Voices','HorizontalAlignment','left');

uicontrol('Parent',a,'Style','edit','Tag','EditText_voices', ...
	'Units','normalized','Position',[0.16 0.55 0.12 0.07], ...
	'FontUnits','normalized','FontSize',0.6, ...
    'String','32', ...
	'Callback','fl_regdim1d_compute(''edit_voices'');');

uicontrol('Parent',a,'Style','popupmenu','Tag','PopupMenu_voices', ...
	'Units','normalized','Position',[0.31 0.55 0.15 0.07], ...
	'FontUnits','normalized','FontSize',0.6, ...
	'Callback','fl_regdim1d_compute(''popmenu_voices'');', ...
	'String',{'2', '4', '8', '16', '32', '64', '128', '256'}, ...
	'Value',5);

uicontrol('Parent',a,'Style','text','Tag','StaticTextf_kernel', ...
	'Units','normalized','Position',[0.53 0.53 0.12 0.07], ...
	'FontUnits','normalized','FontSize',0.6, ...
	'String','Kernel','HorizontalAlignment','left');

uicontrol('Parent',a,'Style','popupmenu','Tag','Kertype_menu', ...
	'Units','normalized','Position',[0.64 0.55 0.3 0.07], ...
	'FontUnits','normalized','FontSize',0.6, ...
	'String',{'Gaussian', 'Rectangle'}, ...
	'Value',1);
    
uicontrol('Parent',a,'Style','text','Tag','StaticText_regression', ...
	'Units','normalized','Position',[0.05 0.43 0.17 0.07], ...
	'FontUnits','normalized','FontSize',0.6, ...
	'String','Regression');

uicontrol('Parent',a,'Style','popupmenu','Tag','Regtype_menu', ...
	'Units','normalized','Position',[0.23 0.45 0.43 0.07], ...
	'FontUnits','normalized','FontSize',0.6, ...
	'String',{'Least Square','Weighted Least Square','Penalized Least Square', ...
              'Lepskii Adaptive Procedure','Maximum Likelihood','Lim inf','Lim sup'}, ...
	'Value',1);
    
uicontrol('Parent',a,'Style','text','Tag','StaticText_noise', ...
	'Units','normalized','Position',[0.05 0.33 0.26 0.07], ...
	'FontUnits','normalized','FontSize',0.6, ...
	'String','Std deviation noise','HorizontalAlignment','left');

uicontrol('Parent',a,'Style','edit','Tag','EditText_noise', ...
	'Units','normalized','Position',[0.34 0.35 0.12 0.07], ...
	'FontUnits','normalized','FontSize',0.6, ...
	'Callback','fl_regdim1d_compute(''edit_sigma'');', ...
	'String','0');

uicontrol('Parent',a,'Style','Checkbox','Tag','Check_regularized', ...
	'Units','normalized','Position',[0.05 0.26 0.45 0.07], ...
	'FontUnits','normalized','FontSize',0.6, ...
	'String','No regularized graphs', ...
    'Value',0, ...
    'Callback','fl_regdim1d_compute(''check_reg'');');

%%%%%%%%%%%%%%%%%%%% COMPUTE/HELP/CLOSE %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
uicontrol('Parent',a,'Tag','Button_compute', ...
	'Units','normalized','Position',[0.032 0.11 0.2 0.11], ...
	'FontUnits','normalized','FontWeight','bold','FontSize',0.4, ...
    'String','Compute', ...
	'Callback','eval([''global '' fl_regdim1d_compute(''compute'',who)])');

uicontrol('Parent',a,'Tag','Button_help', ...
	'Units','normalized','Position',[0.41 0.11 0.2 0.11], ...
	'FontUnits','normalized','FontWeight','bold','FontSize',0.4, ...
    'String','Help', ...
	'Callback','fl_regdim1d_compute(''help'');');

uicontrol('Parent',a,'Tag','Button_close', ...
	'Units','normalized','Position',[0.77 0.11 0.2 0.11], ...
	'FontUnits','normalized','FontWeight','bold','FontSize',0.4, ...
	'String','Close', ...
	'Callback','fl_regdim1d_compute(''close'');');

%%%%%%%%%%%%% REGULARIZATION DIMENSION DISPLAY %%%%%%%%%%%%%%%%%%%%%%%%%%%%
uicontrol('Parent',a,'Style','text','Tag','StaticText_regdim', ...
	'Units','normalized','Position',[0.3 0.005 0.4 0.07], ...
	'FontUnits','normalized','FontWeight','bold','FontSize',0.6, ...
	'String','Regularization Dimension','HorizontalAlignment','left');

uicontrol('Parent',a,'Style','edit','Tag','EditText_regdim', ...
	'Units','normalized','Position',[0.7 0.025 0.27 0.07], ...
	'FontUnits','normalized','FontSize',0.6);

fl_window_init(a);
set(findobj(a,'Tag','StaticText_regdim'),'BackgroundColor',fl_getOption('BackGroundColor'));
set(findobj(a,'Tag','StaticText_regdim'),'ForegroundColor',fl_getOption('AltFontColor'));

if nargout > 0, fig = a; end

fl_regdim1d_compute('refresh');
