function gui_fl_managethemes()
% This is the machine-generated representation of a MATLAB object
% and its children.  Note that handle values may change when these
% objects are re-created. This may cause problems with some callbacks.
% The command syntax may be supported in the future, but is currently 
% incomplete and subject to change.
%
% To re-open this system, just type the name of the m-file at the MATLAB
% prompt. The M-file and its associtated MAT-file must be on your path.

% FracLab 2.05 Beta, Copyright © 1996 - 2009 by INRIA
% -- --
% For details on use and redistribution refer to $fraclab/licence.txt
%--------------------------------------------------------------------------

options_fig=findobj('Tag','Fig_gui_fl_options');
if isempty(options_fig)
	fl_error('FracLab Options window not found');
	return;
end
p=version;
if str2num(p(1))<7
	fl_error('FracLab Options Manager is disabled in Matlab prior to version 7');
	return;
end
ud = get(options_fig,'UserData');

flroot = fl_getOption('FracLabRoot');
fltool_list = ls(fullfile(flroot,'Gui','fltool_*.mat'));
fltool_list_size = size(fltool_list);
for i = 1:fltool_list_size(1)
	fltool_perso = fltool_list(i,:);
	espaces = find(fltool_perso == ' ');
	if ~isempty(espaces)
		fltool_perso = fltool_perso(1:espaces(1)-1);
	end
	fltool_perso = fltool_perso(8:end-4);
	Themes_List{i} =  fltool_perso;
end

a = figure('Units','pixels', ...
	'MenuBar','none','IntegerHandle','off','NumberTitle','off', ...
	'Position',[100 200 350 200], ...
	'HandleVisibility','callback', ...
	'Color',ud.bgcolor,...
	'Tag','Fig_gui_fl_managethemes');
    
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.342857142857143, ...
	'ListboxTop',0, ...
	'Position',[0.02 0.83 0.96 0.15], ...
	'Style','frame', ...
	'BackgroundColor',ud.framecolor,...
	'Tag','Frame1');    
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.872727272727273, ...
	'FontWeight','bold', ...
	'HorizontalAlignment','center', ...
	'Position',[0.1 0.87 0.8 0.07], ...
	'String','Manage themes', ...
	'Style','text', ...
	'BackgroundColor',ud.framecolor,...
	'ForegroundColor',ud.fontcolor,...
	'Tag','StaticText0');
    
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.0695652173913043, ...
	'ListboxTop',0, ...
	'Position',[0.02 0.03 0.96 0.77], ...
	'Style','frame', ...
	'BackgroundColor',ud.framecolor,...
	'Tag','Frame2');    


b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.7, ...
	'HorizontalAlignment','left', ...
	'Position',[0.05 0.65 0.42 0.09], ...
	'String','Save current theme as', ...
	'Style','text', ...
	'BackgroundColor',ud.framecolor,...
	'ForegroundColor',ud.fontcolor,...
	'Tag','StaticText1');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',0.6, ...
	'Position',[0.46 0.66 0.39 0.09], ...
	'Style','edit', ...
	'BackgroundColor',ud.fill_incolor,...
	'ForegroundColor',ud.fontcolor,...
	'Tag','Text_saveas');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_managethemes_compute(''add_theme'');', ...
	'FontSize',0.6, ...
	'Position',[0.87 0.66 0.09 0.09], ...
	'String','OK', ...
	'BackgroundColor',ud.buttoncolor,...
	'ForegroundColor',ud.fontcolor,...
	'Tag','Pushbutton1');


b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.2, ...
	'HorizontalAlignment','left', ...
	'Position',[0.05 0.25 0.22 0.29], ...
	'String','Available themes', ...
	'Style','text', ...
	'BackgroundColor',ud.framecolor,...
	'ForegroundColor',ud.fontcolor,...
	'Tag','StaticText3');

b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',0.18, ...
	'Position',[0.24 0.26 0.71 0.34], ...
	'String',Themes_List,...
	'Callback','fl_managethemes_compute(''select_theme'');', ...
	'Style','list', ...
	'BackgroundColor',ud.fill_incolor,...
	'ForegroundColor',ud.fontcolor,...
	'Tag','list_themes');
 
    

b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.7, ...
	'HorizontalAlignment','left', ...
	'Position',[0.05 0.08 0.18 0.09], ...
	'String','Rename', ...
	'Style','text', ...
	'BackgroundColor',ud.framecolor,...
	'ForegroundColor',ud.fontcolor,...
	'Tag','StaticText2');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',0.6, ...
	'Position',[0.24 0.09 0.39 0.09], ...
	'Style','edit', ...
	'BackgroundColor',ud.fill_incolor,...
	'ForegroundColor',ud.fontcolor,...
	'Tag','Text_rename');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_managethemes_compute(''rename_theme'');', ...
	'FontSize',0.6, ...
	'Position',[0.66 0.09 0.09 0.09], ...
	'String','OK', ...
	'BackgroundColor',ud.buttoncolor,...
	'ForegroundColor',ud.fontcolor,...
	'Tag','Pushbutton2');
	
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_managethemes_compute(''delete_theme'');', ...
	'FontSize',0.6, ...
	'Position',[0.8 0.09 0.16 0.09], ...
	'String','Delete', ...
	'BackgroundColor',ud.buttoncolor,...
	'ForegroundColor',ud.fontcolor,...
	'Tag','Pushbutton3');

fl_window_init(a,'NoTheme');