function fig = gui_fl_estimOSC2DH()
% This is the machine-generated representation of a MATLAB object
% and its children.  Note that handle values may change when these
% objects are re-created. This may cause problems with some callbacks.
% The command syntax may be supported in the future, but is currently
% incomplete and subject to change.
%
% To re-open this system, just type the name of the m-file at the MATLAB
% prompt. The M-file and its associtated MAT-file must be on your path.

% Author Christian Choque Cortez, November 2008

% FracLab 2.05 Beta, Copyright © 1996 - 2009 by INRIA
% -- --
% For details on use and redistribution refer to $fraclab/licence.txt
%--------------------------------------------------------------------------

a = figure('Name','Oscillation based estimation 2D','Tag','Fig_gui_fl_estimOSC2DH',...
    'MenuBar','none','IntegerHandle','off','NumberTitle','off', ...
    'Position',[20 38 369 272]);

%%%%%%%%%%%%%%%%%%% CREATE FRAME %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
uicontrol('Parent',a,'Style','frame','Tag','Frame_title', ...
    'Units','normalized','Position',[0.049 0.879 0.919 0.1]);

uicontrol('Parent',a,'Style','frame','Tag','Frame_input', ...
    'Units','normalized','Position',[0.049 0.71 0.919 0.154]);

uicontrol('Parent',a,'Style','frame','Tag','Frame_size_input', ...
    'Units','normalized','Position',[0.049 0.165 0.919 0.53]);

%%%%%%%%%%%%%%%%%%% TITLE FRAME %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
uicontrol('Parent',a,'Style','text','Tag','StaticText_title', ...
    'Units','normalized','Position',[0.06 0.89 0.9 0.07], ...
    'FontUnits','normalized','FontWeight','bold','FontSize',0.6, ...
    'String','Estimation of Holder exponent - Oscillation method 2D');

%%%%%%%%%%%%%%%%%%% INPUT SIGNAL %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
uicontrol('Parent',a,'Style','text','Tag','StaticText_input', ...
    'Units','normalized','Position',[0.08 0.73 0.22 0.07], ...
    'FontUnits','normalized','FontWeight','bold','FontSize',0.6, ...
    'String','Input Signal');

uicontrol('Parent',a,'Style','edit','Tag','EditText_input', ...
    'Units','normalized','Position',[0.33 0.74 0.33 0.08], ...
    'FontUnits','normalized','FontSize',0.6, ...
    'String','', ...
    'Enable','inactive');

uicontrol('Parent',a,'Tag','Button_refresh', ...
    'Units','normalized', ...
    'FontUnits','normalized','FontWeight','bold','FontSize',0.4, ...
    'Position',[0.71 0.72 0.23 0.12], ...
    'String','Refresh', ...
    'Callback','fl_estimOSC2DH_compute(''refresh'')');

%%%%%%%%%%%%% SAMPLING AND ZONES PARAMETERS %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
uicontrol('Parent',a,'Style','text','Tag','StaticText_base', ...
    'Units','normalized','Position',[0.08 0.59 0.1 0.07], ...
    'FontUnits','normalized','FontSize',0.6, ...
    'String','Base');

uicontrol('Parent',a,'Style','edit','Tag','EditText_base', ...
    'Units','normalized','Position',[0.2 0.61 0.12 0.07], ...
    'FontUnits','normalized','FontSize',0.6, ...
    'String','2.1', ...
    'Callback','fl_estimOSC2DH_compute(''edit_base'')');

uicontrol('Parent',a,'Style','Text','Tag','StaticText_alpha', ...
    'Units','normalized','Position',[0.41 0.59 0.1 0.07], ...
    'FontUnits','normalized','FontSize',0.6, ...
    'String','Alpha');

uicontrol('Parent',a,'Style','edit','Tag','EditText_alpha', ...
    'Units','normalized','Position',[0.53 0.61 0.12 0.07], ...
    'FontUnits','normalized','FontSize',0.6, ...
    'String','0.1', ...
    'Callback','fl_estimOSC2DH_compute(''edit_alpha'')');

uicontrol('Parent',a,'Style','text','Tag','StaticText_beta', ...
    'Units','normalized','Position',[0.7 0.59 0.1 0.07], ...
    'FontUnits','normalized','FontSize',0.6, ...
    'String','Beta');

uicontrol('Parent',a,'Style','edit','Tag','EditText_beta', ...
    'Units','normalized','Position',[0.82 0.61 0.12 0.07], ...
    'FontUnits','normalized','FontSize',0.6, ...
    'String','0.3', ...
    'Callback','fl_estimOSC2DH_compute(''edit_beta'')');

uicontrol('Parent',a,'Style','Checkbox','Tag','Check_subsampling', ...
    'Units','normalized','Position',[0.091 0.51 0.35 0.07], ...
    'FontUnits','normalized','FontSize',0.6, ...
    'String','No Sub-sampling', ...
    'Value',0, ...
    'Callback','fl_estimOSC2DH_compute(''check_subsampling'')');

uicontrol('Parent',a,'Style','edit','Tag','EditText_sampling', ...
    'Units','normalized','Position',[0.53 0.52 0.12 0.07], ...
    'FontUnits','normalized','FontSize',0.6, ...
    'String','2', ...
    'Enable','off', ...    
    'Callback','fl_estimOSC2DH_compute(''edit_sampling'')');

uicontrol('Parent',a,'Style','text','Tag','StaticText_zones', ...
    'Units','normalized','Position',[0.69 0.505 0.1 0.07], ...
    'FontUnits','normalized','FontSize',0.6, ...
    'String','Zones');

uicontrol('Parent',a,'Style','edit','Tag','EditText_zones', ...
    'Units','normalized','Position',[0.82 0.52 0.12 0.07], ...
    'FontUnits','normalized','FontSize',0.6, ...
    'String','7', ...
    'Callback','fl_estimOSC2DH_compute(''edit_zones'')');

%%%%%%%%%%%%%%%%%%% AVERAGING PARAMETERS %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
uicontrol('Parent',a,'Style','Checkbox','Tag','Check_average', ...
    'Units','normalized','Position',[0.091 0.41 0.25 0.07], ...
    'FontUnits','normalized','FontSize',0.6, ...
    'String','No Averaging', ...
    'Value',0, ...
    'Callback','fl_estimOSC2DH_compute(''check_average'')');

uicontrol('Parent',a,'Style','Text','Tag','StaticText_gamma', ...
    'Units','normalized','Position',[0.376 0.405 0.13 0.07], ...
    'FontUnits','normalized','FontSize',0.6, ...
    'String','Gamma', ...
    'Enable','off');

uicontrol('Parent',a,'Style','edit','Tag','EditText_gamma', ...
    'Units','normalized', ...
    'FontUnits','normalized','FontSize',0.6, ...
    'Position',[0.53 0.42 0.12 0.07], ...
    'String','0.5', ...
    'Enable','off', ...
    'Callback','fl_estimOSC2DH_compute(''edit_gamma'')');

uicontrol('Parent',a,'Style','text','Tag','StaticText_delta', ...
    'Units','normalized','Position',[0.698 0.405 0.1 0.07], ...
    'FontUnits','normalized','FontSize',0.6, ...
    'String','Delta', ...
    'Enable','off');

uicontrol('Parent',a,'Style','edit','Tag','EditText_delta', ...
    'Units','normalized','Position',[0.82 0.42 0.12 0.07], ...
    'FontUnits','normalized','FontSize',0.6, ...
    'String','1', ...
    'Enable','off', ...
    'Callback','fl_estimOSC2DH_compute(''edit_delta'')');

%%%%%%%%%%%%%%%% TIME INSTANT PARAMETERS %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
uicontrol('Parent',a,'Style','Checkbox','Tag','Check_timeinstant', ...
    'Units','normalized','Position',[0.091 0.3 0.40 0.07], ...
    'FontUnits','normalized','FontSize',0.6, ...
    'String','Holder Function', ...
    'Value',1, ...
    'Callback','fl_estimOSC2DH_compute(''check_time'')');

uicontrol('Parent',a,'Style','text','Tag','StaticText_timeinstant', ...
    'Units','normalized','Position',[0.59 0.305 0.20 0.07], ...
    'FontUnits','normalized','FontSize',0.6, ...
    'String','Time Instant', ...
    'Enable','off');

[SigIn_name] = fl_get_input('matrix');
eval(['global ' SigIn_name]);
SigIn = eval(SigIn_name);
N = min(size(SigIn));

uicontrol('Parent',a,'Style','edit','Tag','EditText_timeinstant', ...
    'Units','normalized','Position',[0.82 0.32 0.12 0.07], ...
    'FontUnits','normalized','FontSize',0.6, ...
    'String',[num2str(floor(1+N*rand(1))),',',num2str(floor(1+N*rand(1)))], ...
    'Enable','off', ...
    'Callback','fl_estimOSC2DH_compute(''edit_time'')');

%%%%%%%%%%%%%%%%%%% REGRESSION PARAMETERS %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
uicontrol('Parent',a,'Style','text','Tag','StaticText_regression', ...
    'Units','normalized','Position',[0.155 0.18 0.19 0.07], ...
    'FontUnits','normalized','FontSize',0.6, ...
    'String','Regression');

uicontrol('Parent',a,'Style','popupmenu','Tag','Regtype_menu', ...
    'Units','normalized','Position',[0.41 0.19 0.53 0.08], ...
    'FontUnits','normalized','FontSize',0.6, ...
    'String',{'Least Square','Weighted Least Square','Penalized Least Square',...
              'Lepskii Adaptive Procedure','Maximum Likelihood','lim inf','lim sup'}, ...
    'Value',1, ...
    'Callback','fl_estimOSC2DH_compute(''regtype'')');

%%%%%%%%%%%%%%%%%%%% COMPUTE/HELP/CLOSE %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
uicontrol('Parent',a,'Tag','Button_compute', ...
    'Units','normalized','Position',[0.049 0.02 0.23 0.12], ...
    'FontUnits','normalized','FontWeight','bold','FontSize',0.4, ...
    'String','Compute', ...
    'Callback','eval([''global '' fl_estimOSC2DH_compute(''compute'',who)])');

uicontrol('Parent',a,'Tag','Button_help', ...
    'Units','normalized','Position',[0.39 0.02 0.23 0.12], ...
    'FontUnits','normalized','FontWeight','bold','FontSize',0.4, ...
    'String','Help', ...
    'Callback','fl_estimOSC2DH_compute(''help'')');

uicontrol('Parent',a,'Tag','Button_close', ...
    'Units','normalized','Position',[0.735 0.02 0.23 0.12], ...
    'FontUnits','normalized','FontWeight','bold','FontSize',0.4, ...
    'String','Close', ...
    'Callback','fl_estimOSC2DH_compute(''close'')');

fl_window_init(a);

if nargout > 0, fig = a; end

fl_estimOSC2DH_compute('refresh');
