function gui_fl_tml()
% This is the machine-generated representation of a MATLAB object
% and its children.  Note that handle values may change when these
% objects are re-created. This may cause problems with some callbacks.
% The command syntax may be supported in the future, but is currently 
% incomplete and subject to change.
%
% To re-open this system, just type the name of the m-file at the MATLAB
% prompt. The M-file and its associtated MAT-file must be on your path.
                   
% FracLab 2.05 Beta, Copyright © 1996 - 2009 by INRIA
% -- --
% For details on use and redistribution refer to $fraclab/licence.txt
%--------------------------------------------------------------------------

a = figure( ...
	'Colormap',[], ...
	'HandleVisibility','callback', ...
	'MenuBar','none','IntegerHandle','off','NumberTitle','off', ...
	'Name','2-microlocal Like Frontier Estimation', ...
	'Position',[20 50 400 450], ...
	'Tag','Fig_gui_fl_tml', ...
	'UserData',0.00137174);
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.344086021505376, ...
	'Position',[0.05 0.9 0.9 0.0775], ...
	'Style','frame', ...
	'Tag','Frame_gui_fl_tml');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.533333333333333, ...
	'FontWeight','bold', ...
	'Position',[0.15 0.905 0.7 0.05], ...
	'String','2-microlocal Like Frontier estimation', ...
	'Style','text', ...
	'Tag','StaticText_gui_fl_tml');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.0666666666666667, ...
	'Position',[0.05 0.46 0.9 0.40], ...
	'Style','frame', ...
	'Tag','Frame_input_tml');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.666666666666667, ...
	'FontWeight','bold', ...
	'HorizontalAlignment','left', ...
	'Position',[0.075 0.8125 0.2 0.04], ...
	'String','Input data', ...
	'Style','text', ...
	'Tag','StaticTexttml_input');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_tml(''refresh1'');', ...
	'FontSize',0.666666666666667, ...
	'FontWeight','bold', ...
	'Position',[0.075 0.7675 0.15 0.04], ...
	'String','Refresh', ...
	'Tag','Pushbuttontml_refresh');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.666666666666667, ...
	'HorizontalAlignment','center', ...
	'Position',[0.275 0.7675 0.1 0.04], ...
	'String','name', ...
	'Style','text', ...
	'Tag','StaticTexttml_name');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',0.666666666666667, ...
	'HorizontalAlignment','left', ...
	'Position',[0.4 0.7675 0.2 0.04], ...
	'String','Input data name', ...
	'Style','edit', ...
	'Enable','inactive',...
	'Tag','StaticTexttml_sig_nname');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.666666666666667, ...
	'HorizontalAlignment','center', ...
	'Position',[0.6 0.7675 0.1 0.04], ...
	'String','size', ...
	'Style','text', ...
	'Tag','StaticTexttml_size');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',0.666666666666667, ...
	'HorizontalAlignment','center', ...
	'Position',[0.725 0.7675 0.2 0.04], ...
	'String','[M1 x M2]', ...
	'Style','edit', ...
	'Enable','inactive',...
	'Tag','EditTexttml_size');
%b = uicontrol('Parent',a, ...
%	'Units','normalized', ...
%	'FontUnits','normalized', ...
%	'FontSize',0.101587301587302, ...
%	'Position',[0.05 0.45 0.9 0.2625], ...
%	'Style','frame', ...
%	'Tag','Frame_param');
%b = uicontrol('Parent',a, ...
%	'Units','normalized', ...
%	'FontUnits','normalized', ...
%	'FontSize',0.592592592592593, ...
%	'FontWeight','bold', ...
%	'HorizontalAlignment','center', ...
%	'Position',[0.1 0.6625 0.8 0.045], ...
%	'String','Parameters', ...
%	'Style','text', ...
%	'Tag','StaticText_param');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.666666666666667, ...
	'HorizontalAlignment','left', ...
	'Position',[0.075 0.67 0.25 0.04], ...
	'String','window', ...
	'Style','text', ...
	'Tag','StaticText_no_pts_used');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
   'BackgroundColor',[1 1 1], ...
	'Callback','fl_tml(''edittext_no_pts_used'');', ...
	'FontSize',0.666666666666667, ...
	'Min',3, ...
	'Position',[0.35 0.67 0.2 0.04], ...
	'String','3', ...
	'Style','edit', ...
   'Tag','EditText_no_pts_used');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.666666666666667, ...
	'HorizontalAlignment','left', ...
	'Position',[0.6 0.67 0.175 0.04], ...
	'String','step', ...
	'Style','text', ...
	'Tag','StaticText_incr');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','fl_tml(''edittext_incr'');', ...
	'FontSize',0.666666666666667, ...
	'Min',0, ...
	'Position',[0.725 0.67 0.2 0.04], ...
	'String','0', ...
	'Style','edit', ...
	'Tag','EditText_incr');
%b = uicontrol('Parent',a, ...
%	'Units','normalized', ...
%	'FontUnits','normalized', ...
%	'FontSize',0.666666666666667, ...
%	'HorizontalAlignment','left', ...
%	'Position',[0.055 0.60 0.25 0.04], ...
%	'String','# of pts to be studied', ...
%	'Style','text', ...
%	'Tag','StaticText_no_pts_std');
%b = uicontrol('Parent',a, ...
%	'Units','normalized', ...
%	'FontUnits','normalized', ...
%	'BackgroundColor',[1 1 1], ...
%	'Callback','fl_tml(''edittext_no_pts_std'');', ...
%	'FontSize',0.666666666666667, ...
%	'Min',1, ...
%	'Position',[0.35 0.60 0.2 0.04], ...
%	'String','1', ...
%	'Style','edit', ...
%	'Tag','EditText_no_pts_std', ...
%	'Value',1);
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.666666666666667, ...
	'HorizontalAlignment','left', ...
	'Position',[0.6 0.60 0.2 0.04], ...
	'String','estimate', ...
	'Style','text', ...
	'Tag','StaticText_find');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_tml(''popupmenu_find'');', ...
	'FontSize',0.666666666666667, ...
	'Max',3, ...
	'Min',1, ...
	'Position',[0.725 0.60 0.2 0.04], ...
	'String',{'frontier','local','pointwise'}, ...
	'Style','popupmenu', ...
	'Tag','PopupMenu_find', ...
	'Value',1);
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','eval([''global '' fl_tml(''compute'',who)]);', ...
	'FontSize',0.355555555555556, ...
	'FontWeight','bold', ...
	'Position',[0.3 0.49 0.4 0.075], ...
	'String','Compute', ...
	'Tag','Pushbutton_compute');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.0888888888888889, ...
	'Position',[0.05 0.15 0.9 0.30], ...
	'Style','frame', ...
	'Tag','Frame_convex');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Enable','on', ...
	'FontSize',0.666666666666667, ...
	'FontWeight','bold', ...
	'HorizontalAlignment','center', ...
	'Position',[0.1 0.4 0.8 0.04], ...
	'String','Make the frontier convex', ...
	'Style','text', ...
	'Tag','StaticTextConv_frontier');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Enable','on', ...
	'FontSize',0.666666666666667, ...
	'FontWeight','bold', ...
	'HorizontalAlignment','left', ...
	'Position',[0.075 0.35 0.2 0.04], ...
	'String','Input data', ...
	'Style','text', ...
	'Tag','StaticTextConv_input');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_tml(''refresh2'');', ...
	'Enable','on', ...
	'FontSize',0.666666666666667, ...
	'FontWeight','bold', ...
	'Position',[0.075 0.31 0.15 0.04], ...
	'String','Refresh', ...
	'Tag','PushbuttonConv_refresh');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Enable','on', ...
	'FontSize',0.666666666666667, ...
	'HorizontalAlignment','center', ...
	'Position',[0.25 0.31 0.1 0.04], ...
	'String','name', ...
	'Style','text', ...
	'Tag','StaticTextConv_name');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Enable','on', ...
	'FontSize',0.666666666666667, ...
	'HorizontalAlignment','left', ...
	'Position',[0.35 0.31 0.2 0.04], ...
	'String','Input data name', ...
	'Style','edit', ...
	'Enable','inactive',...
	'Tag','StaticTextConv_sig_nname');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Enable','on', ...
	'FontSize',0.666666666666667, ...
	'HorizontalAlignment','left', ...
	'Position',[0.6 0.31 0.2 0.04], ...
	'String','s` cut off', ...
	'Style','text', ...
	'Tag','StaticText_sprime');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','fl_tml(''edittext_sprime'');', ...
	'Enable','on', ...
	'FontSize',0.666666666666667, ...
	'Max',1.0, ...
	'Min',-0.8, ...
	'Position',[0.725 0.31 0.175 0.04], ...
	'String','0.0', ...
	'Style','edit', ...
	'Tag','EditText_sprime', ...
	'Value',0.0);
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','eval([''global '' fl_tml(''do_it'',who)]);', ...
	'Enable','on', ...
	'FontSize',0.355555555555556, ...
	'FontWeight','bold', ...
	'Position',[0.4 0.175 0.2 0.075], ...
	'String','Convexify', ...
	'Tag','Pushbutton_do_it');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','helpwin(''fl_tml'');', ...
	'FontSize',0.355555555555556, ...
	'FontWeight','bold', ...
	'Position',[0.05 0.05 0.2 0.075], ...
	'String','Help', ...
	'Tag','Pushbutton_help');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[0.701961 0.701961 0.701961], ...
	'Callback','close(findobj(''Tag'',''Fig_gui_fl_tml''));', ...
	'FontSize',0.355555555555556, ...
	'FontWeight','bold', ...
	'Position',[0.75 0.05 0.2 0.075], ...
	'String','Close', ...
	'Tag','Pushbutton_close');

fl_window_init(a);

fl_tml('refresh1');
