function gui_fl_adv_dwtspec()
% This is the machine-generated representation of a MATLAB object
% and its children.  Note that handle values may change when these
% objects are re-created. This may cause problems with some callbacks.
% The command syntax may be supported in the future, but is currently 
% incomplete and subject to change.
%
% To re-open this system, just type the name of the m-file at the MATLAB
% prompt. The M-file and its associtated MAT-file must be on your path.
              
% FracLab 2.05 Beta, Copyright © 1996 - 2009 by INRIA
% -- --
% For details on use and redistribution refer to $fraclab/licence.txt
%--------------------------------------------------------------------------

a = figure( ...
	'Colormap',[], ...
	'HandleVisibility','callback', ...
	'MenuBar','none','IntegerHandle','off','NumberTitle','off', ...
	'Name','dwt-based advanced Spectrum', ...
	'Position',[20 50 400 400], ...
	'Tag','Fig_gui_fl_adv_dwtspec');
    
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.25, ...
	'Position',[0.025 0.685 0.95 0.12], ...
	'Style','frame', ...
	'Tag','Frame_input');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.6, ...
	'FontWeight','bold', ...
	'HorizontalAlignment','left', ...
	'Position',[0.06 0.710 0.25 0.05], ...
	'String','Input Signal', ...
	'Style','text', ...
	'Tag','StaticText_input');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',0.5, ...
	'HorizontalAlignment','left', ...
	'Position',[0.32 0.715 0.4 0.06], ...
	'Style','edit', ...
	'Enable','inactive',...
	'Tag','EditText_sig_nname');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_dwtspec_compute(''advanced_compute'');', ...
	'FontSize',0.4, ...
	'FontWeight','bold', ...
	'Position',[0.75 0.710 0.175 0.075], ...
	'String','Refresh', ...
	'Tag','refresh_input');

b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.258063999999999, ...
	'Position',[0.025 0.8425 0.95 0.13], ...
	'Style','frame', ...
	'Tag','Frame_gui_fl_dwt');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.136752, ...
	'Position',[0.025 0.4575 0.95 0.2], ...
	'Style','frame', ...
	'Tag','Frame_gui_fl_dwtparam');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.499999999999999, ...
	'FontWeight','bold', ...
	'Position',[0.159292 0.867805 0.646018 0.055437], ...
	'String','DWT Based Legendre Spectrum', ...
	'Style','text', ...
	'Tag','StaticText_dwt _title');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.533333333333332, ...
	'Interruptible','off', ...
	'Max',14, ...
	'Min',1, ...
	'Position',[0.36 0.575 0.275 0.05], ...
	'String',{'Daubechies 2', 'Daubechies 4', 'Daubechies 6', 'Daubechies 8', 'Daubechies 10', 'Daubechies 12', 'Daubechies 14', 'Daubechies 16', 'Daubechies 18', 'Daubechies 20', 'Coiflet 6', 'Coiflet 12', 'Coiflet 18', 'Coiflet 24'}, ...
	'Style','popupmenu', ...
	'Tag','PopupMenu_dwt_type', ...
	'Value',1);
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.615383999999998, ...
	'Position',[0.175 0.575 0.1625 0.04], ...
	'String','Wavelet:', ...
	'Style','text', ...
	'Tag','StaticText_dwtype');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.615383999999998, ...
	'Position',[0.175 0.4975 0.1625 0.04], ...
	'String','Octaves:', ...
	'Style','text', ...
	'Tag','StaticText_octave');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','fl_adv_dwtspec_compute(''dwt_edit_octave'');', ...
	'FontSize',0.533333333333332, ...
	'Position',[0.36 0.4975 0.13 0.0475], ...
	'String','8', ...
	'Style','edit', ...
	'Tag','EditText_dwt_octave');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_adv_dwtspec_compute(''dwt_ppm_octave'');', ...
	'FontSize',0.533333333333332, ...
	'Max',8, ...
	'Min',1, ...
	'Position',[0.5025 0.4975 0.13 0.0475], ...
	'String',{'1', '2', '3', '4', '5', '6', '7', '8'}, ...
	'Style','popupmenu', ...
	'Tag','PopupMenu_dwt_octave', ...
	'Value',8);
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','eval([''global '' fl_adv_dwtspec_compute(''dwtspec_compute'',who)]);', ...
	'FontSize',0.399999999999999, ...
	'FontWeight','bold', ...
	'Position',[0.1275 0.045 0.175 0.075], ...
	'String','Compute', ...
	'Tag','Pushbutton_dwtspec_compute');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_adv_dwtspec_compute(''close'');', ...
	'FontSize',0.399999999999999, ...
	'FontWeight','bold', ...
	'Position',[0.6825 0.045 0.175 0.075], ...
	'String','Close', ...
	'Tag','Pushbutton_dwtspec_cancel');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.136752, ...
	'Position',[0.025 0.155 0.95 0.2675], ...
	'Style','frame', ...
	'Tag','Frame_gui_fl_dwtparam');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',0.571427999999998, ...
	'Position',[0.2775 0.3325 0.1075 0.0475], ...
	'String','-4', ...
	'Style','edit', ...
	'Tag','EditText_adv_dwtspec_qmin');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.592591999999998, ...
	'Position',[0.12 0.3325 0.1425 0.045], ...
	'String','Q min', ...
	'Style','text', ...
	'Tag','StaticText1');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.592591999999998, ...
	'Position',[0.12 0.27 0.1425 0.0425], ...
	'String','Q max', ...
	'Style','text', ...
	'Tag','StaticText2');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.592591999999998, ...
	'Position',[0.12 0.2075 0.1425 0.0425], ...
	'String','# of Q''s', ...
	'Style','text', ...
	'Tag','StaticText3');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',0.571427999999998, ...
	'Position',[0.2775 0.27 0.1075 0.045], ...
	'String','4', ...
	'Style','edit', ...
	'Tag','EditText_adv_dwtspec_qmax');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',0.571427999999998, ...
	'Position',[0.2775 0.2075 0.1075 0.045], ...
	'String','11', ...
	'Style','edit', ...
	'Tag','EditText_adv_dwtspec_nbq');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_adv_dwtspec_compute(''radiobutton_reg'')', ...
	'FontSize',0.533333333333332, ...
	'Position',[0.45 0.30 0.44 0.05], ...
	'String','Specify Regression Range', ...
	'Style','Checkbox', ...
	'Tag','Radiobutton_adv_dwtspec_reg', ...
   'Value',1);
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.533333333333332, ...
	'ListboxTop',0, ...
	'Min',1, ...
	'Position',[0.45 0.235 0.441 0.05], ...
	'String',{'Least Square', 'Weighted Least Square', 'Penalized Least Square', 'Lepskii Adaptive Procedure', 'Maximum Likelihood', 'Lim inf', 'Lim sup'}, ...
	'Style','popupmenu', ...
	'Tag','Radiobutton_adv_dwtspec_monolr', ...
	'Value',1);        
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_adv_dwtspec_compute(''help'')', ...
	'FontSize',0.399999999999999, ...
	'FontWeight','bold', ...
	'Position',[0.41 0.045 0.175 0.075], ...
	'String','Help', ...
	'Tag','Pushbutton1');


fl_window_init(a);