function gui_fl_fracinterp2d()
% This is the machine-generated representation of a MATLAB object
% and its children.  Note that handle values may change when these
% objects are re-created. This may cause problems with some callbacks.
% The command syntax may be supported in the future, but is currently 
% incomplete and subject to change.
%
% To re-open this system, just type the name of the m-file at the MATLAB
% prompt. The M-file and its associtated MAT-file must be on your path.

% Modified by Christian Choque Cortez, May 2010

% FracLab 2.05 Beta, Copyright © 1996 - 2009 by INRIA
% -- --
% For details on use and redistribution refer to $fraclab/licence.txt
%--------------------------------------------------------------------------

a = figure('Name','Holder interpolation 2D','Tag','Fig_gui_fl_fracinterp2d', ...
	'MenuBar','none','IntegerHandle','off','NumberTitle','off', ...
	'Position',[20 38 370 270]);

%%%%%%%%%%%%%%%%%%% CREATE FRAME %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
uicontrol('Parent',a,'Style','frame','Tag','Frame_title', ...
	'Units','normalized','Position',[0.03 0.85 0.94 0.12]);

uicontrol('Parent',a,'Style','frame','Tag','Frame_input', ...
	'Units','normalized','Position',[0.03 0.66 0.94 0.15]);

uicontrol('Parent',a,'Style','frame','Tag','Frame_parameters', ...
	'Units','normalized','Position',[0.03 0.18 0.94 0.44]);

%%%%%%%%%%%%%%%%%%% TITLE FRAME %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
uicontrol('Parent',a,'Style','text','Tag','StaticText_title', ...
	'Units','normalized','Position',[0.05 0.86 0.9 0.08], ...
	'FontUnits','normalized','FontWeight','bold','FontSize',0.6, ...
	'String','Holderian interpolation - Triangle wavelets 2D');

%%%%%%%%%%%%%%%%%%% INPUT SIGNAL %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
uicontrol('Parent',a,'Style','text','Tag','StaticText_input', ...
	'Units','normalized','Position',[0.05 0.7 0.22 0.07], ...
	'FontUnits','normalized','FontWeight','bold','FontSize',0.7, ...
	'String','Input signal','HorizontalAlignment','left');

uicontrol('Parent',a,'Style','edit','Tag','EditText_input', ...
	'Units','normalized','Position',[0.3 0.7 0.45 0.07], ...
	'FontUnits','normalized','FontSize',0.7, ...
	'String','', ...
	'Enable','inactive');

uicontrol('Parent',a,'Tag','Button_refresh', ...
	'Units','normalized', ...
	'FontUnits','normalized','FontWeight','bold','FontSize',0.4, ...
    'Position',[0.78 0.67 0.17 0.12],'String','Refresh', ...
	'Callback','fl_fracinterp2d_compute(''refresh'');');

%%%%%%%%%%%%%%%%%%%% GLOBAL PARAMETERS %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
uicontrol('Parent',a,'Style','text','Tag','StaticText_ninterp', ...
	'Units','normalized','Position',[0.05 0.5 0.45 0.07], ...
	'FontUnits','normalized','FontSize',0.7, ...
	'String','Number of interpolations','HorizontalAlignment','left');

uicontrol('Parent',a,'Style','edit','Tag','EditText_ninterp', ...
	'Units','normalized','Position',[0.45 0.51 0.15 0.075], ...
	'FontUnits','normalized','FontSize',0.6, ...
	'String','1', ...
    'Callback','fl_fracinterp2d_compute(''edit_ninterp'');');

uicontrol('Parent',a,'Style','text','Tag','StaticText_min', ...
	'Units','normalized','Position',[0.05 0.36 0.2 0.07], ...
	'FontUnits','normalized','FontSize',0.7, ...
	'String','Start Level','HorizontalAlignment','left');

uicontrol('Parent',a,'Style','edit','Tag','EditText_min', ...
	'Units','normalized','Position',[0.3 0.37 0.15 0.075], ...
	'FontUnits','normalized','FontSize',0.6, ...
	'String','2', ...
    'Callback','fl_fracinterp2d_compute(''edit_min'');');

uicontrol('Parent',a,'Style','text','Tag','StaticText_max', ...
	'Units','normalized','Position',[0.55 0.36 0.2 0.07], ...
	'FontUnits','normalized','FontSize',0.7, ...
	'String','End Level','HorizontalAlignment','left');

uicontrol('Parent',a,'Style','edit','Tag','EditText_max', ...
	'Units','normalized','Position',[0.8 0.37 0.15 0.075], ...
	'FontUnits','normalized','FontSize',0.6, ...
	'String','5', ...
    'Callback','fl_fracinterp2d_compute(''edit_max'');');

uicontrol('Parent',a,'Style','text','Tag','StaticText_wavelet', ...
	'Units','normalized','Position',[0.05 0.22 0.33 0.07], ...
	'FontUnits','normalized','FontSize',0.7, ...
	'String','Interpolating Wavelet','HorizontalAlignment','left');

uicontrol('Parent',a,'Style','popupmenu','Tag','PopupMenu_wavelet', ...
	'Units','normalized','Position',[0.45 0.24 0.25 0.07], ...
	'FontUnits','normalized','FontSize',0.6, ...
	'String',{'Triangle'}, ...
	'Value',1);

%%%%%%%%%%%%%%%%%%%% COMPUTE/HELP/CLOSE %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
uicontrol('Parent',a,'Tag','Button_compute', ...
	'Units','normalized','Position',[0.03 0.03 0.23 0.12], ...
	'FontUnits','normalized','FontWeight','bold','FontSize',0.4, ...
    'String','Compute', ...
	'Callback','eval([''global '' fl_fracinterp2d_compute(''compute'',who);]);');

uicontrol('Parent',a,'Tag','Button_help', ...
	'Units','normalized','Position',[0.39 0.03 0.23 0.12], ...
	'FontUnits','normalized','FontWeight','bold','FontSize',0.4, ...
	'String','Help', ...
    'Callback','fl_fracinterp2d_compute(''help'');');

uicontrol('Parent',a,'Tag','Button_close', ...
	'Units','normalized','Position',[0.74 0.03 0.23 0.12], ...
	'FontUnits','normalized','FontWeight','bold','FontSize',0.4, ...
	'String','Close', ...
	'Callback','fl_fracinterp2d_compute(''close'');');

fl_window_init(a);

fl_fracinterp2d_compute('refresh');
