function gui_fl_dilate()
% This is the machine-generated representation of a MATLAB object
% and its children.  Note that handle values may change when these
% objects are re-created. This may cause problems with some callbacks.
% The command syntax may be supported in the future, but is currently 
% incomplete and subject to change.
%
% To re-open this system, just type the name of the m-file at the MATLAB
% prompt. The M-file and its associtated MAT-file must be on your path.
                    
% FracLab 2.05 Beta, Copyright © 1996 - 2009 by INRIA
% -- --
% For details on use and redistribution refer to $fraclab/licence.txt
%--------------------------------------------------------------------------

a = figure( ...
	'Colormap',[], ...
	'HandleVisibility','callback', ...
	'MenuBar','none','IntegerHandle','off','NumberTitle','off', ...
	'Name','Dilation/compression', ...
	'Position',[20 50 300 250], ...
	'Tag','Fig_gui_fl_dilate');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.228310666666666, ...
	'Position',[0.05 0.746836 0.9 0.199367], ...
	'Style','frame', ...
	'Tag','Frame1');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.228310666666666, ...
	'Position',[0.05 0.225 0.9 0.49], ...
	'Style','frame', ...
	'Tag','Frame2');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','close(clf)', ...
	'FontSize',0.839999999999998, ...
	'FontWeight','bold', ...
	'Position',[0.226032 0.816456 0.55 0.0601268], ...
	'String','Dilation - Compression', ...
	'Style','text', ...
	'Tag','StaticText1');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_dmt_compute(''edit_N'')', ...
	'FontSize',0.533333333333332, ...
	'Position',[0.055 0.596 0.4 0.08], ...
	'String','Lower Frequency', ...
	'Style','text', ...
	'Tag','StaticText2');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','close(clf)', ...
	'FontSize',0.533333333333332, ...
	'Position',[0.055 0.496 0.4 0.08], ...
	'String','Higher Frequency', ...
	'Style','text', ...
	'Tag','StaticText3');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','fl_dilate_compute(''edit_fmin'')', ...
	'FontSize',0.533333333333332, ...
	'Position',[0.71 0.596 0.18 0.08], ...
	'Style','edit', ...
	'Tag','EditText_fmin');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','fl_dilate_compute(''edit_fmax'')', ...
	'FontSize',0.533333333333332, ...
	'Position',[0.71 0.496 0.18 0.08], ...
	'Style','edit', ...
	'Tag','EditText_fmax');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','close(clf)', ...
	'FontSize',0.533333333333332, ...
	'Position',[0.055 0.396 0.4 0.08], ...
	'String','Number of Points', ...
	'Style','text', ...
	'Tag','StaticText4');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','fl_dilate_compute(''edit_N'')', ...
	'FontSize',0.533333333333332, ...
	'Position',[0.71 0.396 0.18 0.08], ...
	'Style','edit', ...
	'Tag','EditText_N');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','eval([''global '' fl_dilate_compute(''compute'',who)])', ...
	'FontSize',0.399999999999999, ...
	'FontWeight','bold', ...
	'Position',[0.0966667 0.08 0.233333 0.12], ...
	'String','Compute', ...
	'Tag','Pushbutton_compute');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_dilate_compute(''help'')', ...
	'FontSize',0.399999999999999, ...
	'FontWeight','bold', ...
	'Position',[0.383333 0.08 0.233333 0.12], ...
	'String','Help', ...
	'Tag','Pushbutton_help');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','close(clf)', ...
	'FontSize',0.399999999999999, ...
	'FontWeight','bold', ...
	'Position',[0.666667 0.08 0.233333 0.12], ...
	'String','Close', ...
	'Tag','Pushbutton_close');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.533333333333332, ...
	'FontWeight','bold', ...
	'Position',[0.055 0.276 0.4 0.08], ...
	'String','Scale Factor', ...
	'Style','text', ...
	'Tag','StaticText5');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','fl_dilate_compute(''edit_scale'')', ...
	'FontSize',0.533333333333332, ...
	'Position',[0.71 0.276 0.18 0.08], ...
	'String','2', ...
	'Style','edit', ...
	'Tag','EditText_scale');


fl_window_init(a);