function fig = gui_fl_pseudoaw()
% This is the machine-generated representation of a MATLAB object
% and its children.  Note that handle values may change when these
% objects are re-created. This may cause problems with some callbacks.
% The command syntax may be supported in the future, but is currently 
% incomplete and subject to change.
%
% To re-open this system, just type the name of the m-file at the MATLAB
% prompt. The M-file and its associtated MAT-file must be on your path.

% FracLab 2.05 Beta, Copyright © 1996 - 2009 by INRIA
% -- --
% For details on use and redistribution refer to $fraclab/licence.txt
%--------------------------------------------------------------------------                 

a = figure('Name','Pseudo Affine Wigner','Tag','Fig_gui_fl_pseudoaw', ...
	'MenuBar','none','IntegerHandle','off','NumberTitle','off', ...
	'Position',[20 38 401 300]);

%%%%%%%%%%%%%%%%%%% CREATE FRAME %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
uicontrol('Parent',a,'Style','frame','Tag','Frame_title', ...
	'Units','normalized','Position',[0.02 0.89 0.96 0.09]);

uicontrol('Parent',a,'Style','frame','Tag','Frame_input', ...
	'Units','normalized','Position',[0.02 0.73 0.96 0.14]);

uicontrol('Parent',a,'Style','frame','Tag','Frame_parameters', ...
	'Units','normalized','Position',[0.02 0.16 0.96 0.55]);

%%%%%%%%%%%%%%%%%%% TITLE FRAME %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
uicontrol('Parent',a,'Style','text','Tag','StaticText_title', ...
	'Units','normalized','Position',[0.14 0.895 0.7 0.07], ...
	'FontUnits','normalized','FontWeight','bold','FontSize',0.6, ...
	'String','Pseudo Affine Wigner Distribution');

%%%%%%%%%%%%%%%%%%% INPUT SIGNAL %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
uicontrol('Parent',a,'Style','text','Tag','StaticText_input', ...
	'Units','normalized','Position',[0.04 0.75 0.2 0.07], ...
	'FontUnits','normalized','FontWeight','bold','FontSize',0.6, ...
	'String','Input Signal','HorizontalAlignment','left');

uicontrol('Parent',a,'Style','edit','Tag','EditText_input', ...
	'Units','normalized','Position',[0.3 0.765 0.4 0.07], ...
	'FontUnits','normalized','FontSize',0.6, ...
    'String','', ...
	'Enable','inactive');

uicontrol('Parent',a,'Tag','Button_refresh', ...
	'Units','normalized','Position',[0.77 0.745 0.17 0.11], ...
	'FontUnits','normalized','FontWeight','bold','FontSize',0.4, ...
    'String','Refresh', ...
    'Callback','fl_pseudoaw_compute(''refresh'');');

%%%%%%%%%%%%%%%%%%%% GLOBAL PARAMETERS %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
uicontrol('Parent',a,'Style','text','Tag','StaticText_fmin', ...
	'Units','normalized','Position',[0.04 0.59 0.15 0.07], ...
	'FontUnits','normalized','FontSize',0.6, ...
	'String','fmin','HorizontalAlignment','left');

uicontrol('Parent',a,'Style','edit','Tag','EditText_fmin', ...
	'Units','normalized','Position',[0.13 0.61 0.18 0.07], ...
	'FontUnits','normalized','FontSize',0.6, ...
    'String',2^(-5), ...
	'Callback','fl_pseudoaw_compute(''edit_fmin'');');

uicontrol('Parent',a,'Style','popupmenu','Tag','PopupMenu_fmin', ...
	'Units','normalized','Position',[0.32 0.615 0.17 0.07], ...
	'FontUnits','normalized','FontSize',0.6, ...
	'Callback','fl_pseudoaw_compute(''popmenu_fmin'');', ...
	'String',{'2^(-5)', '2^(-4)', '2^(-3)', '2^(-2)'}, ...
	'Value',1);

uicontrol('Parent',a,'Style','text','Tag','StaticText_fmax', ...
	'Units','normalized','Position',[0.51 0.59 0.15 0.07], ...
	'FontUnits','normalized','FontSize',0.6, ...
	'String','fmax','HorizontalAlignment','left');

uicontrol('Parent',a,'Style','edit','Tag','EditText_fmax', ...
	'Units','normalized','Position',[0.6 0.61 0.18 0.07], ...
	'FontUnits','normalized','FontSize',0.6, ...
    'String','0.5', ...
	'Callback','fl_pseudoaw_compute(''edit_fmax'');');

uicontrol('Parent',a,'Style','popupmenu','Tag','PopupMenu_fmax', ...
	'Units','normalized','Position',[0.79 0.615 0.17 0.07], ...
	'FontUnits','normalized','FontSize',0.6, ...
	'Callback','fl_pseudoaw_compute(''popmenu_fmax'');', ...
	'String',{'2^(-1)', '2^(-2)', '2^(-3)', '2^(-4)'}, ...
	'Value',1);

uicontrol('Parent',a,'Style','text','Tag','StaticText_voices', ...
	'Units','normalized','Position',[0.04 0.48 0.15 0.07], ...
	'FontUnits','normalized','FontSize',0.6, ...
	'String','Voices','HorizontalAlignment','left');

uicontrol('Parent',a,'Style','edit','Tag','EditText_voices', ...
	'Units','normalized','Position',[0.19 0.5 0.12 0.07], ...
	'FontUnits','normalized','FontSize',0.6, ...
    'String','128', ...
	'Callback','fl_pseudoaw_compute(''edit_voices'');');

uicontrol('Parent',a,'Style','popupmenu','Tag','PopupMenu_voices', ...
	'Units','normalized','Position',[0.34 0.505 0.15 0.07], ...
	'FontUnits','normalized','FontSize',0.6, ...
	'Callback','fl_pseudoaw_compute(''popmenu_voices'');', ...
	'String',{'2', '4', '8', '16', '32', '64', '128', '256'}, ...
	'Value',7);

uicontrol('Parent',a,'Style','text','Tag','StaticTextf_distribution', ...
	'Units','normalized','Position',[0.04 0.38 0.16 0.07], ...
	'FontUnits','normalized','FontSize',0.6, ...
	'String','Distribution','HorizontalAlignment','left');

uicontrol('Parent',a,'Style','popupmenu','Tag','PopupMenu_distribution', ...
	'Units','normalized','Position',[0.22 0.4 0.27 0.07], ...
	'FontUnits','normalized','FontSize',0.6, ...
	'String',{'Unterberger', 'Bertrand', 'D-Flandrin', 'Wigner'}, ...
	'Value',2, ...
    'Callback','fl_pseudoaw_compute(''popmenu_distribution'');');

uicontrol('Parent',a,'Style','text','Tag','StaticText_kvalue', ...
	'Units','normalized','Position',[0.51 0.38 0.15 0.07], ...
	'FontUnits','normalized','FontSize',0.6, ...
	'String','K value','HorizontalAlignment','left');

uicontrol('Parent',a,'Style','edit','Tag','EditText_kvalue', ...
	'Units','normalized','Position',[0.66 0.4 0.12 0.07], ...
	'FontUnits','normalized','FontSize',0.6, ...
	'String','0', ...
    'Callback','fl_pseudoaw_compute(''edit_kvalue'');');

uicontrol('Parent',a,'Style','text','Tag','StaticText_wavelet', ...
	'Units','normalized','Position',[0.04 0.27 0.17 0.07], ...
	'FontUnits','normalized','FontSize',0.6, ...
	'String','Wavelet','HorizontalAlignment','left');

uicontrol('Parent',a,'Style','popupmenu','Tag','PopupMenu_wavelet', ...
	'Units','normalized','Position',[0.22 0.29 0.27 0.07], ...
	'FontUnits','normalized','FontSize',0.6, ...
	'String',{'Mexican hat','Morlet (real)','Morlet (analytic)'}, ...
	'Value',1, ...
    'Callback','fl_pseudoaw_compute(''popmenu_wavelet'');');

uicontrol('Parent',a,'Style','text','Tag','StaticText_wave', ...
	'Units','normalized','Position',[0.51 0.27 0.15 0.07], ...
	'FontUnits','normalized','FontSize',0.6, ...
	'String','Size','Enable','off','HorizontalAlignment','left');

uicontrol('Parent',a,'Style','edit','Tag','EditText_wave', ...
	'Units','normalized','Position',[0.66 0.29 0.12 0.07], ...
	'FontUnits','normalized','FontSize',0.6, ...
	'Callback','fl_pseudoaw_compute(''edit_wave'');', ...
	'String','0','Enable','off', ...
    'Callback','fl_pseudoaw_compute(''edit_wave'');');

uicontrol('Parent',a,'Style','text','Tag','StaticText_smooth', ...
	'Units','normalized','Position',[0.04 0.165 0.15 0.07], ...
	'FontUnits','normalized','FontSize',0.6, ...
	'String','Smoothing','HorizontalAlignment','left');

uicontrol('Parent',a,'Style','edit','Tag','EditText_smooth', ...
	'Units','normalized','Position',[0.22 0.185 0.12 0.07], ...
	'FontUnits','normalized','FontSize',0.6, ...
	'Callback','fl_pseudoaw_compute(''edit_smooth'');', ...
	'String','0');

%%%%%%%%%%%%%%%%%%%% COMPUTE/HELP/CLOSE %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
uicontrol('Parent',a,'Tag','Button_compute', ...
	'Units','normalized','Position',[0.022 0.02 0.2 0.11], ...
	'FontUnits','normalized','FontWeight','bold','FontSize',0.4, ...
    'String','Compute', ...
	'Callback','eval([''global '' fl_pseudoaw_compute(''compute'',who)])');

uicontrol('Parent',a,'Tag','Button_help', ...
	'Units','normalized','Position',[0.41 0.02 0.2 0.11], ...
	'FontUnits','normalized','FontWeight','bold','FontSize',0.4, ...
    'String','Help', ...
	'Callback','fl_pseudoaw_compute(''help'');');

uicontrol('Parent',a,'Tag','Button_close', ...
	'Units','normalized','Position',[0.78 0.02 0.2 0.11], ...
	'FontUnits','normalized','FontWeight','bold','FontSize',0.4, ...
	'String','Close', ...
	'Callback','fl_pseudoaw_compute(''close'');');

fl_window_init(a);

if nargout > 0, fig = a; end

fl_pseudoaw_compute('refresh');