function gui_fl_stable_syn()
% This is the machine-generated representation of a MATLAB object
% and its children.  Note that handle values may change when these
% objects are re-created. This may cause problems with some callbacks.
% The command syntax may be supported in the future, but is currently 
% incomplete and subject to change.
%
% To re-open this system, just type the name of the m-file at the MATLAB
% prompt. The M-file and its associtated MAT-file must be on your path.
               
% FracLab 2.05 Beta, Copyright © 1996 - 2009 by INRIA
% -- --
% For details on use and redistribution refer to $fraclab/licence.txt
%--------------------------------------------------------------------------

a = figure( ...
	'Colormap',[], ...
	'HandleVisibility','callback', ...
	'MenuBar','none','IntegerHandle','off','NumberTitle','off', ...
	'Name','Synthesis of Stable Motion', ...
	'Position',[20 50 400 400], ...
	'Tag','Fig_gui_fl_stable_syn', ...
	'UserData',0.00390625);
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.266666666666666, ...
	'Position',[0.05 0.7975  0.9 0.125], ...
	'Style','frame', ...
	'Tag','Frame_gui_fl_stable_syn');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.551723999999999, ...
	'FontWeight','bold', ...
	'Position',[0.26 0.835 0.5 0.0475], ...
	'String','Synthesis of Stable Motion', ...
	'Style','text', ...
	'Tag','StaticText_gui_fl_stable_syn');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.0758293333333331, ...
	'Position',[0.05 0.234374 0.9 0.502233], ...
	'Style','frame', ...
	'Tag','Frame_gui_fl_stable_syn2');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.571427999999998, ...
	'HorizontalAlignment','left', ...
	'Position',[0.1 0.61 0.375 0.0475], ...
	'String','Characteristic Exponent', ...
	'Style','text', ...
	'Tag','StaticText_cara_expo');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.551723999999999, ...
	'HorizontalAlignment','left', ...
	'Position',[0.1 0.5225 0.375 0.0475], ...
	'String','Skewness Parameter', ...
	'Style','text', ...
	'Tag','StaticText_skew_par');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.551723999999999, ...
	'HorizontalAlignment','left', ...
	'Position',[0.1 0.435 0.375 0.0475], ...
	'String','Location Parameter', ...
	'Style','text', ...
	'Tag','StaticText_loc_par');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.551723999999999, ...
	'HorizontalAlignment','left', ...
	'Position',[0.1 0.3475 0.375 0.0475], ...
	'String','Scale Parameter', ...
	'Style','text', ...
	'Tag','StaticText_scale_par');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.551723999999999, ...
	'HorizontalAlignment','left', ...
	'Position',[0.1 0.26 0.375 0.0475], ...
	'String','Sample Size', ...
	'Style','text', ...
	'Tag','StaticText_sam_size');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','fl_stable_function(''edittext_stable_alpha'');', ...
	'FontSize',0.551723999999999, ...
	'Position',[0.75 0.61 0.15 0.05], ...
	'String','1.5', ...
	'Style','edit', ...
	'Tag','EditText_stable_alpha');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_stable_function(''slider_stable_alpha'') ;', ...
	'FontSize',0.551723999999999, ...
	'Max',2, ...
	'Position',[0.47 0.61 0.25 0.05], ...
	'Style','slider', ...
	'Tag','Slider_stable_alpha', ...
	'Value',1.5);
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','fl_stable_function(''edittext_stable_beta'');', ...
	'FontSize',0.533333333333332, ...
	'Position',[0.75 0.5225 0.15 0.05], ...
	'String','0', ...
	'Style','edit', ...
	'Tag','EditText_stable_beta');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_stable_function(''slider_stable_beta'');', ...
	'FontSize',0.533333333333332, ...
	'Min',-1, ...
	'Position',[0.47 0.5225 0.25 0.05], ...
	'Style','slider', ...
	'Tag','Slider_stable_beta');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','fl_stable_function(''edittext_stable_mu'');', ...
	'FontSize',0.533333333333332, ...
	'Position',[0.75 0.435 0.15 0.05], ...
	'String','0', ...
	'Style','edit', ...
	'Tag','EditText_stable_mu');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','fl_stable_function(''edittext_stable_gamma'');', ...
	'FontSize',0.533333333333332, ...
	'Position',[0.75 0.3475 0.15 0.05], ...
	'String','1', ...
	'Style','edit', ...
	'Tag','EditText_stable_gamma');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','fl_stable_function(''edittext_stable_ssize'');', ...
	'FontSize',0.533333333333332, ...
	'Position',[0.75 0.26 0.15 0.05], ...
	'String','5000', ...
	'Style','edit', ...
	'Tag','EditText_stable_ssize');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','close(gcf);', ...
	'FontSize',0.399999999999999, ...
	'FontWeight','bold', ...
	'Position',[0.698215 0.0736608 0.175 0.075], ...
	'String','Close', ...
	'Tag','Pushbutton_stable_syn_close');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_stable_function(''bushbutton_stable_syn_help'');', ...
	'FontSize',0.399999999999999, ...
	'FontWeight','bold', ...
	'Position',[0.4 0.0736608 0.175 0.075], ...
	'String','Help', ...
	'Tag','Pushbutton_stable_syn_help');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','eval([''global '' fl_stable_function(''pushbutton_stable_syn_compute'',who)]);', ...
	'FontSize',0.399999999999999, ...
	'FontWeight','bold', ...
	'Position',[0.1 0.0736608 0.175 0.075], ...
	'String','Compute', ...
	'Tag','Pushbutton_stable_syn_compute');

fl_window_init(a);