function fig = gui_fl_wavereg1d()
% This is the machine-generated representation of a MATLAB object
% and its children.  Note that handle values may change when these
% objects are re-created. This may cause problems with some callbacks.
% The command syntax may be supported in the future, but is currently 
% incomplete and subject to change.
%
% To re-open this system, just type the name of the m-file at the MATLAB
% prompt. The M-file and its associtated MAT-file must be on your path.
                  
% FracLab 2.05 Beta, Copyright © 1996 - 2009 by INRIA
% -- --
% For details on use and redistribution refer to $fraclab/licence.txt
%--------------------------------------------------------------------------

a = figure('Name','Regularization 1D','Tag','Fig_gui_fl_wavereg1d', ...
    'MenuBar','none','IntegerHandle','off','NumberTitle','off', ...
	'Position',[20 50 320 270]);

%%%%%%%%%%%%%%%%%%% CREATE FRAME %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
uicontrol('Parent',a,'Style','frame','Tag','Frame_title', ...
	'Units','normalized','Position',[0.04 0.81 0.92 0.15]);

uicontrol('Parent',a,'Style','frame','Tag','Frame_input', ...
	'Units','normalized','Position',[0.04 0.63 0.92 0.15]);

uicontrol('Parent',a,'Style','frame','Tag','Frame_parameters', ...
	'Units','normalized','Position',[0.04 0.2 0.92 0.39]);

%%%%%%%%%%%%%%%%%%% TITLE FRAME %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
uicontrol('Parent',a,'Style','text','Tag','StaticText_title', ...
	'Units','normalized','Position',[0.09 0.84 0.8 0.075], ...
	'FontUnits','normalized','FontWeight','bold','FontSize',0.6, ...
	'String','Multifractal Regularization 1D');

%%%%%%%%%%%%%%%%%%% INPUT SIGNAL %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
uicontrol('Parent',a,'Style','text','Tag','StaticText_input', ...
	'Units','normalized','Position',[0.06 0.65 0.4 0.07], ...
	'FontUnits','normalized','FontWeight','bold','FontSize',0.6, ...
	'String','Input signal','HorizontalAlignment','left');

uicontrol('Parent',a,'Style','edit','Tag','EditText_input', ...
	'Units','normalized','Position',[0.3 0.66 0.42 0.07], ...
	'FontUnits','normalized','FontSize',0.6, ...
	'String','', ...
	'Enable','inactive');

uicontrol('Parent',a,'Tag','Button_refresh', ...
	'Units','normalized','Position',[0.76 0.65 0.175 0.1], ...
	'FontUnits','normalized','FontWeight','bold','FontSize',0.4, ...
    'String','Refresh', ...
	'Callback','fl_wavereg1d_compute(''refresh'');');

%%%%%%%%%%%%%%%%%%%% GLOBAL PARAMETERS %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
uicontrol('Parent',a,'Style','text','Tag','StaticText_wavelet', ...
	'Units','normalized','Position',[0.06 0.47 0.17 0.07], ...
	'FontUnits','normalized','FontSize',0.6, ...
	'String','Wavelet','HorizontalAlignment','left');

uicontrol('Parent',a,'Style','popupmenu','Tag','PopupMenu_wavelet', ...
	'Units','normalized','Position',[0.43 0.495 0.4 0.07], ...
	'FontUnits','normalized','FontSize',0.6, ...
	'String',{'Daubechies 2','Daubechies 4','Daubechies 6','Daubechies 8', ...
              'Daubechies 10','Daubechies 12','Daubechies 14','Daubechies 16', ...
              'Daubechies 18','Daubechies 20','Coiflet 6','Coiflet 12','Coiflet 18','Coiflet 24'}, ...
	'Value',5);

uicontrol('Parent',a,'Style','text','Tag','StaticText_regularity', ...
	'Units','normalized','Position',[0.06 0.34 0.35 0.07], ...
	'FontUnits','normalized','FontSize',0.6, ...
	'String','Regularity Increase','HorizontalAlignment','left');

uicontrol('Parent',a,'Style','edit','Tag','EditText_regularity', ...
	'Units','normalized','Position',[0.43 0.36 0.15 0.07], ...
	'FontUnits','normalized','FontSize',0.6, ...
    'String','0.5', ...
	'Callback','fl_wavereg1d_compute(''edit_regularity'');');

uicontrol('Parent',a,'Style','text','Tag','StaticText_level', ...
	'Units','normalized','Position',[0.06 0.22 0.2 0.07], ...
	'FontUnits','normalized','FontSize',0.6, ...
	'String','Start level','HorizontalAlignment','left');

uicontrol('Parent',a,'Style','edit','Tag','EditText_level', ...
	'Units','normalized','Position',[0.28 0.24 0.15 0.07], ...
	'FontUnits','normalized','FontSize',0.6, ...
	'Callback','fl_wavereg1d_compute(''edit_level'');', ...
	'String','');

uicontrol('Parent',a,'Style','checkbox','Tag','Check_norm', ...
    'Units','normalized','Position',[0.48 0.23 0.45 0.07], ...
    'FontUnits','normalized','FontSize',0.6, ... 
    'String','Kullback normalization', ...
    'Value',0, ...
    'Callback','fl_wavereg1d_compute(''check_norm'');');

%%%%%%%%%%%%%%%%%%%% COMPUTE/HELP/CLOSE %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
uicontrol('Parent',a,'Tag','Button_compute', ...
	'Units','normalized','Position',[0.045 0.04 0.23 0.12], ...
	'FontUnits','normalized','FontWeight','bold','FontSize',0.4, ...
    'String','Compute', ...
	'Callback','eval([''global '' fl_wavereg1d_compute(''compute'',who)])');

uicontrol('Parent',a,'Tag','Button_help', ...
	'Units','normalized','Position',[0.39 0.04 0.23 0.12], ...
	'FontUnits','normalized','FontWeight','bold','FontSize',0.4, ...
    'String','Help', ...
	'Callback','fl_wavereg1d_compute(''help'');');

uicontrol('Parent',a,'Tag','Button_close', ...
	'Units','normalized','Position',[0.73 0.04 0.23 0.12], ...
	'FontUnits','normalized','FontWeight','bold','FontSize',0.4, ...
    'String','Close', ...
	'Callback','fl_wavereg1d_compute(''close'');');

fl_window_init(a);

if nargout > 0, fig = a; end

fl_wavereg1d_compute('refresh');
