function gui_normalize()
% This is the machine-generated representation of a MATLAB object
% and its children.  Note that handle values may change when these
% objects are re-created. This may cause problems with some callbacks.
% The command syntax may be supported in the future, but is currently 
% incomplete and subject to change.
%
% To re-open this system, just type the name of the m-file at the MATLAB
% prompt. The M-file and its associtated MAT-file must be on your path.

% FracLab 2.05 Beta, Copyright © 1996 - 2009 by INRIA
% -- --
% For details on use and redistribution refer to $fraclab/licence.txt
%--------------------------------------------------------------------------

a = figure('Units','pixels', ...
	'MenuBar','none','IntegerHandle','off','NumberTitle','off', ...
	'Position',[20 80 300 250], ...
	'HandleVisibility','callback', ...
	'Name','Normalization','Tag','Fig_gui_normalize');
    
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.342857142857143, ...
	'ListboxTop',0, ...
	'Position',[0.02 0.84 0.96 0.14], ...
	'Style','frame', ...
	'Tag','Frame1');    
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.872727272727273, ...
	'FontWeight','bold', ...
	'HorizontalAlignment','center', ...
	'Position',[0.1 0.89 0.8 0.055], ...
	'String','Normalize', ...
	'Style','text', ...
	'Tag','StaticText1');
    
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.0695652173913043, ...
	'ListboxTop',0, ...
	'Position',[0.02 0.44 0.96 0.38], ...
	'Style','frame', ...
	'Tag','Frame2');    
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.872727272727273, ...
	'FontWeight','bold', ...
	'HorizontalAlignment','center', ...
	'Position',[0.1 0.76 0.8 0.055], ...
	'String',' Data', ...
	'Style','text', ...
	'Tag','StaticText1');

    % Input
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.7, ...
	'HorizontalAlignment','left', ...
	'Position',[0.05 0.65 0.18 0.07], ...
	'String','Input', ...
	'Style','text', ...
	'Tag','StaticText1');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',0.6, ...
	'Position',[0.27 0.66 0.49 0.07], ...
	'Style','edit', ...
	'Tag','Text_input');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_normalize_compute(''get_input_name'');', ...
	'FontSize',0.6, ...
	'Position',[0.79 0.66 0.16 0.07], ...
	'String','Refresh', ...
	'Tag','Pushbutton1');

    
    % output
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.7, ...
	'HorizontalAlignment','left', ...
	'Position',[0.05 0.53 0.18 0.07], ...
	'String','Output', ...
	'Style','text', ...
	'Tag','StaticText1');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',0.6, ...
	'Position',[0.27 0.54 0.49 0.07], ...
	'Style','edit', ...
	'Tag','Text_output');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_normalize_compute(''get_output_name'');', ...
	'FontSize',0.6, ...
	'Position',[0.79 0.54 0.16 0.07], ...
	'String','Refresh', ...
	'Tag','Pushbutton1');


b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.0695652173913043, ...
	'ListboxTop',0, ...
	'Position',[0.02 0.16 0.96 0.26], ...
	'Style','frame', ...
	'Tag','Frame3');    
	


b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.685714285714286, ...
	'ListboxTop',0, ...
	'Position',[0.07    0.26    0.15    0.07], ...
	'String','min', ...
	'Style','text', ...
	'Tag','StaticText_min');

b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','fl_normalize_compute(''edit_min'');', ...
	'FontSize',0.6, ...
	'ListboxTop',0, ...
	'String','0', ...
	'Position',[0.24    0.26    0.16    0.07], ...
	'Style','edit', ...
	'Tag','EditText_min');


b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.685714285714286, ...
	'ListboxTop',0, ...
	'Position',[0.5    0.26   0.15    0.07], ...
	'String','max', ...
	'Style','text', ...
	'Tag','StaticText_max');	
	

b = uicontrol('Parent',a, ...
        'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','fl_normalize_compute(''edit_max'');', ...
	'FontSize',0.6, ...
	'ListboxTop',0, ...
	'String','1', ...
	'Position',[ 0.67 0.26 0.16    0.07], ...
	'Style','edit', ...
	'Tag','EditText_max');



   
    % general
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','eval([''global '' fl_normalize_compute(''compute_normalize'');]);', ...
	'FontSize',0.436363636363636, ...
	'FontWeight','bold', ...
	'Position',[0.1 0.02 0.3 0.11], ...
	'String','Compute', ...
	'Tag','Pushbutton_Create');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_function(''close'');', ...
	'FontSize',0.436363636363636, ...
	'FontWeight','bold', ...
	'Position',[0.6 0.02 0.3 0.11], ...
	'String','Close', ...
	'Tag','Pushbutton_close');
	
fl_window_init(a);
