function gui_fl_adv_track()
% This is the machine-generated representation of a MATLAB object
% and its children.  Note that handle values may change when these
% objects are re-created. This may cause problems with some callbacks.
% The command syntax may be supported in the future, but is currently 
% incomplete and subject to change.
%
% To re-open this system, just type the name of the m-file at the MATLAB
% prompt. The M-file and its associtated MAT-file must be on your path.

% FracLab 2.05 Beta, Copyright © 1996 - 2009 by INRIA
% -- --
% For details on use and redistribution refer to $fraclab/licence.txt
%--------------------------------------------------------------------------

a = figure( ...
	'Colormap',[], ...
	'HandleVisibility','callback', ...
	'MenuBar','none','IntegerHandle','off','NumberTitle','off', ...
	'Position',[20 50 400 500], ...
	'Name','cwt advanced Estimation','Tag','Fig_gui_fl_adv_track');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.3, ...
	'Position',[0.025 0.8 0.95 0.08], ...
	'Style','frame', ...
	'Tag','Frame_input');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.48, ...
	'FontWeight','bold', ...
	'HorizontalAlignment','left', ...
	'Position',[0.06 0.805 0.25 0.05], ...
	'String','Input Signal', ...
	'Style','text', ...
	'Tag','StaticText_input');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',0.48, ...
	'HorizontalAlignment','left', ...
	'Position',[0.32 0.815 0.4 0.05], ...
	'Style','edit', ...
	'Enable','inactive',...
	'Tag','EditText_sig_nname');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_adv_track_compute(''refresh'');', ...
	'FontSize',0.4, ...
	'FontWeight','bold', ...
	'Position',[0.75 0.81 0.175 0.06], ...
	'String','Refresh', ...
	'Tag','refresh_input');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.3, ...
	'Position',[0.025 0.37 0.95 0.08], ...
	'Style','frame', ...
	'Tag','Frame_inputcwt');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.48, ...
	'FontWeight','bold', ...
	'HorizontalAlignment','left', ...
	'Position',[0.0525 0.38 0.25 0.05], ...
	'String','Input CWT', ...
	'Style','text', ...
	'Tag','StaticText_inputcwt');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',0.48, ...
	'HorizontalAlignment','left', ...
	'Position',[0.3225 0.386 0.4 0.05], ...
	'Style','edit', ...
	'Enable','inactive',...
	'Tag','EditText_cwt_nname');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_adv_track_compute(''refresh_cwt'');', ...
	'FontSize',0.4, ...
	'FontWeight','bold', ...
	'Position',[0.75 0.38 0.175 0.06], ...
	'String','Refresh', ...
	'Tag','refresh_inputcwt');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.0727272727272727, ...
	'Position',[0.025 0.46 0.95 0.33], ...
	'Style','frame', ...
	'Tag','Frame_param');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.129032258064516, ...
	'Position',[0.025 0.172 0.95 0.186], ...
	'Style','frame', ...
	'Tag','Frame_param');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',0.533333333333332, ...
	'Position',[0.0425 0.696 0.1825 0.04], ...
	'String','0.015625', ...
	'Style','edit', ...
	'Tag','EditText_cwt_fmin');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','fl_adv_track_compute(''cwt_editf'');', ...
	'FontSize',0.533333333333332, ...
	'Position',[0.575 0.696 0.185 0.04], ...
	'String','0.5', ...
	'Style','edit', ...
   'Tag','EditText_cwt_fmax');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_adv_track_compute(''cwt_ppm_fmin'');', ...
	'FontSize',0.516129333333332, ...
	'Max',6, ...
	'Min',1, ...
	'Position',[0.2625 0.696 0.1825 0.042], ...
	'String',{'2^(-6)','2^(-5)','2^(-4)', '2^(-3)', '2^(-2)', '2^(-1)'}, ...
	'Style','popupmenu', ...
	'Tag','PopupMenu_cwt_fmin', ...
	'Value',1);
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_adv_track_compute(''cwt_ppm_fmax'');', ...
	'FontSize',0.516129333333332, ...
	'Max',6, ...
	'Min',1, ...
	'Position',[0.7775 0.696 0.1825 0.042], ...
	'String',{'2^(-1)', '2^(-2)', '2^(-3)', '2^(-4)', '2^(-5)', '2^(-6)'}, ...
	'Style','popupmenu', ...
	'Tag','PopupMenu_cwt_fmax', ...
	'Value',1);
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.551723999999999, ...
	'Position',[0.0425 0.736 0.185 0.038], ...
	'String','fmin', ...
	'Style','text', ...
	'Tag','StaticTextf_cwt_fmin');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.551723999999999, ...
	'Position',[0.5725 0.734 0.1875 0.038], ...
	'String','fmax', ...
	'Style','text', ...
	'Tag','StaticText_cwt_fmax');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.146789333333333, ...
	'Position',[0.045 0.482 0.505 0.198], ...
	'Style','frame', ...
	'Tag','Frame_wavelet');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.551723999999999, ...
	'FontWeight','demi', ...
	'Position',[0.195 0.63 0.2075 0.038], ...
	'String','Wavelet', ...
	'Style','text', ...
	'Tag','StaticText_cwt_wavelet');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.551723999999999, ...
	'Position',[0.0575 0.578 0.125 0.038], ...
	'String','Size', ...
	'Style','text', ...
	'Tag','StaticTextf_cwt_wsize');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',0.533333333333332, ...
	'Position',[0.34 0.578 0.1825 0.04], ...
	'String','8', ...
	'Style','edit', ...
	'Tag','EditText_cwt_wsize');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.551723999999999, ...
	'Position',[0.0575 0.516 0.125 0.038], ...
	'String','Type', ...
	'Style','text', ...
	'Tag','StaticTextf_cwt_wtype');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_adv_track_compute(''cwt_ppm_wtype'');', ...
	'FontSize',0.516129333333332, ...
	'Max',3, ...
	'Min',1, ...
	'Position',[0.18 0.516 0.3425 0.042], ...
	'String',{'Mexican Hat', 'Morlet (real)', 'Morlet (analytic)'}, ...
	'Style','popupmenu', ...
	'Tag','PopupMenu_cwt_wtype', ...
	'Value',3);
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_adv_track_compute(''cwt_rb_mirror'');', ...
	'FontSize',0.533333333333332, ...
	'Position',[0.6075 0.552 0.35 0.04], ...
	'String','Mirror', ...
	'Style','Checkbox', ...
	'Tag','Radiobutton_cwt_mirror', ...
	'Value',1);
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.551723999999999, ...
	'Position',[0.5775 0.646 0.1825 0.038], ...
	'String','Voices', ...
	'Style','text', ...
	'Tag','StaticText_cwt_voices');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','fl_adv_track_compute(''cwt_edit_voices'');', ...
	'FontSize',0.533333333333332, ...
	'Position',[0.575 0.6 0.185 0.04], ...
	'String','128', ...
	'Style','edit', ...
	'Tag','EditText_cwt_voices');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_adv_track_compute(''close'')', ...
	'FontSize',0.399999999999999, ...
	'FontWeight','bold', ...
	'Position',[0.6725 0.092 0.175 0.06], ...
	'String','Close', ...
	'Tag','Pushbutton_cwt_wclose');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','eval([''global '' fl_adv_track_compute(''compute_HofT'',who)]) ;', ...
	'FontSize',0.399999999999999, ...
	'FontWeight','bold', ...
	'Position',[0.1175 0.092 0.175 0.06], ...
	'String','Compute', ...
	'Tag','Pushbutton_HofT_compute');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_adv_track_compute(''cwt_ppm_voices'');', ...
	'FontSize',0.516129333333332, ...
	'Max',8, ...
	'Min',1, ...
	'Position',[0.7775 0.602 0.18 0.042], ...
	'String',{'2', '4', '8', '16', '32', '64', '128', '256'}, ...
	'Style','popupmenu', ...
	'Tag','PopupMenu_cwt_voices', ...
   'Value',7);
[SigIn_name error_in] = fl_get_input ('vector') ;
eval(['global ' SigIn_name]) ;
SigIn = eval(SigIn_name) ;
N = length(SigIn) ;
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','fl_adv_track_compute(''edit_time'')', ...
	'FontSize',0.533333333333332, ...
	'Position',[0.3225 0.296 0.11 0.04], ...
	'String',num2str(floor(N/2)), ...
	'Style','edit', ...
	'Tag','EditText_adv_track_time');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','fl_adv_track_compute(''edit_radius'')', ...
	'FontSize',0.533333333333332, ...
	'Position',[0.3225 0.236 0.11 0.04], ...
	'String','8', ...
	'Style','edit', ...
	'Tag','EditText_adv_track_radius');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','fl_adv_track_compute(''edit_deepscale'')', ...
	'FontSize',0.533333333333332, ...
	'Position',[0.3225 0.186 0.11 0.04], ...
	'String','1', ...
	'Style','edit', ...
	'Tag','EditText_adv_track_deepscale');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_adv_track_compute(''radiobutton_findmax'')', ...
	'FontSize',0.533333333333332, ...
	'Position',[0.8275 0.178 0.1375 0.04], ...
	'String','No', ...
	'Style','Checkbox', ...
	'Tag','Radiobutton_adv_track_findmax', ...
	'Value',0);
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.551723999999999, ...
	'Position',[0.0475 0.296 0.25 0.038], ...
	'String','Time Instant', ...
	'Style','text', ...
	'Tag','StaticText1');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.551723999999999, ...
	'Position',[0.0475 0.236 0.25 0.038], ...
	'String','Radius', ...
	'Style','text', ...
	'Tag','StaticText2');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.551723999999999, ...
	'Position',[0.0475 0.186 0.25 0.038], ...
	'String','Scale-Depth', ...
	'Style','text', ...
	'Tag','StaticText3');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.551723999999999, ...
	'Position',[0.525 0.178 0.2125 0.038], ...
	'String','Local Maxima', ...
	'Style','text', ...
	'Tag','StaticText4', ...
	'Value',1);
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.551723999999999, ...
	'FontWeight','bold', ...
	'Position',[0.1 0.028 0.4 0.038], ...
	'String','Pointwise Exponent', ...
	'Style','text', ...
	'Tag','StaticText7');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',0.516129333333332, ...
	'Position',[0.575 0.028 0.28 0.042], ...
	'Style','edit', ...
	'Tag','EditText_adv_track_HofT');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','eval([''global '' fl_adv_track_compute(''cwt_compute'',who)]);', ...
	'FontSize',0.399999999999999, ...
	'FontWeight','bold', ...
	'Position',[0.605 0.48 0.35 0.064], ...
	'String','Compute WT', ...
	'Tag','Pushbutton_cwt_compute');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_adv_track_compute(''radiobutton_time'')', ...
	'FontSize',0.533333333333332, ...
	'Position',[0.525 0.31 0.44 0.04], ...
	'String','Single Time Exponent', ...
	'Style','Checkbox', ...
	'Tag','Radiobutton_adv_track_time', ...
	'Value',1);
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_adv_track_compute(''radiobutton_reg'')', ...
	'FontSize',0.533333333333332, ...
	'Position',[0.525 0.265 0.44 0.04], ...
	'String','Specify Regression Range', ...
	'Style','Checkbox', ...
	'Tag','Radiobutton_adv_track_reg', ...
	'Value',1);
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.533333333333332, ...
	'ListboxTop',0, ...
	'Min',1, ...
	'Position',[0.524 0.222 0.441 0.04], ...
	'String',{'Least Square', 'Weighted Least Square', 'Penalized Least Square', 'Lepskii Adaptive Procedure', 'Maximum Likelihood', 'Lim inf', 'Lim sup'}, ...
	'Style','popupmenu', ...
	'Tag','Radiobutton_adv_track_monolr', ...
	'Value',1);    
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.296295999999999, ...
	'Position',[0.025 0.898052 0.95 0.0884558], ...
	'Style','frame', ...
	'Tag','Frame1');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.551723999999999, ...
	'FontWeight','bold', ...
	'Position',[0.143119 0.92 0.72844 0.038], ...
	'String','Holder Function or Pointwise Exponent', ...
	'Style','text', ...
	'Tag','StaticText6');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_adv_track_compute(''help'')', ...
	'FontSize',0.399999999999999, ...
	'FontWeight','bold', ...
	'Position',[0.4 0.092 0.175 0.06], ...
	'String','Help', ...
	'Tag','Pushbutton1');

fl_window_init(a);
fl_adv_track_compute('refresh');

set(findobj(a,'Tag','StaticText7'),'BackgroundColor',fl_getOption('BackGroundColor'));
set(findobj(a,'Tag','StaticText7'),'ForegroundColor',fl_getOption('AltFontColor'));
