function gui_fl_import()
% This is the machine-generated representation of a MATLAB object
% and its children.  Note that handle values may change when these
% objects are re-created. This may cause problems with some callbacks.
% The command syntax may be supported in the future, but is currently 
% incomplete and subject to change.
%
% To re-open this system, just type the name of the m-file at the MATLAB
% prompt. The M-file and its associtated MAT-file must be on your path.

% FracLab 2.05 Beta, Copyright © 1996 - 2009 by INRIA
% -- --
% For details on use and redistribution refer to $fraclab/licence.txt
%--------------------------------------------------------------------------

a = figure('Units','pixels', ...
        'MenuBar','none','IntegerHandle','off','NumberTitle','off', ...
	'HandleVisibility','callback', ...
	'Name','Import Data from Matlab Workspace', ...
	'Position',[20 50 400 500], ...
	'Tag','Fig_gui_fl_import');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.24, ...
	'ListboxTop',0, ...
	'Position',[0.02 0.89 0.96 0.10], ...
	'Style','frame', ...
	'Tag','Frame1');    
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.604651162790698, ...
	'FontWeight','bold', ...
	'HorizontalAlignment','center', ...
	'Position',[0.05 0.925 0.9 0.043], ...
	'String','Import Data from MATLAB Workspace', ...
	'Style','text', ...
	'Tag','StaticText');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.0307692307692308, ...
	'ListboxTop',0, ...
	'Position',[0.02 0.1 0.96 0.78], ...
	'Style','frame', ...
	'Tag','Frame2');  
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','fl_function(''lb_imp'');', ...
	'FontSize',0.0352581854081062, ...
	'Position',[0.06 0.123762 0.32 0.680693], ...
	'Style','listbox', ...
	'Tag','Listbox_imp_name', ...
	'Value',1);
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','fl_function(''lb_imp'');', ...
	'FontSize',0.0352581854081062, ...
	'Position',[0.39 0.123762 0.28 0.680693], ...
	'Style','listbox', ...
	'Tag','Listbox_imp_size', ...
	'Value',1);
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','fl_function(''lb_imp'');', ...
	'FontSize',0.0352581854081062, ...
	'Position',[0.68 0.123762 0.24 0.680693], ...
	'Style','listbox', ...
	'Tag','Listbox_imp_type', ...
	'Value',1);
b = uicontrol('Parent',a, ...
    	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.700266909425862, ...
	'HorizontalAlignment','center', ...
	'Position',[0.06 0.819926 0.32 0.0371287], ...
	'String','Name', ...
	'Style','text', ...
	'Tag','StaticText2');
b = uicontrol('Parent',a, ...
    	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.700266909425862, ...
	'HorizontalAlignment','center', ...
	'Position',[0.68 0.819926 0.24 0.0371287], ...
	'String','Type', ...
	'Style','text', ...
	'Tag','StaticText2');
b = uicontrol('Parent',a, ...
    	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.700266909425862, ...
	'HorizontalAlignment','center', ...
	'Position',[0.39 0.819926 0.28 0.0371287], ...
	'String','Size', ...
	'Style','text', ...
	'Tag','StaticText2');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_import;', ...
	'FontSize',0.342857142857143, ...
	'FontWeight','bold', ...
	'Position',[0.1 0.02 0.3 0.07], ...
	'String','Import', ...
	'Tag','Pushbutton_imp_import');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_function(''close'');', ...
	'FontSize',0.342857142857143, ...
	'FontWeight','bold', ...
	'Position',[0.6 0.02 0.3 0.07], ...
	'String','Close', ...
	'Tag','Pushbutton_imp_close');

fl_window_init(a);