function gui_fl_create_matrix()
% This is the machine-generated representation of a MATLAB object
% and its children.  Note that handle values may change when these
% objects are re-created. This may cause problems with some callbacks.
% The command syntax may be supported in the future, but is currently 
% incomplete and subject to change.
%
% To re-open this system, just type the name of the m-file at the MATLAB
% prompt. The M-file and its associtated MAT-file must be on your path.
           
% FracLab 2.05 Beta, Copyright © 1996 - 2009 by INRIA
% -- --
% For details on use and redistribution refer to $fraclab/licence.txt
%--------------------------------------------------------------------------

a = figure('Units','pixels', ...
	'HandleVisibility','callback', ...
	'MenuBar','none','IntegerHandle','off','NumberTitle','off', ...
	'Position',[20 80 300 140], ...
	'Name','Matrix Creation','Tag','Create matrix');
    
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.342857142857143, ...
	'ListboxTop',0, ...
	'Position',[0.02 0.74 0.96 0.25], ...
	'Style','frame', ...
	'Tag','Frame1');    
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.779220779220779, ...
	'FontWeight','bold', ...
	'HorizontalAlignment','center', ...
	'Position',[0.1 0.78 0.8 0.11], ...
	'String','Create Matrix Structure', ...
	'Style','text', ...
	'Tag','StaticText');
    
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.168067226890756, ...
	'ListboxTop',0, ...
	'Position',[0.02 0.22 0.96 0.51], ...
	'Style','frame', ...
	'Tag','Frame2');    

    % Name
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.714285714285714, ...
	'HorizontalAlignment','left', ...
	'Position',[0.05 0.5 0.18 0.12], ...
	'String','Name', ...
	'Style','text', ...
	'Tag','StaticText1');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',0.6, ...
	'Position',[0.27 0.5 0.49 0.12], ...
	'Style','edit', ...
	'Tag','Text_mat_name');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_create_structures(''get_matrix_name'');', ...
	'FontSize',0.6, ...
	'Position',[0.79 0.5 0.16 0.12], ...
	'String','Refresh', ...
	'Tag','Pushbutton1');

    
    % matrix
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.714285714285714, ...
	'HorizontalAlignment','left', ...
	'Position',[0.05 0.3 0.18 0.12], ...
	'String','Matrix', ...
	'Style','text', ...
	'Tag','StaticText1');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',0.6, ...
	'Position',[0.27 0.3 0.49 0.12], ...
	'Style','edit', ...
	'Tag','Text_matrix');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_create_structures(''get_matrix'');', ...
	'FontSize',0.6, ...
	'Position',[0.79 0.3 0.16 0.12], ...
	'String','Refresh', ...
	'Tag','Pushbutton1');
   
    % general
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_function(''close'');', ...
	'FontSize',0.499999999999999, ...
	'FontWeight','bold', ...
	'Position',[0.6 0.02 0.3 0.18], ...
	'String','Close', ...
	'Tag','Pushbutton_close');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','eval([''global '' fl_create_structures(''create_matrix'');]);', ...
	'FontSize',0.499999999999999, ...
	'FontWeight','bold', ...
	'Position',[0.1 0.02 0.3 0.18], ...
	'String','Create', ...
	'Tag','Pushbutton_Create');

fl_window_init(a);