function fig = gui_fl_getregparam()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.

% FracLab 2.05 Beta, Copyright © 1996 - 2009 by INRIA
% -- --
% For details on use and redistribution refer to $fraclab/licence.txt
%--------------------------------------------------------------------------

h0 = figure( ...
	'Colormap',[], ...
	'Position',[559 533 373 95], ...
	'MenuBar','none','IntegerHandle','off','NumberTitle','off', ...    
	'Tag','Fig1');
get(findobj('Tag','Fig1'),'Name');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.315789473684211, ...
	'ListboxTop',0, ...
	'Position',[0.1 0.5 0.8 0.4], ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','uiresume(gcf)', ...
	'FontSize',0.631578947368421, ...
	'ListboxTop',0, ...
	'Position',[0.1 0.2 0.8 0.2], ...
	'Style','edit', ...
	'Tag','EditText1');
	
fl_window_init(h0);	
	
if nargout > 0, fig = h0; end
