function gui_fl_create_graph()
% This is the machine-generated representation of a MATLAB object
% and its children.  Note that handle values may change when these
% objects are re-created. This may cause problems with some callbacks.
% The command syntax may be supported in the future, but is currently 
% incomplete and subject to change.
%
% To re-open this system, just type the name of the m-file at the MATLAB
% prompt. The M-file and its associtated MAT-file must be on your path.

% FracLab 2.05 Beta, Copyright © 1996 - 2009 by INRIA
% -- --
% For details on use and redistribution refer to $fraclab/licence.txt
%--------------------------------------------------------------------------

a = figure('MenuBar','none','IntegerHandle','off','NumberTitle','off', ...
	'HandleVisibility','callback', ...
	'Position',[20 50 300 250], ...
	'Name','Graph Creation','Tag','Create graph');

b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.32, ...
	'ListboxTop',0, ...
	'Position',[0.02 0.84 0.96 0.15], ...
	'Style','frame', ...
	'Tag','Frame1');    
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.842105263157895, ...
	'FontWeight','bold', ...
	'HorizontalAlignment','center', ...
	'Position',[0.1 0.88 0.8 0.057], ...
	'String','Create Graph Structure', ...
	'Style','text', ...
	'Tag','StaticText');
    
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.0695652173913043, ...
	'ListboxTop',0, ...
	'Position',[0.02 0.14 0.96 0.69], ...
	'Style','frame', ...
	'Tag','Frame2');    
    
    %  name
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.842105263157895, ...
	'HorizontalAlignment','left', ...
	'Position',[0.05 0.73 0.18 0.057], ...
	'String','Name', ...
	'Style','text', ...
	'Tag','StaticText1');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',0.574711999999998, ...
	'Position',[0.27 0.73 0.49 0.07], ...
	'Style','edit', ...
	'Tag','Text_graph_name');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_create_structures(''get_graph_name'');', ...
	'FontSize',0.6, ...
	'Position',[0.79 0.73 0.16 0.0666667], ...
	'String','Refresh', ...
	'Tag','Pushbutton1');


    % data 1
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.842105263157895, ...
	'HorizontalAlignment','left', ...
	'Position',[0.05 0.64 0.18 0.057], ...
	'String','Data 1', ...
	'Style','text', ...
	'Tag','StaticText1');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',0.6, ...
	'Position',[0.27 0.64 0.49 0.07], ...
	'Style','edit', ...
	'Tag','Text_graph_data1');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_create_structures(''get_graph_data1'');', ...
	'FontSize',0.6, ...
	'Position',[0.79 0.64 0.16 0.07], ...
	'String','Refresh', ...
	'Tag','Pushbutton1');
    
    % data 2
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.842105263157895, ...
	'HorizontalAlignment','left', ...
	'Position',[0.05 0.55 0.18 0.057], ...
	'String','Data 2', ...
	'Style','text', ...
	'Tag','StaticText1');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_create_structures(''get_graph_data2'');', ...
	'FontSize',0.6, ...
	'Position',[0.79 0.55 0.16 0.07], ...
	'String','Refresh', ...
	'Tag','Pushbutton1');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',0.6, ...
	'Position',[0.27 0.55 0.49 0.07], ...
	'Style','edit', ...
	'Tag','Text_graph_data2');
    
    % title
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.842105263157895, ...
	'HorizontalAlignment','left', ...
	'Position',[0.05 0.46 0.18 0.057], ...
	'String','Title', ...
	'Style','text', ...
	'Tag','StaticText1');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',0.6, ...
	'Position',[0.27 0.46 0.49 0.07], ...
	'Style','edit', ...
	'Tag','Text_graph_title');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_create_structures(''get_graph_title'');', ...
	'FontSize',0.6, ...
	'Position',[0.79 0.46 0.16 0.07], ...
	'String','Refresh', ...
	'Tag','Pushbutton1');

    
    % X label
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.842105263157895, ...
	'HorizontalAlignment','left', ...
	'Position',[0.05 0.37 0.18 0.057], ...
	'String','X label', ...
	'Style','text', ...
	'Tag','StaticText1');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',0.6, ...
	'Position',[0.27 0.37 0.49 0.07], ...
	'Style','edit', ...
	'Tag','Text_graph_xlabel');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_create_structures(''get_graph_xlabel'');', ...
	'FontSize',0.6, ...
	'Position',[0.79 0.37 0.16 0.07], ...
	'String','Refresh', ...
	'Tag','Pushbutton1');

    % y label
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.842105263157895, ...
	'HorizontalAlignment','left', ...
	'Position',[0.05 0.28 0.18 0.057], ...
	'String','Y label', ...
	'Style','text', ...
	'Tag','StaticText1');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',0.6, ...
	'Position',[0.27 0.28 0.49 0.07], ...
	'Style','edit', ...
	'Tag','Text_graph_ylabel');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_create_structures(''get_graph_ylabel'');', ...
	'FontSize',0.6, ...
	'Position',[0.79 0.28 0.16 0.07], ...
	'String','Refresh', ...
	'Tag','Pushbutton1');
    
    % general
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_create_structures(''get_graph_all'');', ...
	'FontSize',0.5, ...
	'Position',[0.38 0.16 0.24 0.09], ...
	'String','Refresh all', ...
	'Tag','Pushbutton2');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_function(''close'');', ...
	'FontSize',0.499999999999999, ...
	'FontWeight','bold', ...
	'Position',[0.6 0.02 0.3 0.1], ...
	'String','Close', ...
	'Tag','Pushbutton_close');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','eval([''global '' fl_create_structures(''create_graph'');]);', ...
	'FontSize',0.499999999999999, ...
	'FontWeight','bold', ...
	'Position',[0.1 0.02 0.3 0.1], ...
	'String','Create', ...
	'Tag','Pushbutton_Create');

fl_window_init(a);
