function fig = gui_view_toolbar()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.

% Modified by Christian Choque Cortez, October 2009

% FracLab 2.05 Beta, Copyright © 1996 - 2009 by INRIA
% -- --
% For details on use and redistribution refer to $fraclab/licence.txt
%--------------------------------------------------------------------------

a = figure('Name','View Toolbar','Tag','gui_view_toolbar', ...
    'HandleVisibility','callback','MenuBar','none','IntegerHandle','off','NumberTitle','off', ...
    'Position',[20 50 200 650],'UserData',0);

uicontrol('Parent',a,'Style','frame','Tag','Frame1', ...
	'Units','normalized','Position',[0.05 0.8295 0.9 0.161], ...
	'FontUnits','pixels','FontSize',12);

uicontrol('Parent',a,'Style','text','Tag','StaticText_figure', ...
	'Units','normalized','Position',[0.1 0.941 0.8 0.04], ...
	'FontUnits','pixels','FontSize',12,'FontWeight','bold', ...
	'String','Figure');

uicontrol('Parent',a,'Tag','button_view_in_new', ...
	'Units','normalized','Position',[0.1 0.91 0.8 0.03], ...
	'String','view in new', ...
	'CallBack','fl_view_toolbar(''View_in_new'');');

uicontrol('Parent',a,'Tag','button_view', ...
	'Units','normalized','Position',[0.1 0.875 0.8 0.03], ...
	'String','view','Enable','off', ...
	'CallBack','fl_view_toolbar(''View'');');

uicontrol('Parent',a,'Tag','button_Help', ...
	'Units','normalized','Position',[0.1 0.84 0.8 0.03], ...
	'String','help', ...
	'Callback','helpwin help_view;');

%%%%%%%%%%%%%%%%%%%% MODE FRAME %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
uicontrol('Parent',a,'Style','frame','Tag','Frame2', ...
	'Units','normalized','Position',[0.05 0.655+0.034 0.9 0.13], ...
	'FontUnits','pixels','FontSize',12);

uicontrol('Parent',a,'Style','text','Tag','StaticText_mode', ...
	'Units','normalized','Position',[0.1 0.731+0.034 0.8 0.04], ...
	'FontUnits','pixels','FontSize',12,'FontWeight','bold', ...
	'String','Image mode');

uicontrol('Parent',a,'Tag','button_Image_Matrix', ...
	'Units','normalized','Position',[0.1 0.7+0.034 0.8 0.03], ...
	'String','image control','Enable','off', ...
	'CallBack','fl_view_toolbar(''image'')');

uicontrol('Parent',a,'Style','checkbox','Tag','Checkbox_superpose', ...
	'Units','normalized','Position',[0.1 0.665+0.034 0.8 0.03], ...
	'String','superpose','Enable','off', ...
	'CallBack','fl_view_toolbar(''superpose_image'');');

%%%%%%%%%%%%%%%%%% TOOLBAR FRAME %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
uicontrol('Parent',a,'Style','frame','Tag','Frame3', ...
	'Units','normalized','Position',[0.05 0.305 0.9 0.34+0.034], ...
	'FontUnits','pixels','FontSize',12);

uicontrol('Parent',a,'Style','text','Tag','StaticText_tools', ...
	'Units','normalized','Position',[0.1 0.591+0.034 0.8 0.04], ...
	'FontUnits','pixels','FontSize',12,'FontWeight','bold', ...	
	'String','Tools');

uicontrol('Parent',a,'Style','checkbox','Tag','Checkbox_hold', ...
	'Units','normalized','Position',[0.1 0.56+0.034 0.8 0.03], ...
	'String','hold','Enable','off', ...
	'CallBack','fl_view_toolbar (''hold'');');

uicontrol('Parent',a,'Style','checkbox','Tag','Checkbox_rotate', ...
	'Units','normalized','Position',[0.1 0.525+0.034 0.8 0.03], ...
	'String','rotate','Enable','off', ...
	'CallBack','fl_view_toolbar (''rotate'');');

uicontrol('Parent',a,'Style','checkbox','Tag','Checkbox_zoom', ...
	'Units','normalized','Position',[0.1 0.49+0.034 0.8 0.03], ...
	'String','zoom','Enable','off', ...
	'CallBack','fl_view_toolbar(''zoom'');');

uicontrol('Parent',a,'Style','text','Tag','StaticText_Vsplit', ...
	'Units','normalized','Position',[0.1 0.45+0.034 0.5 0.03], ...
	'FontUnits','pixels','FontSize',12, ...
	'String','Vsplit','Enable','off');

uicontrol('Parent',a,'Style','edit','Tag','EditText_Vsplit', ...
	'Units','normalized','Position',[0.55 0.455+0.034 0.25 0.03],'BackgroundColor',[1 1 1], ...
	'FontUnits','pixels','FontSize',12, ...
	'String','1','Enable','off', ...
	'Callback','fl_view_toolbar (''divide'');');

uicontrol('Parent',a,'Style','text','Tag','StaticText_Hsplit', ...
	'Units','normalized','Position',[0.1 0.415+0.034 0.5 0.03], ...
	'FontUnits','pixels','FontSize',12, ...
	'String','Hsplit','Enable','off');

uicontrol('Parent',a,'Style','edit','Tag','EditText_Hsplit', ...
	'Units','normalized','Position',[0.55 0.42+0.034 0.25 0.03],'BackgroundColor',[1 1 1], ...
	'FontUnits','pixels','FontSize',12, ...
	'Callback','fl_view_toolbar (''divide'');', ...	
	'String','1','Enable','off');

uicontrol('Parent',a,'Tag','button_Axes', ...
	'Units','normalized','Position',[0.1 0.385+0.034 0.8 0.03], ...
	'String','axes control','Enable','off', ...
	'Callback','fl_view_toolbar(''axes'');');

uicontrol('Parent',a,'Tag','button_print', ...
	'Units','normalized','Position',[0.1 0.35+0.034 0.8 0.03], ...
	'String','print','Enable','off', ...
	'Callback','fl_view_toolbar(''Print'');');

uicontrol('Parent',a,'Tag','button_close_figure', ...
	'Units','normalized','Position',[0.1 0.315+0.034 0.8 0.03], ...
	'String','close figure','Enable','off', ...
	'Callback','fl_view_toolbar(''Close_figure'');');

uicontrol('Parent',a,'Tag','button_Close', ...
	'Units','normalized','Position',[0.1 0.280+0.034 0.8 0.03], ...
	'String','close all', ...
	'Callback','fl_view_toolbar(''Close_all'');');

%%%%%%%%%%%%%%%%%%%%%%%% LIST BOX %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
uicontrol('Parent',a,'Style','listbox','Tag','Listbox_figures', ...
	'Units','normalized','Position',[0.075 0.01 0.85 0.29],'BackgroundColor',[1 1 1], ...
	'FontUnits','pixels','FontSize',12, ...
    'String',' ', ...
	'CallBack','fl_view_toolbar(''click_listbox'');');
	
fl_window_init(a);	
    
if nargout > 0, fig = a; end
