function gui_oper_matrix()
% This is the machine-generated representation of a MATLAB object
% and its children.  Note that handle values may change when these
% objects are re-created. This may cause problems with some callbacks.
% The command syntax may be supported in the future, but is currently 
% incomplete and subject to change.
%
% To re-open this system, just type the name of the m-file at the MATLAB
% prompt. The M-file and its associtated MAT-file must be on your path.

% FracLab 2.05 Beta, Copyright © 1996 - 2009 by INRIA
% -- --
% For details on use and redistribution refer to $fraclab/licence.txt
%--------------------------------------------------------------------------

a = figure('Units','pixels', ...
	'HandleVisibility','callback', ...
	'MenuBar','none','IntegerHandle','off','NumberTitle','off', ...
	'Position',[20 80 300 300], ...
	'Name','Matrix Operations','Tag','Fig_gui_oper_matrix');
    
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.285714285714286, ...
	'ListboxTop',0, ...
	'Position',[0.02 0.84 0.96 0.14], ...
	'Style','frame', ...
	'Tag','Frame1');    
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.727272727272727, ...
	'FontWeight','bold', ...
	'HorizontalAlignment','center', ...
	'Position',[0.1 0.87 0.8 0.055], ...
	'String','Matrix Operations', ...
	'Style','text', ...
	'Tag','StaticText_title');
    
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.0579710144927536, ...
	'ListboxTop',0, ...
	'Position',[0.02 0.14 0.96 0.69], ...
	'Style','frame', ...
	'Tag','Frame2');    
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.727272727272727, ...
	'FontWeight','bold', ...
	'HorizontalAlignment','center', ...
	'Position',[0.1 0.755 0.8 0.055], ...
	'String','Parameters', ...
	'Style','text', ...
	'Tag','StaticText_param');

    % Input 1
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.666666666666667, ...
	'HorizontalAlignment','left', ...
	'Position',[0.05 0.65 0.18 0.06], ...
	'String','Input 1', ...
	'Style','text', ...
	'Tag','StaticText_input1');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'Callback','fl_create_structures(''text_input1'');', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',0.666666666666667, ...
	'Position',[0.27 0.66 0.49 0.06], ...
	'Style','edit', ...
	'Tag','Text_input1');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_create_structures(''get_input1'');', ...
	'FontSize',0.6, ...
	'Position',[0.79 0.66 0.16 0.06], ...
	'String','Refresh', ...
	'Tag','Pushbutton_get1');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.666666666666667, ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[0.1    0.56    0.19    0.06], ...
	'String','scale', ...
	'Style','text', ...
	'Tag','StaticText_scale1');

    % 'Callback','fl_create_structures(''edit_scale1'');', ...
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','fl_create_structures(''edit_isnum'');', ...
	'FontSize',0.666666666666667, ...
	'ListboxTop',0, ...
	'String','1', ...
	'Position',[0.3    0.57    0.16    0.06], ...
	'Style','edit', ...
	'Tag','scale1');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.666666666666667, ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[0.5    0.56    0.19    0.06], ...
	'String','offset', ...
	'Style','text', ...
	'Tag','StaticText_offset1');

    % 'Callback','fl_create_structures(''edit_offset1'');', ...
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','fl_create_structures(''edit_isnum'');', ...
	'FontSize',0.666666666666667, ...
	'ListboxTop',0, ...
	'String','0', ...
	'Position',[0.7    0.57    0.16    0.06], ...
	'Style','edit', ...
	'Tag','offset1');    
    % input 2
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.666666666666667, ...
	'HorizontalAlignment','left', ...
	'Position',[0.05 0.47 0.18 0.06], ...
	'String','Input 2', ...
	'Style','text', ...
	'Enable','off', ...
	'Tag','StaticText_input2');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',0.666666666666667, ...
	'Position',[0.27 0.48 0.49 0.06], ...
	'Style','edit', ...
	'Enable','off', ...
	'Callback','fl_create_structures(''text_input2'');', ...
	'Tag','Text_input2');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_create_structures(''get_input2'');', ...
	'FontSize',0.6, ...
	'Position',[0.79 0.48 0.16 0.06], ...
	'Enable','off', ...
	'String','Refresh', ...
	'Tag','Pushbutton_get2');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.666666666666667, ...
	'Enable','off', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[0.1    0.38    0.19    0.06], ...
	'String','scale', ...
	'Style','text', ...
	'Tag','StaticText_scale2');
    
    % 'Callback','fl_create_structures(''edit_scale2'');', ...
b = uicontrol('Parent',a, ...
    	'Enable','off', ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','fl_create_structures(''edit_isnum'');', ...
	'FontSize',0.666666666666667, ...
	'ListboxTop',0, ...
	'String','1', ...
	'Position',[0.3    0.39    0.16    0.06], ...
	'Style','edit', ...
	'Tag','scale2');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.666666666666667, ...
	'Enable','off', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[0.5    0.38    0.19    0.06], ...
	'String','offset', ...
	'Style','text', ...
	'Tag','StaticText_offset2');
    
    % 'Callback','fl_create_structures(''edit_offset2'');', ...
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Enable','off', ...
	'Callback','fl_create_structures(''edit_isnum'');', ...
	'FontSize',0.666666666666667, ...
	'Enable','off', ...
	'ListboxTop',0, ...
	'String','0', ...
	'Position',[0.7    0.39    0.16    0.06], ...
	'Style','edit', ...
	'Tag','offset2');
    
    % output
b = uicontrol('Parent',a, ...
    	'Enable','off', ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.666666666666667, ...
	'HorizontalAlignment','left', ...
	'Position',[0.05 0.28 0.18 0.06], ...
	'String','Output', ...
	'Style','text', ...
	'Tag','StaticText_output');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_create_structures(''text_output'');', ...
	'Enable','off', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',0.666666666666667, ...
	'Position',[0.27 0.29 0.49 0.06], ...
	'Style','edit', ...
	'Tag','Text_output');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_create_structures(''get_output'');', ...
	'FontSize',0.6, ...
	'Enable','off', ...
	'Position',[0.79 0.29 0.16 0.06], ...
	'String','Refresh', ...
	'Tag','Pushbutton_output');

    


b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.666666666666667, ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[0.25    0.17    0.2    0.06], ...
	'String','operation', ...
	'Enable','off', ...
	'Style','text', ...
	'Tag','StaticText_oper');

b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.571428571428571, ...
	'ListboxTop',0, ...
	'Enable','off', ...
	'Max',4, ...
	'Min',1, ...
	'Position',[0.5 0.18 0.25 0.07], ...
	'String',{'add','sub','mul', 'div'}, ...
	'Style','popupmenu', ...
	'Tag','PopupMenu_oper', ...
	'Value',1);

    % general
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','eval([''global '' fl_create_structures(''oper_matrix'');]);', ...
	'FontSize',0.363636363636364, ...
	'Enable','off', ...
	'FontWeight','bold', ...
	'Position',[0.1 0.02 0.3 0.11], ...
	'String','Apply', ...
	'Tag','Pushbutton_Apply');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_function(''close'');', ...
	'FontSize',0.363636363636364, ...
	'FontWeight','bold', ...
	'Position',[0.6 0.02 0.3 0.11], ...
	'String','Close', ...
	'Tag','Pushbutton_close');

fl_window_init(a);