function gui_signal2measure()
% This is the machine-generated representation of a MATLAB object
% and its children.  Note that handle values may change when these
% objects are re-created. This may cause problems with some callbacks.
% The command syntax may be supported in the future, but is currently 
% incomplete and subject to change.
%
% To re-open this system, just type the name of the m-file at the MATLAB
% prompt. The M-file and its associtated MAT-file must be on your path.

% FracLab 2.05 Beta, Copyright © 1996 - 2009 by INRIA
% -- --
% For details on use and redistribution refer to $fraclab/licence.txt
%--------------------------------------------------------------------------

a = figure('Units','pixels', ...
	'MenuBar','none','IntegerHandle','off','NumberTitle','off', ...
	'Position',[20 80 300 200], ...
	'HandleVisibility','callback', ...
	'Name','Signal2measure','Tag','Fig_gui_signal2measure');
    
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.342857142857143, ...
	'ListboxTop',0, ...
	'Position',[0.02 0.78 0.96 0.2], ...
	'Style','frame', ...
	'Tag','Frame1');    
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.872727272727273, ...
	'FontWeight','bold', ...
	'HorizontalAlignment','center', ...
	'Position',[0.1 0.87 0.8 0.07], ...
	'String','Turn signal into measure', ...
	'Style','text', ...
	'Tag','StaticText1');
    
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.0695652173913043, ...
	'ListboxTop',0, ...
	'Position',[0.02 0.2 0.96 0.55], ...
	'Style','frame', ...
	'Tag','Frame2');    
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.872727272727273, ...
	'FontWeight','bold', ...
	'HorizontalAlignment','center', ...
	'Position',[0.1 0.65 0.8 0.07], ...
	'String','Signal', ...
	'Style','text', ...
	'Tag','StaticText1');

    % Input
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.7, ...
	'HorizontalAlignment','left', ...
	'Position',[0.05 0.47 0.18 0.09], ...
	'String','Input', ...
	'Style','text', ...
	'Tag','StaticText1');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',0.6, ...
	'Position',[0.27 0.48 0.49 0.09], ...
	'Style','edit', ...
	'Tag','Text_input');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_signal2measure_compute(''get_input_name'');', ...
	'FontSize',0.6, ...
	'Position',[0.79 0.48 0.16 0.09], ...
	'String','Refresh', ...
	'Tag','Pushbutton1');

    
    % output
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.7, ...
	'HorizontalAlignment','left', ...
	'Position',[0.05 0.33 0.18 0.09], ...
	'String','Output', ...
	'Style','text', ...
	'Tag','StaticText1');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',0.6, ...
	'Position',[0.27 0.34 0.49 0.09], ...
	'Style','edit', ...
	'Tag','Text_output');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_signal2measure_compute(''get_output_name'');', ...
	'FontSize',0.6, ...
	'Position',[0.79 0.34 0.16 0.09], ...
	'String','Refresh', ...
	'Tag','Pushbutton1');


   
    % general
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','eval([''global '' fl_signal2measure_compute(''compute_signal2measure'');]);', ...
	'FontSize',0.436363636363636, ...
	'FontWeight','bold', ...
	'Position',[0.1 0.02 0.3 0.14], ...
	'String','Compute', ...
	'Tag','Pushbutton_Create');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_function(''close'');', ...
	'FontSize',0.436363636363636, ...
	'FontWeight','bold', ...
	'Position',[0.6 0.02 0.3 0.14], ...
	'String','Close', ...
	'Tag','Pushbutton_close');

fl_window_init(a);