function gui_fl_lacunarity()
% This is the machine-generated representation of a MATLAB object
% and its children.  Note that handle values may change when these
% objects are re-created. This may cause problems with some callbacks.
% The command syntax may be supported in the future, but is currently 
% incomplete and subject to change.
%
% To re-open this system, just type the name of the m-file at the MATLAB
% prompt. The M-file and its associtated MAT-file must be on your path. 

% Modified by Christian Choque Cortez, February 2009

% FracLab 2.05 Beta, Copyright © 1996 - 2009 by INRIA
% -- --
% For details on use and redistribution refer to $fraclab/licence.txt
%--------------------------------------------------------------------------

a = figure( 'Name','Lacunarity','Tag','Fig_gui_fl_lacunarity',...
	'MenuBar','none','IntegerHandle','off','NumberTitle','off', ...
	'Position',[20 50 320 290]);

[SigIn_name] = fl_get_input('matrix'); eval(['global ' SigIn_name]);
SigIn = eval(SigIn_name); 
if isempty(SigIn), N = 1; else N = min(size(SigIn));end

%%%%%%%%%%%%%%%%%%% CREATE FRAME %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
uicontrol('Parent',a,'Style','frame','Tag','Frame_title', ...
	'Units','normalized','Position',[0.04 0.85 0.92 0.11]);

uicontrol('Parent',a,'Style','frame','Tag','Frame_input', ...
	'Units','normalized','Position',[0.04 0.68 0.92 0.13]);

uicontrol('Parent',a,'Style','frame','Tag','Frame_parameters', ...
	'Units','normalized','Position',[0.04 0.24 0.92 0.4]);

%%%%%%%%%%%%%%%%%%% TITLE FRAME %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
uicontrol('Parent',a,'Style','text','Tag','StaticText_title', ...
	'Units','normalized','Position',[0.21 0.86 0.56 0.076], ...
	'FontUnits','normalized','FontWeight','bold','FontSize',0.6, ...
	'String','Lacunarity');

%%%%%%%%%%%%%%%%%%% INPUT SIGNAL %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
uicontrol('Parent',a,'Style','text','Tag','StaticText_input', ...
	'Units','normalized','Position',[0.06 0.69 0.25 0.07], ...
	'FontUnits','normalized','FontWeight','bold','FontSize',0.6, ...
	'String','Input signal');

uicontrol('Parent',a,'Style','edit','Tag','EditText_input', ...
	'Units','normalized','Position',[0.34 0.705 0.38 0.075], ...
	'FontUnits','normalized','FontSize',0.6, ...
	'String','', ...
	'Enable','inactive');

uicontrol('Parent',a,'Tag','Button_refresh', ...
	'Units','normalized','Position',[0.76 0.70 0.175 0.09], ...
	'FontUnits','normalized','FontWeight','bold','FontSize',0.4, ...
	'String','Refresh', ...
    'Callback','fl_lacunarity_compute(''refresh'')');

%%%%%%%%%%%%%%%%%%%% GLOBAL PARAMETERS %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
uicontrol('Parent',a,'Style','text','Tag','StaticText_min', ...
	'Units','normalized','Position',[0.05 0.5 0.1 0.07], ...
	'FontUnits','normalized','FontSize',0.6, ...
	'String','min');

uicontrol('Parent',a,'Style','edit','Tag','EditText_min', ...
	'Units','normalized','Position',[0.15 0.52 0.16 0.08], ...
	'FontUnits','normalized','FontSize',0.6, ...
	'String','1', ...
	'Callback','fl_lacunarity_compute(''edit_min'');');

uicontrol('Parent',a,'Style','text','Tag','StaticText_max', ...
	'Units','normalized','Position',[0.35 0.5 0.1 0.07], ...
	'FontUnits','normalized','FontSize',0.6, ...
	'String','max');

uicontrol('Parent',a,'Style','edit','Tag','EditText_max', ...
	'Units','normalized','Position',[0.46 0.52 0.16 0.08], ...
	'FontUnits','normalized','FontSize',0.6, ...
	'String',N, ...
    'Callback','fl_lacunarity_compute(''edit_max'')');

uicontrol('Parent',a,'Style','text','Tag','StaticText_step', ...
	'Units','normalized','Position',[0.66 0.5 0.1 0.07], ...
	'FontUnits','normalized','FontSize',0.6, ...
	'String','step');

uicontrol('Parent',a,'Style','edit','Tag','EditText_step', ...
	'Units','normalized','Position',[0.78 0.52 0.16 0.08], ...
	'FontUnits','normalized','FontSize',0.6, ...
	'String','1', ...
    'Callback','fl_lacunarity_compute(''edit_step'')');

%%%%%%%%%%%%%%%%%%%%%%%% MASK PARAMETERS %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
uicontrol('Parent',a,'Style','Checkbox','Tag','Check_mask', ...
    'Units','normalized','Position',[0.07 0.35 0.16 0.065], ...
    'FontUnits','normalized','FontSize',0.6, ... 
    'String','Mask', ...
    'Value',0, ...
    'Callback','fl_lacunarity_compute(''check_mask'')');

uicontrol('Parent',a,'Style','edit','Tag','EditText_mask', ...
    'Units','normalized','Position',[0.23 0.35 0.32 0.068], ...
    'FontUnits','normalized','FontSize',0.6, ...
    'String','', ...
    'Enable','inactive','Enable','off');

uicontrol('Parent',a,'Tag','Button_refresh_mask',...
	'Units','normalized','Position',[0.57 0.35 0.18 0.09], ...
	'FontUnits','normalized','FontWeight','bold','FontSize',0.4, ...
	'String','Refresh', ...
    'Enable','off', ...
	'Callback','fl_lacunarity_compute(''refresh_mask'')');

uicontrol('Parent',a,'Tag','Button_new_mask', ...
	'Units','normalized','Position',[0.785 0.35 0.15 0.09], ...
	'FontUnits','normalized','FontWeight','bold','FontSize',0.4, ...
	'String','New', ...
    'Enable','off', ...
	'Callback','eval([''global '' fl_lacunarity_compute(''new_mask'',who)])');

%%%%%%%%%%%%%%%%%%%% COMPUTE/HELP/CLOSE %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
uicontrol('Parent',a,'Tag','Button_compute', ...
    'Units','normalized','Position',[0.046 0.09 0.23 0.11], ...
    'FontUnits','normalized','FontWeight','bold','FontSize',0.4, ...
    'String','Compute', ...
    'Callback','eval([''global '' fl_lacunarity_compute(''compute'',who)])');

uicontrol('Parent',a,'Tag','Button_help', ...
    'Units','normalized','Position',[0.4 0.09 0.23 0.11], ...
    'FontUnits','normalized','FontWeight','bold','FontSize',0.4, ...
    'String','Help', ...
    'Callback','fl_lacunarity_compute(''help'')');

uicontrol('Parent',a,'Tag','Button_close', ...
    'Units','normalized','Position',[0.73 0.09 0.23 0.11], ...
    'FontUnits','normalized','FontWeight','bold','FontSize',0.4, ... 
    'String','Close', ...
    'Callback','fl_lacunarity_compute(''close'')');
	
fl_window_init(a);	

fl_lacunarity_compute('refresh');
