function gui_fl_create_dwt()
% This is the machine-generated representation of a MATLAB object
% and its children.  Note that handle values may change when these
% objects are re-created. This may cause problems with some callbacks.
% The command syntax may be supported in the future, but is currently 
% incomplete and subject to change.
%
% To re-open this system, just type the name of the m-file at the MATLAB
% prompt. The M-file and its associtated MAT-file must be on your path.
             
% FracLab 2.05 Beta, Copyright © 1996 - 2009 by INRIA
% -- --
% For details on use and redistribution refer to $fraclab/licence.txt
%--------------------------------------------------------------------------

a = figure('MenuBar','none','IntegerHandle','off','NumberTitle','off', ...
	'HandleVisibility','callback', ...
	'Position',[20 50 300 250], ...
	'Name','DWT Creation','Tag','Create dwt');

b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.32, ...
	'ListboxTop',0, ...
	'Position',[0.02 0.84 0.96 0.15], ...
	'Style','frame', ...
	'Tag','Frame1');    
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.842105263157895, ...
	'FontWeight','bold', ...
	'HorizontalAlignment','center', ...
	'Position',[0.1 0.88 0.8 0.057], ...
	'String','Create DWT Structure', ...
	'Style','text', ...
	'Tag','StaticText');
    
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.0761904761904762, ...
	'ListboxTop',0, ...
	'Position',[0.02 0.2 0.96 0.63], ...
	'Style','frame', ...
	'Tag','Frame2');    
    
    %  name
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.842105263157895, ...
	'HorizontalAlignment','left', ...
	'Position',[0.05 0.73 0.18 0.057], ...
	'String','Name', ...
	'Style','text', ...
	'Tag','StaticText1');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',0.6, ...
	'Position',[0.27 0.73 0.49 0.07], ...
	'Style','edit', ...
	'Tag','Text_name');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_create_structures(''get_dwt_name'');', ...
	'FontSize',0.5, ...
	'Position',[0.79 0.73 0.16 0.07], ...
	'String','Refresh', ...
	'Tag','Pushbutton1');


    % wt
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.842105263157895, ...
	'HorizontalAlignment','left', ...
	'Position',[0.05 0.61 0.18 0.057], ...
	'String','wt', ...
	'Style','text', ...
	'Tag','StaticText1');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',0.6, ...
	'Position',[0.27 0.61 0.49 0.07], ...
	'Style','edit', ...
	'Tag','Text_wt');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_create_structures(''get_dwt_wt'');', ...
	'FontSize',0.5, ...
	'Position',[0.79 0.61 0.16 0.07], ...
	'String','Refresh', ...
	'Tag','Pushbutton1');
    
    % index
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.842105263157895, ...
	'HorizontalAlignment','left', ...
	'Position',[0.05 0.49 0.18 0.057], ...
	'String','Index', ...
	'Style','text', ...
	'Tag','StaticText1');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_create_structures(''get_dwt_index'');', ...
	'FontSize',0.5, ...
	'Position',[0.79 0.49 0.16 0.07], ...
	'String','Refresh', ...
	'Tag','Pushbutton1');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',0.6, ...
	'Position',[0.27 0.49 0.49 0.07], ...
	'Style','edit', ...
	'Tag','Text_index');
    
    % length
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.842105263157895, ...
	'HorizontalAlignment','left', ...
	'Position',[0.05 0.37 0.18 0.057], ...
	'String','Length', ...
	'Style','text', ...
	'Tag','StaticText1');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',0.6, ...
	'Position',[0.27 0.37 0.49 0.07], ...
	'Style','edit', ...
	'Tag','Text_length');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_create_structures(''get_dwt_length'');', ...
	'FontSize',0.5, ...
	'Position',[0.79 0.37 0.16 0.07], ...
	'String','Refresh', ...
	'Tag','Pushbutton1');
    
    % general
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_create_structures(''get_all_dwt'');', ...
	'FontSize',0.450450666666666, ...
	'Position',[0.38 0.24 0.24 0.1], ...
	'String','Refresh all', ...
	'Tag','Pushbutton2');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_function(''close'');', ...
	'FontSize',0.499999999999999, ...
	'FontWeight','bold', ...
	'Position',[0.6 0.05 0.3 0.1], ...
	'String','Close', ...
	'Tag','Pushbutton_close');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','eval([''global '' fl_create_structures(''create_dwt'');]);', ...
	'FontSize',0.499999999999999, ...
	'FontWeight','bold', ...
	'Position',[0.1 0.05 0.3 0.1], ...
	'String','Create', ...
	'Tag','Pushbutton_Create');

fl_window_init(a);