function fig = gui_fl_wsamod()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.

% Modified by Christian Choque Cortez, April 2010

% FracLab 2.05 Beta, Copyright © 1996 - 2009 by INRIA
% -- --
% For details on use and redistribution refer to $fraclab/licence.txt
%--------------------------------------------------------------------------

a = figure('Name','WSA Segmentation','Tag','Fig_gui_fl_wsamod', ...
    'MenuBar','none','IntegerHandle','off','NumberTitle','off', ...
    'Position',[20 50 350 270]);

%%%%%%%%%%%%%%%%%%% CREATE FRAME %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
uicontrol('Parent',a,'Style','frame','Tag','Frame_title', ...
    'Units','normalized','Position',[0.03 0.875 0.94 0.1]);

uicontrol('Parent',a,'Style','frame','Tag','Frame_input', ...
    'Units','normalized','Position',[0.03 0.71 0.94 0.14]);

uicontrol('Parent',a,'Style','frame','Tag','Frame_parameters', ...
    'Units','normalized','Position',[0.03 0.31 0.94 0.38]);

%%%%%%%%%%%%%%%%%%% TITLE FRAME %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
uicontrol('Parent',a,'Style','text','Tag','StaticText_title', ...
    'Units','normalized','Position',[0.04 0.88 0.92 0.08], ...
    'FontUnits','normalized','FontWeight','bold','FontSize',0.6, ...
    'String','Modeling and Segmentation using WSA Functions');

%%%%%%%%%%%%%%%%%%% INPUT SIGNAL %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
uicontrol('Parent',a,'Style','text','Tag','StaticText_input', ...
    'Units','normalized','Position',[0.06 0.73 0.2 0.07], ...
    'FontUnits','normalized','FontWeight','bold','FontSize',0.6, ...
    'String','Input Signal','HorizontalAlignment','left');

uicontrol('Parent',a,'Style','edit','Tag','EditText_input', ...
    'Units','normalized','Position',[0.3 0.74 0.4 0.07], ...
    'FontUnits','normalized','FontSize',0.6, ...
    'String','','Enable','inactive');

uicontrol('Parent',a,'Tag','Button_refresh', ...
    'Units','normalized','Position',[0.74 0.72 0.2 0.11], ...
    'FontUnits','normalized','FontWeight','bold','FontSize',0.4, ...
    'String','Refresh', ...
    'Callback','fl_wsamod_compute(''refresh'');');

%%%%%%%%%%%%%%%%%%%% GLOBAL PARAMETERS %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
uicontrol('Parent',a,'Style','text','Tag','StaticText_wavelet', ...
    'Units','normalized','Position',[0.06 0.56 0.15 0.07], ...
    'FontUnits','normalized','FontSize',0.6, ...
    'String','Wavelet','HorizontalAlignment','left');

uicontrol('Parent',a,'Style','popupmenu','Tag','PopupMenu_wavelet', ...
    'Units','normalized','Position',[0.3 0.585 0.4 0.07], ...
    'FontUnits','normalized','FontSize',0.6, ...
    'String',{'Haar','Daubechies 4','Daubechies 6','Daubechies 8', ...
    'Daubechies 10','Daubechies 12','Daubechies 14','Daubechies 16'}, ...
    'Value',1);

uicontrol('Parent',a,'Style','text','Tag','StaticText_scale', ...
    'Units','normalized', 'Position',[0.06 0.44 0.2 0.07], ...
    'FontUnits','normalized','FontSize',0.6, ...
    'String','Scale depth','HorizontalAlignment','left');

uicontrol('Parent',a,'Style','edit','Tag','EditText_scale', ...
    'Units','normalized','Position',[0.3 0.46 0.15 0.07], ...
    'FontUnits','normalized','FontSize',0.6, ...
    'String','', ...
    'Callback','fl_wsamod_compute( ''edit_scale'');');

uicontrol('Parent',a,'Style','text','Tag','StaticText_threshold', ...
    'Units','normalized','Position',[0.53 0.44 0.2 0.07], ...
    'FontUnits','normalized','FontSize',0.6, ...
    'String','Threshold','HorizontalAlignment','left');

uicontrol('Parent',a,'Style','edit','Tag','EditText_threshold', ...
    'Units','normalized','Position',[0.78 0.46 0.15 0.07], ...
    'FontUnits','normalized','FontSize',0.6, ...
    'String','10', ...
    'Callback','fl_wsamod_compute( ''edit_threshold'');');

uicontrol('Parent',a,'Style','text','Tag','StaticText_cmin', ...
    'Units','normalized','Position',[0.06 0.33 0.15 0.07], ...
    'FontUnits','normalized','FontSize',0.6, ...
    'String','C min','HorizontalAlignment','left');

uicontrol('Parent',a,'Style','edit','Tag','EditText_cmin', ...
    'Units','normalized','Position',[0.3 0.35 0.15 0.07], ...
    'FontUnits','normalized','FontSize',0.6, ...
    'String','0.1', ...
    'Callback','fl_wsamod_compute( ''edit_cmin'');');

uicontrol('Parent',a,'Style','text','Tag','StaticText_cmax', ...
    'Units','normalized','Position',[0.53 0.33 0.15 0.07], ...
    'FontUnits','normalized','FontSize',0.6, ...
    'String','C max','HorizontalAlignment','left');

uicontrol('Parent',a,'Style','edit','Tag','EditText_cmax', ...
    'Units','normalized','Position',[0.78 0.34 0.15 0.07], ...
    'FontUnits','normalized','FontSize',0.6, ...
    'String','1', ...
    'Callback','fl_wsamod_compute( ''edit_cmax'');');

%%%%%%%%%%%%%%%%%%%% COMPUTE/HELP/CLOSE %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
uicontrol('Parent',a,'Tag','Button_compute', ...
	'Units','normalized','Position',[0.032 0.16 0.2 0.12], ...
	'FontUnits','normalized','FontWeight','bold','FontSize',0.4, ...
    'String','Compute', ...
	'Callback','eval([''global '' fl_wsamod_compute(''compute'',who)])');

uicontrol('Parent',a,'Tag','Button_help', ...
	'Units','normalized','Position',[0.41 0.16 0.2 0.12], ...
	'FontUnits','normalized','FontWeight','bold','FontSize',0.4, ...
    'String','Help', ...
	'Callback','fl_wsamod_compute(''help'');');

uicontrol('Parent',a,'Tag','Button_close', ...
	'Units','normalized','Position',[0.77 0.16 0.2 0.12], ...
	'FontUnits','normalized','FontWeight','bold','FontSize',0.4, ...
	'String','Close', ...
	'Callback','fl_wsamod_compute(''close'');');

%%%%%%%%%%%%%%%%%%%%% PERCENTAGE DISPLAY %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
uicontrol('Parent',a,'Style','text','Tag','StaticText_count', ...
	'Units','normalized','Position',[0.25 0.03 0.6 0.07], ...
	'FontUnits','normalized','FontWeight','bold','FontSize',0.6, ...
	'String','% of processed coefficients','HorizontalAlignment','left');

uicontrol('Parent',a,'Style','edit','Tag','EditText_count', ...
	'Units','normalized','Position',[0.77 0.05 0.2 0.07], ...
	'FontUnits','normalized','FontSize',0.6);

fl_window_init(a);
set(findobj(a,'Tag','StaticText_count'),'BackgroundColor',fl_getOption('BackGroundColor'));
set(findobj(a,'Tag','StaticText_count'),'ForegroundColor',fl_getOption('AltFontColor'));

if nargout > 0, fig = a; end

fl_wsamod_compute('refresh');
