function fig = gui_fl_estimGQV2DH()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.

% Modified by Christian Choque Cortez, December 2008

% FracLab 2.05 Beta, Copyright © 1996 - 2009 by INRIA
% -- --
% For details on use and redistribution refer to $fraclab/licence.txt
%--------------------------------------------------------------------------

a = figure( 'Name','GQV based estimation 2D','Tag','Fig_gui_fl_estimGQV2DH',...
    'MenuBar','none','IntegerHandle','off','NumberTitle','off', ...
    'Position',[20 38 369 272]);

%%%%%%%%%%%%%%%%%%% CREATE FRAME %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
uicontrol('Parent',a,'Style','frame','Tag','Frame_title', ...
    'Units','normalized','Position',[0.049 0.879 0.919 0.1]);

uicontrol('Parent',a,'Style','frame','Tag','Frame_input', ...
    'Units','normalized','Position',[0.049 0.705 0.919 0.154]);

uicontrol('Parent',a,'Style','frame','Tag','Frame_size_input', ...
    'Units','normalized','Position',[0.049 0.169 0.919 0.52]);

%%%%%%%%%%%%%%%%%%% TITLE FRAME %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
uicontrol('Parent',a,'Style','text','Tag','StaticText_title', ...
    'Units','normalized','Position',[0.06 0.89 0.9 0.07], ...
    'FontUnits','normalized','FontWeight','bold','FontSize',0.6, ...
    'String','Estimation of Holder exponent - GQV based method 2D');

%%%%%%%%%%%%%%%%%%% INPUT SIGNAL %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
uicontrol('Parent',a,'Style','text','Tag','StaticText_input', ...
    'Units','normalized','Position',[0.08 0.73 0.22 0.07], ...
    'FontUnits','normalized','FontWeight','bold','FontSize',0.6, ...
    'String','Input Signal');

uicontrol('Parent',a,'Style','edit','Tag','EditText_input', ...
    'Units','normalized','Position',[0.33 0.74 0.33 0.08], ...
    'FontUnits','normalized','FontSize',0.6, ...
    'String','', ...
    'Enable','inactive');

uicontrol('Parent',a,'Tag','Button_refresh', ...
    'Units','normalized','Position',[0.71 0.72 0.23 0.12], ...
    'FontUnits','normalized','FontWeight','bold','FontSize',0.4, ...
    'String','Refresh', ...
    'Callback','fl_estimGQV2DH_compute(''refresh'')');

%%%%%%%%%%%%%%%%%%%% GLOBAL PARAMETERS %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
uicontrol('Parent',a,'Style','text','Tag','StaticText_gamma', ...
    'Units','normalized','Position',[0.07 0.59 0.15 0.07], ...
    'FontUnits','normalized','FontSize',0.6, ...
    'String','Gamma');

uicontrol('Parent',a,'Style','edit','Tag','EditText_gamma', ...
    'Units','normalized','Position',[0.23 0.6 0.12 0.07], ...
    'FontUnits','normalized','FontSize',0.6, ...
    'String','0.8', ...
    'Callback','fl_estimGQV2DH_compute(''edit_gamma'')');

uicontrol('Parent',a,'Style','text','Tag','StaticText_delta', ...
    'Units','normalized','Position',[0.41 0.59 0.1 0.07], ...
    'FontUnits','normalized','FontSize',0.6, ...
    'String','Delta');

uicontrol('Parent',a,'Style','edit','Tag','EditText_delta', ...
    'Units','normalized','Position',[0.525 0.6 0.12 0.07], ...
    'FontUnits','normalized','FontSize',0.6, ...
    'String','1', ...
    'Callback','fl_estimGQV2DH_compute(''edit_delta'')');

%%%%%%%%%%%%% SAMPLING AND ZONES PARAMETERS %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
uicontrol('Parent',a,'Style','text','Tag','StaticText_sampling', ...
    'Units','normalized','Position',[0.084 0.5 0.15 0.07], ...
    'FontUnits','normalized','FontSize',0.6, ...
    'String','Sampling');

uicontrol('Parent',a,'Style','radiobutton','Tag','RadioButton_linear', ...
    'Units','normalized','Position',[0.26 0.507 0.15 0.07], ...
    'FontUnits','normalized','FontSize',0.6, ...
    'String','Linear', ...
    'Value',1, ...
    'Callback','fl_estimGQV2DH_compute(''linear_option'')');

uicontrol('Parent',a,'Style','radiobutton','Tag','RadioButton_geometric', ...
    'Units','normalized','Position',[0.44 0.507 0.21 0.07], ...
    'FontUnits','normalized','FontSize',0.6, ...
    'String','Geometric', ...
    'Value',0, ...
    'Callback','fl_estimGQV2DH_compute(''geometric_option'')');

uicontrol('Parent',a,'Style','text','Tag','StaticText_zones', ...
    'Units','normalized','Position',[0.69 0.5 0.1 0.07], ...
    'FontUnits','normalized','FontSize',0.6, ...
    'String','Zones');

uicontrol('Parent',a,'Style','edit','Tag','EditText_zones', ...
    'Units','normalized','Position',[0.82 0.52 0.12 0.07], ...
    'FontUnits','normalized','FontSize',0.6, ...
    'String','7', ...
    'Callback','fl_estimGQV2DH_compute(''edit_zones'')');

uicontrol('Parent',a,'Style','text','Tag','StaticText_k1', ...
    'Units','normalized','Position',[0.1 0.41 0.1 0.07], ...
    'FontUnits','normalized','FontSize',0.6, ...
    'String','Initial');

uicontrol('Parent',a,'Style','edit','Tag','EditText_k1', ...
    'Units','normalized','Position',[0.23 0.43 0.12 0.07], ...
    'FontUnits','normalized','FontSize',0.6, ...
    'String','1', ...
    'Callback','fl_estimGQV2DH_compute(''edit_k1'')');

uicontrol('Parent',a,'Style','text','Tag','StaticText_k2', ...
    'Units','normalized','Position',[0.41 0.41 0.1 0.07], ...
    'FontUnits','normalized','FontSize',0.6, ...
    'String','Final');

uicontrol('Parent',a,'Style','edit','Tag','EditText_k2', ...
    'Units','normalized','Position',[0.525 0.43 0.12 0.07], ...
    'FontUnits','normalized','FontSize',0.6, ...
    'String','5', ...
    'Callback','fl_estimGQV2DH_compute(''edit_k2'')');

uicontrol('Parent',a,'Style','text','Tag','StaticText_step', ...
    'Units','normalized','Position',[0.7 0.41 0.1 0.07], ...
    'FontUnits','normalized','FontSize',0.6, ...
    'String','Step');

uicontrol('Parent',a,'Style','edit','Tag','EditText_step', ...
    'Units','normalized','Position',[0.82 0.43 0.12 0.07], ...
    'FontUnits','normalized','FontSize',0.6, ...
    'String','1', ...
    'Callback','fl_estimGQV2DH_compute(''edit_step'')');

%%%%%%%%%%%%%%%% TIME INSTANT PARAMETERS %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
uicontrol('Parent',a,'Style','Checkbox','Tag','Check_timeinstant', ...
    'Units','normalized','Position',[0.11 0.31 0.44 0.07], ...
    'FontUnits','normalized','FontSize',0.6, ...
    'String','Holder Function', ...
    'Value',1, ...
    'Callback','fl_estimGQV2DH_compute(''check_time'')');

uicontrol('Parent',a,'Style','text','Tag','StaticText_timeinstant', ...
    'Units','normalized','Position',[0.59 0.3 0.2 0.07], ...
    'FontUnits','normalized','FontSize',0.6, ...
    'String','Time Instant', ...
    'Enable','off');

[SigIn_name] = fl_get_input ('matrix');
eval(['global ' SigIn_name]);
SigIn = eval(SigIn_name);
N = min(size(SigIn));

uicontrol('Parent',a,'Style','edit','Tag','EditText_timeinstant', ...
    'Units','normalized','Position',[0.82 0.32 0.12 0.07], ...
    'FontUnits','normalized','FontSize',0.6, ...
    'String',[num2str(floor(1+N*rand(1))),',',num2str(floor(1+N*rand(1)))], ...
    'Enable','off', ...
    'Callback','fl_estimGQV2DH_compute(''edit_time'')');

%%%%%%%%%%%%%%%%%%% REGRESSION PARAMETERS %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
uicontrol('Parent',a,'Style','Checkbox','Tag','Check_regression', ...
    'Units','normalized','Position',[0.11 0.2 0.28 0.07], ...
    'FontUnits','normalized','FontSize',0.6, ...
    'String','Regression', ...
    'Value',1, ...
    'Callback','fl_estimGQV2DH_compute(''check_regression'')');

uicontrol('Parent',a,'Style','popupmenu','Tag','Regtype_menu', ...
    'Units','normalized','Position',[0.41 0.2 0.53 0.08], ...
    'FontUnits','normalized','FontSize',0.6, ...
    'String',{'Least Square','Weighted Least Square','Penalized Least Square',...
              'Lepskii Adaptive Procedure','Maximum Likelihood','lim inf','lim sup'}, ...
    'Value',1, ...
    'Callback','fl_estimGQV2DH_compute(''regtype'')');

%%%%%%%%%%%%%%%%%%%% COMPUTE/HELP/CLOSE %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
uicontrol('Parent',a,'Tag','Button_compute', ...
    'Units','normalized','Position',[0.049 0.03 0.23 0.12], ...
    'FontUnits','normalized','FontWeight','bold','FontSize',0.4, ...
    'String','Compute', ...
    'Callback','eval([''global '' fl_estimGQV2DH_compute(''compute'',who)])');

uicontrol('Parent',a,'Tag','Button_help', ...
    'Units','normalized','Position',[0.39 0.03 0.23 0.12], ...
    'FontUnits','normalized','FontWeight','bold','FontSize',0.4, ...
    'String','Help', ...
    'Callback','fl_estimGQV2DH_compute(''help'')');

uicontrol('Parent',a,'Tag','Button_close', ...
    'Units','normalized','Position',[0.735 0.03 0.23 0.12], ...
    'FontUnits','normalized','FontWeight','bold','FontSize',0.4, ...
    'String','Close', ...
    'Callback','fl_estimGQV2DH_compute(''close'')');

fl_window_init(a);

if nargout > 0, fig = a; end

fl_estimGQV2DH_compute('refresh');
