function gui_fl_lse()
% This is the machine-generated representation of a MATLAB object
% and its children.  Note that handle values may change when these
% objects are re-created. This may cause problems with some callbacks.
% The command syntax may be supported in the future, but is currently 
% incomplete and subject to change.
%
% To re-open this system, just type the name of the m-file at the MATLAB
% prompt. The M-file and its associtated MAT-file must be on your path.

% Author Christophe Canus, June 1999

% FracLab 2.05 Beta, Copyright © 1996 - 2009 by INRIA
% -- --
% For details on use and redistribution refer to $fraclab/licence.txt
%--------------------------------------------------------------------------
                  
a = figure( ...
	'Colormap',[], ...
	'HandleVisibility','callback', ...
	'MenuBar','none','IntegerHandle','off','NumberTitle','off', ...
	'Name','Legendre Spectrum Estimation', ...
	'Position',[20 50 400 450], ...
	'Tag','Fig_gui_fl_lse', ...
	'UserData',0.00137174);
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.344086021505376, ...
	'Position',[0.05 0.9 0.9 0.0775], ...
	'Style','frame', ...
	'Tag','Frame_gui_fl_fgse');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.533333333333333, ...
	'FontWeight','bold', ...
	'Position',[0.15 0.905 0.7 0.05], ...
	'String','Legendre spectrum estimation', ...
	'Style','text', ...
	'Tag','StaticText_gui_fl_fgse');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.20125786163522, ...
	'Position',[0.05 0.7425 0.9 0.1325], ...
	'Style','frame', ...
	'Tag','Frame_input');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.666666666666667, ...
	'FontWeight','bold', ...
	'HorizontalAlignment','left', ...
	'Position',[0.075 0.8125 0.2 0.04], ...
	'String','Input data', ...
	'Style','text', ...
	'Tag','StaticText_input');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_lse(''fl_lse_Radiobutton_measure'');', ...
	'FontSize',0.666666666666667, ...
	'Position',[0.275 0.8125 0.2 0.04], ...
	'String','measure', ...
	'Style','radiobutton', ...
	'Tag','fl_lse_RadioButton_measure', ...
	'Value',1);
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_lse(''fl_lse_Radiobutton_function'');', ...
	'FontSize',0.666666666666667, ...
	'Position',[0.5 0.8125 0.2 0.04], ...
	'String','function', ...
	'Style','radiobutton', ...
	'Tag','fl_lse_RadioButton_function');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Enable','off', ...
	'Callback','fl_lse(''fl_lse_Radiobutton_cwt'');', ...
	'FontSize',0.666666666666667, ...
	'Position',[0.725 0.8125 0.2 0.04], ...
	'String','cwt', ...
	'Style','radiobutton', ...
	'Tag','fl_lse_RadioButton_cwt');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_lse(''refresh'');', ...
	'FontSize',0.666666666666667, ...
	'FontWeight','bold', ...
	'Position',[0.075 0.7675 0.15 0.04], ...
	'String','Refresh', ...
	'Tag','Pushbutton_refresh');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.666666666666667, ...
	'HorizontalAlignment','center', ...
	'Position',[0.275 0.7675 0.1 0.04], ...
	'String','name', ...
	'Style','text', ...
	'Tag','fl_lse_StaticText_name');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',0.666666666666667, ...
	'HorizontalAlignment','left', ...
	'Position',[0.4 0.7675 0.2 0.04], ...
	'String','Input data name', ...
	'Style','edit', ...
	'Enable','inactive',...
	'Tag','fl_lse_StaticText_sig_nname');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.666666666666667, ...
	'HorizontalAlignment','center', ...
	'Position',[0.6 0.7675 0.1 0.04], ...
	'String','size', ...
	'Style','text', ...
	'Tag','fl_lse_StaticText_size');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',0.666666666666667, ...
	'HorizontalAlignment','center', ...
	'Position',[0.725 0.7675 0.2 0.04], ...
	'String','[M x N]', ...
	'Style','edit', ...
	'Enable','inactive',...
	'Tag','fl_lse_EditText_size');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.0778588807785888, ...
	'Position',[0.05 0.375 0.9 0.3425], ...
	'Style','frame', ...
	'Tag','Frame_partition');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.592592592592593, ...
	'FontWeight','bold', ...
	'HorizontalAlignment','center', ...
	'Position',[0.1 0.6625 0.8 0.045], ...
	'String','Partition function estimation', ...
	'Style','text', ...
	'Tag','fl_lse_StaticText_partition');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.666666666666667, ...
	'HorizontalAlignment','left', ...
	'Position',[0.075 0.6325 0.4 0.04], ...
	'String','min size', ...
	'Style','text', ...
	'Tag','fl_lse_StaticText_min');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','fl_lse(''fl_lse_EditText_min'');', ...
	'FontSize',0.666666666666667, ...
	'Max',64, ...
	'Min',1, ...
	'Position',[0.075 0.6 0.175 0.04], ...
	'String','1', ...
	'Style','edit', ...
	'Tag','fl_lse_EditText_min', ...
	'Value',1);
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_lse(''fl_lse_Slider_min'');', ...
	'FontSize',0.666666666666667, ...
	'Max',64, ...
	'Min',1, ...
	'Position',[0.275 0.6 0.2 0.04], ...
	'Style','slider', ...
	'Tag','fl_lse_Slider_min', ...
	'Value',1);
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.666666666666667, ...
	'HorizontalAlignment','left', ...
	'Position',[0.525 0.6325 0.4 0.04], ...
	'String','max size', ...
	'Style','text', ...
	'Tag','fl_lse_StaticText_max');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','fl_lse(''fl_lse_EditText_max'');', ...
	'FontSize',0.666666666666667, ...
	'Max',64, ...
	'Min',1, ...
	'Position',[0.525 0.6 0.175 0.04], ...
	'String','8', ...
	'Style','edit', ...
	'Tag','fl_lse_EditText_max', ...
	'Value',8);
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_lse(''fl_lse_Slider_max'');', ...
	'FontSize',0.666666666666667, ...
	'Max',64, ...
	'Min',1, ...
	'Position',[0.725 0.6 0.2 0.04], ...
	'Style','slider', ...
	'Tag','fl_lse_Slider_max', ...
	'Value',8);
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.666666666666667, ...
	'HorizontalAlignment','left', ...
	'Position',[0.075 0.5325 0.2 0.04], ...
	'String','# of sizes', ...
	'Style','text', ...
	'Tag','fl_lse_StaticText_size_nb');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','fl_lse(''fl_lse_EditText_size_nb'');', ...
	'FontSize',0.666666666666667, ...
	'Max',10, ...
	'Min',1, ...
	'Position',[0.225 0.5325 0.1 0.04], ...
	'String','5', ...
	'Style','edit', ...
	'Tag','fl_lse_EditText_size_nb', ...
	'Value',5);
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[0.701961 0.701961 0.701961], ...
	'Callback','fl_lse(''fl_lse_Slider_size_nb'');', ...
	'FontSize',0.666666666666667, ...
	'Max',10, ...
	'Min',1, ...
	'Position',[0.35 0.5325 0.2 0.04], ...
	'Style','slider', ...
	'Tag','fl_lse_Slider_size_nb', ...
	'Value',5);
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.666666666666667, ...
	'HorizontalAlignment','left', ...
	'Position',[0.575 0.5325 0.2 0.04], ...
	'String','progress.', ...
	'Style','text', ...
	'Tag','fl_lse_StaticText_progression');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_lse(''fl_lse_Popupmenu_progression'');', ...
	'FontSize',0.666666666666667, ...
	'Max',3, ...
	'Min',1, ...
	'Position',[0.725 0.5325 0.2 0.04], ...
	'String',{'linear','logarithmic','decimated'}, ...
	'Style','popupmenu', ...
	'Tag','fl_lse_PopupMenu_progression', ...
	'Value',1);
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.666666666666667, ...
	'HorizontalAlignment','left', ...
	'Position',[0.075 0.475 0.2 0.04], ...
	'String','ball', ...
	'Style','text', ...
	'Tag','fl_lse_StaticText_ball');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_lse(''fl_lse_Popupmenu_ball'');', ...
	'FontSize',0.666666666666667, ...
	'Max',3, ...
	'Min',1, ...
	'Position',[0.235 0.475 0.25 0.04], ...
	'String',{'center','asymmetric','star'}, ...
	'Style','popupmenu', ...
	'Tag','fl_lse_PopupMenu_ball', ...
	'Value',1);
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.666666666666667, ...
	'HorizontalAlignment','left', ...
	'Position',[0.5 0.475 0.2 0.04], ...
	'String','power', ...
	'Style','text', ...
	'Tag','fl_lse_StaticText_power');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','fl_lse(''fl_lse_EditText_power'');', ...
	'Enable','off', ...
	'FontSize',0.666666666666667, ...
	'Max',10, ...
	'Min',1, ...
	'Position',[0.6 0.475 0.1 0.04], ...
	'SliderStep',[0.99 1], ...
	'String','2.0', ...
	'Style','edit', ...
	'Tag','fl_lse_EditText_power', ...
	'Value',2);
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_lse(''fl_lse_Slider_power'');', ...
	'Enable','off', ...
	'FontSize',0.666666666666667, ...
	'Max',10, ...
	'Min',1, ...
	'Position',[0.725 0.475 0.2 0.04], ...
	'Style','slider', ...
	'Tag','fl_lse_Slider_power', ...
	'Value',2);
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.313725490196078, ...
	'Position',[0.05 0.375 0.9 0.085], ...
	'Style','frame', ...
	'Tag','Frame_q');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.666666666666667, ...
	'HorizontalAlignment','left', ...
	'Position',[0.075 0.400 0.2 0.04], ...
	'String','min q', ...
	'Style','text', ...
	'Tag','fl_lse_StaticText_min_q');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','fl_lse(''fl_lse_EditText_min_q'');', ...
	'FontSize',0.666666666666667, ...
	'Max',0, ...
	'Min',-50, ...
	'Position',[0.185 0.400 0.105 0.04], ...
	'String','-10', ...
	'Style','edit', ...
	'Tag','fl_lse_EditText_min_q', ...
	'Value',-10);
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.666666666666667, ...
	'HorizontalAlignment','left', ...
	'Position',[0.375 0.400 0.2 0.04], ...
	'String','max q', ...
	'Style','text', ...
	'Tag','fl_lse_StaticText_max_q');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','fl_lse(''fl_lse_EditText_max_q'');', ...
	'FontSize',0.666666666666667, ...
	'Max',50, ...
	'Min',0, ...
	'Position',[0.495 0.400 0.105 0.04], ...
	'String','10', ...
	'Style','edit', ...
	'Tag','fl_lse_EditText_max_q', ...
	'Value',10);
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.666666666666667, ...
	'HorizontalAlignment','left', ...
	'Position',[0.675 0.400 0.2 0.04], ...
	'String','# of q''s', ...
	'Style','text', ...
	'Tag','fl_lse_StaticText_q_nb');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','fl_lse(''fl_lse_EditText_q_nb'');', ...
	'FontSize',0.666666666666667, ...
	'Max',201, ...
	'Min',1, ...
	'Position',[0.825 0.400 0.105 0.04], ...
	'String','101', ...
	'Style','edit', ...
	'Tag','fl_lse_EditText_q_nb', ...
	'Value',101);
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','eval([''global '' fl_lse(''compute_partition'',who)]);', ...
	'FontSize',0.355555555555556, ...
	'FontWeight','bold', ...
	'Position',[0.3 0.2825 0.4 0.075], ...
	'String','Compute partition', ...
	'Tag','Pushbutton_compute_partition');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.242424242424242, ...
	'Position',[0.05 0.15 0.9 0.110], ...
	'Style','frame', ...
	'Tag','Frame_spectra');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.666666666666667, ...
	'FontWeight','bold', ...
	'HorizontalAlignment','center', ...
	'Position',[0.1 0.215 0.8 0.04], ...
	'String','Spectrum estimation', ...
	'Style','text', ...
	'Tag','fl_lse_StaticText_spectrum');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.666666666666667, ...
	'HorizontalAlignment','left', ...
	'Position',[0.075 0.175 0.40 0.04], ...
	'String','Specify LR range', ...
	'Style','radiobutton', ...
	'Tag','fl_lse_StaticText_range');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_lse(''fl_lse_Popupmenu_regression'');', ...
	'FontSize',0.666666666666667, ...
	'Max',5, ...
	'Min',1, ...
	'Position',[0.525 0.175 0.40 0.04], ...
	'String',{'Least square','Weighted least square','Penalized least square','Maximum likelihood','Lepskii adaptive proc.'}, ...
	'Style','popupmenu', ...
	'Tag','fl_lse_PopupMenu_regression', ...
	'Value',1);
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','eval([''global '' fl_lse(''compute'',who)]);', ...
	'FontSize',0.355555555555556, ...
	'FontWeight','bold', ...
	'Position',[0.05 0.05 0.2 0.075], ...
	'String','Compute', ...
	'Tag','Pushbutton_compute');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','helpwin fl_lse;', ...
	'FontSize',0.355555555555556, ...
	'FontWeight','bold', ...
	'Position',[0.4 0.05 0.2 0.075], ...
	'String','Help', ...
	'Tag','Pushbutton_help');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[0.701961 0.701961 0.701961], ...
	'Callback','close(findobj(''Tag'',''Fig_gui_fl_lse''));', ...
	'FontSize',0.355555555555556, ...
	'FontWeight','bold', ...
	'Position',[0.75 0.05 0.2 0.075], ...
	'String','Close', ...
	'Tag','Pushbutton_close');

fl_window_init(a);