function gui_fl_mfianalysis()
% This is the machine-generated representation of a MATLAB object
% and its children.  Note that handle values may change when these
% objects are re-created. This may cause problems with some callbacks.
% The command syntax may be supported in the future, but is currently 
% incomplete and subject to change.
%
% To re-open this system, just type the name of the m-file at the MATLAB
% prompt. The M-file and its associtated MAT-file must be on your path. 

% Author Christian Choque Cortez, September 2009

% FracLab 2.05 Beta, Copyright © 1996 - 2009 by INRIA
% -- --
% For details on use and redistribution refer to $fraclab/licence.txt
%--------------------------------------------------------------------------

a = figure('Name','mfi Small Objects Detection',...
    'Tag','Fig_gui_fl_mfianalysis','MenuBar','none','IntegerHandle','off','NumberTitle','off',...
	'Position',[20 40 930 875]);

%%%%%%%%%%%%%%%%%%% CREATE FRAME %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
uicontrol('Parent',a,'Style','frame','Tag','Frame_title', ...
	'Units','normalized','Position',[0.022 0.95 0.325 0.035]);

uicontrol('Parent',a,'Style','frame','Tag','Frame_input', ...
	'Units','normalized','Position',[0.022 0.9 0.325 0.04]);

uicontrol('Parent',a,'Style','frame','Tag','Frame_parameters', ...
	'Units','normalized','Position',[0.022 0.79 0.325 0.104]);

uicontrol('Parent',a,'Style','frame','Tag','Frame_fh_alpha', ...
	'Units','normalized','Position',[0.022 0.65 0.325 0.077],'enable','off');

%%%%%%%%%%%%%%%%%%% TITLE FRAME %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
uicontrol('Parent',a,'Style','text','Tag','StaticText_title', ...
	'Units','normalized','Position',[0.075 0.955 0.22 0.023], ...
	'FontUnits','normalized','FontWeight','bold','FontSize',0.6, ...
	'String','Multifractal Image Analysis');

%%%%%%%%%%%%%%%%%%% INPUT SIGNAL %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
uicontrol('Parent',a,'Style','text','Tag','StaticText_input', ...
	'Units','normalized','Position',[0.03 0.906 0.08 0.021], ...
	'FontUnits','normalized','FontWeight','bold','FontSize',0.6, ...
	'String','Input signal');

uicontrol('Parent',a,'Style','edit','Tag','EditText_input', ...
	'Units','normalized','Position',[0.12 0.91 0.14 0.022], ...
	'FontUnits','normalized','FontSize',0.6, ...
	'String','', ...
	'Enable','inactive');

uicontrol('Parent',a,'Tag','Button_refresh', ...
	'Units','normalized','Position',[0.275 0.908 0.06 0.027], ...
	'FontUnits','normalized','FontWeight','bold','FontSize',0.4, ...
	'String','Refresh', ...
    'Callback','fl_mfianalysis_compute(''refresh'')');

%%%%%%%%%%%%%%%%%%%% INPUT PARAMETERS %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
uicontrol('Parent',a,'Style','text','Tag','StaticText_method', ...
	'Units','normalized','Position',[0.03 0.86 0.055 0.02], ...
	'FontUnits','normalized','FontSize',0.6,'HorizontalAlignment','left', ...
	'String','Method');

uicontrol('Parent',a,'Style','popupmenu','Tag','Method_menu', ...
	'Units','normalized','Position',[0.1 0.865 0.08 0.021], ...
	'FontUnits','normalized','FontSize',0.6, ...
    'String',{'mini','maxi','min','max','sum','iso'}, ...
	'Value',1, ...
    'Callback','fl_mfianalysis_compute(''method'')');

uicontrol('Parent',a,'Style','Checkbox','Tag','Check_negative', ...
    'Units','normalized','Position',[0.22 0.862 0.12 0.02], ...
    'FontUnits','normalized','FontSize',0.6, ...
    'String','Negative image', ...
    'Value',1, ...
    'Callback','fl_mfianalysis_compute(''check_negative'')');

uicontrol('Parent',a,'Style','text','Tag','StaticText_sensibility', ...
	'Units','normalized','Position',[0.1 0.832 0.07 0.02], ...
	'FontUnits','normalized','FontSize',0.6,'HorizontalAlignment','left', ...
	'String','Sensibility','enable','off');

uicontrol('Parent',a,'Style','slider','Tag','Slider_sensibility', ...
	'Units','normalized','Position',[0.18 0.835 0.09 0.02], ...
	'Value',0.8,'enable','off', ...
	'Callback','fl_mfianalysis_compute(''slider_sensibility'')');

uicontrol('Parent',a,'Style','edit','Tag','EditText_sensibility', ...
	'Units','normalized','Position',[0.28 0.835 0.056 0.02], ...
	'FontUnits','normalized','FontSize',0.6, ...
	'String',200,'enable','off', ...
    'Callback','fl_mfianalysis_compute(''edit_sensibility'')');

uicontrol('Parent',a,'Style','text','Tag','StaticText_radius', ...
	'Units','normalized','Position',[0.03 0.796 0.06 0.02], ...
	'FontUnits','normalized','FontSize',0.6,'HorizontalAlignment','left', ...
	'String','Radius');

uicontrol('Parent',a,'Style','edit','Tag','EditText_radius', ...
	'Units','normalized','Position',[0.1 0.8 0.056 0.02], ...
	'FontUnits','normalized','FontSize',0.6, ...
	'String',2, ...
    'Callback','fl_mfianalysis_compute(''edit_radius'')');

uicontrol('Parent',a,'Style','text','Tag','StaticText_alphabins', ...
	'Units','normalized','Position',[0.18 0.796 0.1 0.02], ...
	'FontUnits','normalized','FontSize',0.6,'HorizontalAlignment','left', ...
	'String','Alpha bins (NA)');

uicontrol('Parent',a,'Style','edit','Tag','EditText_alphabins', ...
	'Units','normalized','Position',[0.28 0.8 0.056 0.02], ...
	'FontUnits','normalized','FontSize',0.6, ...
	'String','100', ...
    'Callback','fl_mfianalysis_compute(''edit_step'')');

%%%%%%%%%%%%%%%%%%%%% F(ALPHA) PARAMETERS %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
uicontrol('Parent',a,'Style','text','Tag','StaticText_fhalpha', ...
	'Units','normalized','Position',[0.035 0.69 0.11 0.021], ...
	'FontUnits','normalized','FontWeight','bold','FontSize',0.6, ...
    'HorizontalAlignment','left', ...
	'String','F(alpha) range ');

uicontrol('Parent',a,'Style','text','Tag','StaticText_min', ...
	'Units','normalized','Position',[0.15 0.69 0.03 0.02], ...
	'FontUnits','normalized','FontSize',0.6,'HorizontalAlignment','left', ...
	'String','Min','Enable','off');

uicontrol('Parent',a,'Style','edit','Tag','EditText_min', ...
	'Units','normalized','Position',[0.18 0.695 0.056 0.02], ...
	'FontUnits','normalized','FontSize',0.6, ...
	'String',0,'Enable','off', ...
    'Callback','fl_mfianalysis_compute(''edit_min'')');

uicontrol('Parent',a,'Style','text','Tag','StaticText_max', ...
	'Units','normalized','Position',[0.25 0.69 0.03 0.02], ...
	'FontUnits','normalized','FontSize',0.6,'HorizontalAlignment','left', ...
	'String','Max','Enable','off');

uicontrol('Parent',a,'Style','edit','Tag','EditText_max', ...
	'Units','normalized','Position',[0.28 0.695 0.056 0.02], ...
	'FontUnits','normalized','FontSize',0.6, ...
	'String',0.25,'Enable','off', ...
    'Callback','fl_mfianalysis_compute(''edit_max'')');

uicontrol('Parent',a,'Tag','Button_apply', ...
	'Units','normalized','Position',[0.035 0.655 0.05 0.027], ...
	'FontUnits','normalized','FontWeight','bold','FontSize',0.4, ...
	'String','Apply','Enable','off', ...
    'Callback','fl_mfianalysis_compute(''apply'')');

uicontrol('Parent',a,'Tag','Button_default', ...
	'Units','normalized','Position',[0.105 0.655 0.06 0.027], ...
	'FontUnits','normalized','FontWeight','bold','FontSize',0.4, ...
	'String','Default','Enable','off', ...
    'Callback','fl_mfianalysis_compute(''default'')');

uicontrol('Parent',a,'Tag','Button_increase', ...
	'Units','normalized','Position',[0.19 0.655 0.06 0.027], ...
	'FontUnits','normalized','FontWeight','bold','FontSize',0.4, ...
	'String','Increase','Enable','off', ...
    'Callback','fl_mfianalysis_compute(''increase'')');

uicontrol('Parent',a,'Tag','Button_decrease', ...
	'Units','normalized','Position',[0.271 0.655 0.065 0.027], ...
	'FontUnits','normalized','FontWeight','bold','FontSize',0.4, ...
	'String','Decrease','Enable','off', ...
    'Callback','fl_mfianalysis_compute(''decrease'')');

%%%%%%%%%%%%%%%%%%%%% FIGURES TITLES %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
uicontrol('Parent',a,'Style','text','Tag','StaticText_fig1', ...
	'Units','normalized','Position',[0.385 0.93 0.15 0.02], ...
	'FontUnits','normalized','FontSize',0.6,'HorizontalAlignment','left', ...
	'String','0 < F(alpha) bw < 0.25');

axes('Parent',a,'Tag','axes1','XTick',[],'YTick',[], ...
	'Units','normalized','Position',[0.38 0.66 0.28 0.27]);

uicontrol('Parent',a,'Style','text','Tag','StaticText_fig2', ...
	'Units','normalized','Position',[0.715 0.93 0.17 0.02], ...
	'FontUnits','normalized','FontSize',0.6,'HorizontalAlignment','left', ...
	'String','Haussdorf segmentation');

uicontrol('Parent',a,'Tag','Button_save2', ...
	'Units','normalized','Position',[0.94 0.93 0.05 0.02], ...
	'FontUnits','normalized','FontWeight','bold','FontSize',0.6, ...
	'String','Save', ...
    'Callback','eval([''global '' fl_mfianalysis_compute(''save2'',who)])');

axes('Parent',a,'Tag','axes2','XTick',[],'YTick',[], ...
	'Units','normalized','Position',[0.71 0.66 0.28 0.27]);

uicontrol('Parent',a,'Style','text','Tag','StaticText_fig3', ...
	'Units','normalized','Position',[0.035 0.61 0.15 0.02], ...
	'FontUnits','normalized','FontSize',0.6,'HorizontalAlignment','left', ...
	'String','Input image');

axes('Parent',a,'Tag','axes3','XTick',[],'YTick',[], ...
	'Units','normalized','Position',[0.03 0.34 0.28 0.27]);

uicontrol('Parent',a,'Style','text','Tag','StaticText_fig4', ...
	'Units','normalized','Position',[0.385 0.61 0.2 0.02], ...
	'FontUnits','normalized','FontSize',0.6,'HorizontalAlignment','left', ...
	'String','Alpha image');

axes('Parent',a,'Tag','axes4','XTick',[],'YTick',[], ...
	'Units','normalized','Position',[0.38 0.34 0.28 0.27]);

uicontrol('Parent',a,'Style','text','Tag','StaticText_fig5', ...
	'Units','normalized','Position',[0.715 0.61 0.09 0.02], ...
	'FontUnits','normalized','FontSize',0.6,'HorizontalAlignment','left', ...
	'String','Spectrum MF');

uicontrol('Parent',a,'Style','Checkbox','Tag','Check_normalized', ...
    'Units','normalized','Position',[0.82 0.612 0.11 0.02], ...
    'FontUnits','normalized','FontSize',0.6, ...
    'String','Normalization', ...
    'Value',0, ...
    'Callback','fl_mfianalysis_compute(''check_normalized'')');

uicontrol('Parent',a,'Tag','Button_save5', ...
	'Units','normalized','Position',[0.94 0.61 0.05 0.02], ...
	'FontUnits','normalized','FontWeight','bold','FontSize',0.6, ...
	'String','Save', ...
    'Callback','eval([''global '' fl_mfianalysis_compute(''save5'',who)])');

axes('Parent',a,'Tag','axes5','XTick',[],'YTick',[], ...
	'Units','normalized','Position',[0.71 0.34 0.28 0.27]);

uicontrol('Parent',a,'Style','text','Tag','StaticText_fig6', ...
	'Units','normalized','Position',[0.035 0.29 0.2 0.02], ...
	'FontUnits','normalized','FontSize',0.6,'HorizontalAlignment','left', ...
	'String','F(alpha) image');

axes('Parent',a,'Tag','axes6','XTick',[],'YTick',[], ...
	'Units','normalized','Position',[0.03 0.02 0.28 0.27]);

uicontrol('Parent',a,'Style','text','Tag','StaticText_fig7', ...
	'Units','normalized','Position',[0.385 0.29 0.15 0.02], ...
	'FontUnits','normalized','FontSize',0.6,'HorizontalAlignment','left', ...
	'String','0.8 < F(alpha) bw < 1.2');

axes('Parent',a,'Tag','axes7','XTick',[],'YTick',[], ...
	'Units','normalized','Position',[0.38 0.02 0.28 0.27]);

uicontrol('Parent',a,'Style','text','Tag','StaticText_fig8', ...
	'Units','normalized','Position',[0.715 0.29 0.15 0.02], ...
	'FontUnits','normalized','FontSize',0.6,'HorizontalAlignment','left', ...
	'String','1.3 < F(alpha) bw < 1.7');

axes('Parent',a,'Tag','axes8','XTick',[],'YTick',[], ...
	'Units','normalized','Position',[0.71 0.02 0.28 0.27]);

%%%%%%%%%%%%%%%%%%%% COMPUTE/HELP/CLOSE %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
uicontrol('Parent',a,'Tag','Button_compute', ...
    'Units','normalized','Position',[0.024 0.745 0.08 0.035], ...
    'FontUnits','normalized','FontWeight','bold','FontSize',0.4, ...
    'String','Compute', ...
    'Callback','eval([''global '' fl_mfianalysis_compute(''compute'',who)])');

uicontrol('Parent',a,'Tag','Button_help', ...
    'Units','normalized','Position',[0.148 0.745 0.08 0.035], ...
    'FontUnits','normalized','FontWeight','bold','FontSize',0.4, ...
    'String','Help', ...
    'Callback','fl_mfianalysis_compute(''help'')');

uicontrol('Parent',a,'Tag','Button_close', ...
    'Units','normalized','Position',[0.268 0.745 0.08 0.035], ...
    'FontUnits','normalized','FontWeight','bold','FontSize',0.4, ... 
    'String','Close', ...
    'Callback','fl_mfianalysis_compute(''close'')');
	
fl_window_init(a);	

fl_mfianalysis_compute('refresh');
