function gui_fl_dse()
% This is the machine-generated representation of a MATLAB object
% and its children.  Note that handle values may change when these
% objects are re-created. This may cause problems with some callbacks.
% The command syntax may be supported in the future, but is currently 
% incomplete and subject to change.
%
% To re-open this system, just type the name of the m-file at the MATLAB
% prompt. The M-file and its associtated MAT-file must be on your path.
                      
% FracLab 2.05 Beta, Copyright © 1996 - 2009 by INRIA
% -- --
% For details on use and redistribution refer to $fraclab/licence.txt
%--------------------------------------------------------------------------

[SigIn_name error_in] = fl_get_input ('vector') ;
eval(['global ' SigIn_name]) ;
SigIn = eval(SigIn_name) ;
N = length(SigIn) ;
n_max=ceil(log2(N));    %n_max=num2str(ceil(log2(N)));
n_min=ceil(log2(N))-1;  %n_min=num2str(ceil(log2(N))-1);

a = figure( ...
	'Colormap',[], ...
	'HandleVisibility','callback', ...
	'MenuBar','none','IntegerHandle','off','NumberTitle','off', ...
	'Name','1D Lim Sup Dimension Spectrum Estimation', ...
	'Position',[20 50 400 400], ...
	'Tag','Fig_gui_fl_dse', ...
	'UserData',0.00137174);
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.286123032904149, ...
	'Position',[0.05 0.825 0.9 0.09], ...
	'Style','frame', ...
	'Tag','Frame_gui_fl_dse');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.367872470876763, ...
	'FontWeight','bold', ...
	'Position',[0.15 0.83 0.7 0.07], ...
	'String','1D Lim sup dimension spectrum estimation', ...
	'Style','text', ...
	'Tag','StaticText_gui_fl_dse');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.171673819742489, ...
	'Position',[0.05 0.6 0.9 0.15], ...
	'Style','frame', ...
	'Tag','Frame_input');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.643776824034335, ...
	'FontWeight','bold', ...
	'HorizontalAlignment','left', ...
	'Position',[0.075 0.7 0.2 0.04], ...
	'String','Input data', ...
	'Style','text', ...
	'Tag','StaticText_input');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_dse(''radiobutton_measure'');', ...
	'FontSize',0.643776824034335, ...
	'Position',[0.275 0.7 0.2 0.04], ...
	'String','measure', ...
	'Style','radiobutton', ...
	'Tag','RadioButton_measure', ...
	'Value',1);
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_dse(''radiobutton_function'');', ...
	'FontSize',0.643776824034335, ...
	'Position',[0.5 0.7 0.2 0.04], ...
	'String','function', ...
	'Style','radiobutton', ...
	'Tag','RadioButton_function');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_dse(''refresh'');', ...
	'FontSize',0.643776824034335, ...
	'FontWeight','bold', ...
	'Position',[0.075 0.625 0.15 0.04], ...
	'String','Refresh', ...
	'Tag','Pushbutton_refresh');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.643776824034335, ...
	'HorizontalAlignment','center', ...
	'Position',[0.275 0.625 0.1 0.04], ...
	'String','name', ...
	'Style','text', ...
	'Tag','StaticText_name');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',0.643776824034335, ...
	'HorizontalAlignment','left', ...
	'Position',[0.4 0.625 0.2 0.04], ...
	'String','Input data name', ...
	'Style','edit', ...
	'Enable','inactive',...
	'Tag','StaticText_sig_nname');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.643776824034335, ...
	'HorizontalAlignment','center', ...
	'Position',[0.6 0.625 0.1 0.04], ...
	'String','size', ...
	'Style','text', ...
	'Tag','StaticText_size');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',0.643776824034335, ...
	'HorizontalAlignment','center', ...
	'Position',[0.725 0.625 0.2 0.04], ...
	'String','[M x N]', ...
	'Style','edit', ...
	'Enable','inactive',...
	'Tag','EditText_size');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.0953743443013829, ...
	'Position',[0.05 0.2815 0.9 0.27], ...
	'Style','frame', ...
	'Tag','Frame_spectra');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.572246065808298, ...
	'FontWeight','bold', ...
	'HorizontalAlignment','center', ...
	'Position',[0.1 0.5 0.8 0.045], ...
	'String','Spectrum estimation', ...
	'Style','text', ...
	'Tag','StaticText_spectrum');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.643776824034335, ...
	'HorizontalAlignment','left', ...
	'Position',[0.075 0.45 0.3 0.04], ...
	'String','capacity', ...
	'Style','text', ...
	'Tag','StaticText_capacity');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_dse(''popupmenu_capacity'');', ...
	'FontSize',0.643776824034335, ...
	'Position',[0.25 0.45 0.25 0.04], ...
	'String',{'sum','lpsum','iso','adapiso'}, ...
	'Style','popupmenu', ...
	'Tag','PopupMenu_capacity', ...
	'Value',1);
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.643776824034335, ...
	'HorizontalAlignment','left', ...
	'Position',[0.525 0.45 0.2 0.04], ...
	'String','power', ...
	'Style','text', ...
	'Tag','StaticText_power');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','fl_dse(''edittext_power'');', ...
	'Enable','off', ...
	'FontSize',0.643776824034335, ...
	'Max',10, ...
	'Min',1, ...
	'Position',[0.6 0.45 0.1 0.04], ...
	'SliderStep',[0.99 1], ...
	'String','2.0', ...
	'Style','edit', ...
	'Tag','EditText_power', ...
	'Value',2);
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_dse(''slider_power'');', ...
	'Enable','off', ...
	'FontSize',0.643776824034335, ...
	'Max',10, ...
	'Min',1, ...
	'Position',[0.725 0.45 0.2 0.04], ...
	'Style','slider', ...
	'Tag','Slider_power', ...
	'Value',2);
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.643776824034335, ...
	'HorizontalAlignment','left', ...
	'Position',[0.075 0.375 0.2 0.04], ...
	'String','precision', ...
	'Style','text', ...
	'Tag','StaticText_precision');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','fl_dse(''edittext_precision'');', ...
	'FontSize',0.643776824034335, ...
	'Max',1, ...
	'Min',0, ...
	'Position',[0.25 0.375 0.1 0.04], ...
	'String','0.5', ...
	'Style','edit', ...
	'Tag','EditText_precision', ...
	'Value',0.5);
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[0.701961 0.701961 0.701961], ...
	'Callback','fl_dse(''slider_precision'');', ...
	'FontSize',0.643776824034335, ...
	'Max',1, ...
	'Min',0, ...
	'Position',[0.365 0.375 0.2 0.04], ...
	'Style','slider', ...
	'Tag','Slider_precision', ...
	'Value',0.5);
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.643776824034335, ...
	'HorizontalAlignment','left', ...
	'Position',[0.675 0.375 0.2 0.04], ...
	'String','B', ...
	'Style','text', ...
	'Tag','StaticText_B');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','fl_dse(''edittext_B'');', ...
	'FontSize',0.515021459227468, ...
	'Max',1, ...
	'Min',0, ...
	'Position',[0.725 0.375 0.2 0.05], ...
	'String','[1:2:21]', ...
	'Style','edit', ...
	'Tag','EditText_B', ...
	'Value',[1:2:21]);
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.643776824034335, ...
	'HorizontalAlignment','left', ...
	'Position',[0.075 0.3 0.3 0.04], ...
	'String','dimension', ...
	'Style','text', ...
	'Tag','StaticText_capacity');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_dse(''popupmenu_dimension'');', ...
	'FontSize',0.643776824034335, ...
	'Position',[0.2 0.3 0.12 0.04], ...
	'String',{'box','voss','brnb','haus'}, ...
	'Style','popupmenu', ...
	'Tag','PopupMenu_dimension', ...
	'Value',1);
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.643776824034335, ...
	'HorizontalAlignment','left', ...
	'Position',[0.33 0.3 0.3 0.04], ...
	'String','resolution min', ...
	'Style','text', ...
	'Tag','StaticText_sizemin');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_dse(''popupmenu_resolutionmin'');', ...
	'FontSize',0.643776824034335, ...
	'Position',[0.5 0.3 0.1 0.04], ...
	'String',{'4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19'}, ...
	'Style','popupmenu', ...
	'Tag','PopupMenu_resolutionmin', ...
	'Value',n_min-3);
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.643776824034335, ...
	'HorizontalAlignment','left', ...
	'Position',[0.62 0.3 0.3 0.04], ...
	'String','resolution max', ...
	'Style','text', ...
	'Tag','StaticText_sizemax');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_dse(''popupmenu_resolutionmax'');', ...
	'FontSize',0.643776824034335, ...
	'Position',[0.81 0.3 0.12 0.04], ...
	'String',{'5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20'}, ...
	'Style','popupmenu', ...
	'Tag','PopupMenu_resolutionmax', ...
	'Value',n_max-4);
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','eval([''global '' fl_dse(''compute'',who)]);', ...
	'FontSize',0.343347639484979, ...
	'FontWeight','bold', ...
	'Position',[0.05 0.1 0.2 0.075], ...
	'String','Compute', ...
	'Tag','Pushbutton_compute');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','helpwin fl_dse;', ...
	'FontSize',0.343347639484979, ...
	'FontWeight','bold', ...
	'Position',[0.4 0.1 0.2 0.075], ...
	'String','Help', ...
	'Tag','Pushbutton_help');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[0.701961 0.701961 0.701961], ...
	'Callback','close(findobj(''Tag'',''Fig_gui_fl_dse''));', ...
	'FontSize',0.343347639484979, ...
	'FontWeight','bold', ...
	'Position',[0.75 0.1 0.2 0.075], ...
	'String','Close', ...
	'Tag','Pushbutton_close');
	
fl_window_init(a);
