function gui_fl_oscL()
% This is the machine-generated representation of a MATLAB object
% and its children.  Note that handle values may change when these
% objects are re-created. This may cause problems with some callbacks.
% The command syntax may be supported in the future, but is currently 
% incomplete and subject to change.
%
% To re-open this system, just type the name of the m-file at the MATLAB
% prompt. The M-file and its associtated MAT-file must be on your path.

% FracLab 2.05 Beta, Copyright © 1996 - 2009 by INRIA
% -- --
% For details on use and redistribution refer to $fraclab/licence.txt
%--------------------------------------------------------------------------                       

a = figure( ...
	'HandleVisibility','callback', ...
	'MenuBar','none','IntegerHandle','off','NumberTitle','off', ...
	'Position',[19 51 401 400], ...
	'Name','local Estimation','Tag','Fig_gui_fl_oscL');

% Min Max oscillation range choice    
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.339152435453639, ...
	'Position',[0.0298754 0.898052 0.947755 0.0884558], ...
	'Style','frame', ...
	'Tag','Frame1_oscL');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.0588235294117647, ...
	'Position',[0.0298754 0.249999 0.947755 0.51], ...
	'Style','frame', ...
	'Tag','Frame_size_oscL');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.6, ...
	'FontWeight','bold', ...
	'Position',[0.30 0.70 0.4 0.05], ...
	'String','Oscillation balls size', ...
	'Style','text', ...
	'Tag','StaticText_reg_oscL');
    
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.6, ...
	'Position',[0.05 0.645 0.08 0.05], ...
	'String','Nmin', ...
	'Style','text', ...
	'Tag','StaticText_Nmin_oscL');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','fl_oscL_compute(''editNmin'');', ...
	'FontSize',3000, ...
	'Position',[0 0 0.00001 0.00001], ...
	'String','1', ...
	'Style','edit', ...
    'Enable','off', ...
	'Tag','EditText_Nmin_oscL');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_oscL_compute(''ppm_Nmin'');', ...
	'FontSize',0.6, ...
	'Max',5, ...
	'Min',1, ...
	'Position',[0.15 0.65 0.12 0.05], ...
	'String',{'1' '2' '4' '8' '16' '32'}, ...
	'Style','popupmenu', ...
	'Tag','PopupMenu_Nmin_oscL', ...
	'Value',1);
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.6, ...
	'Position',[0.36 0.645 0.08 0.05], ...
	'String','Nmax', ...
	'Style','text', ...
	'Tag','StaticText_Nmax_oscL');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','fl_oscL_compute(''editNmax'');', ...
	'FontSize',3000, ...
	'Position',[0 0 0.00001 0.00001], ...
	'String','8', ...
	'Style','edit', ...
    'Enable','off', ...
	'Tag','EditText_Nmax_oscL');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_oscL_compute(''ppm_Nmax'');', ...
	'FontSize',0.6, ...
	'Max',5, ...
	'Min',1, ...
	'Position',[0.46 0.65 0.12 0.05], ...
	'String',{'2' '4' '8' '16' '32' '64'}, ...
	'Style','popupmenu', ...
	'Tag','PopupMenu_Nmax_oscL', ...
	'Value',3);

b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.6, ...
	'Position',[0.65 0.645 0.18 0.05], ...
	'String','# of balls', ...
	'Style','text', ...
	'Tag','StaticText_voices_oscL');


b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','fl_oscL_compute(''voices'');', ...
	'FontSize',0.6, ...
	'Position',[0.82 0.65 0.08 0.05], ...
	'String','8', ...
	'Style','edit', ...
	'Tag','EditText_voices_oscL');
    
    
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.6, ...
	'Position',[0.035 0.55 0.28 0.05], ...
	'String','Neighbourhood size', ...
	'Style','text', ...
	'Tag','StaticText_Rho_oscL');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','fl_oscL_compute(''editRho'');', ...
	'FontSize',0.6, ...
	'Position',[0.36 0.56 0.08 0.05], ...
	'String','64', ...
	'Style','edit', ...
	'Tag','EditText_Rho_oscL');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_oscL_compute(''ppm_Rho'');', ...
	'FontSize',0.6, ...
	'Max',5, ...
	'Min',1, ...
	'Position',[0.46 0.56 0.12 0.05], ...
	'String',{'2' '4' '8' '16' '32' '64'}, ...
	'Style','popupmenu', ...
	'Tag','PopupMenu_Rho_oscL', ...
	'Value',6);
    
    
% %%%%%%%%%%%%%%%    
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_oscL_compute(''close'');', ...
	'FontSize',0.399999466667378, ...
	'FontWeight','bold', ...
	'Position',[0.720698 0.1025 0.174564 0.0750001], ...
	'String','Close', ...
	'Tag','Pushbutton_wclose_oscL');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','eval([''global '' fl_oscL_compute(''compute_oscL'',who);]);', ...
	'FontSize',0.399999466667378, ...
	'FontWeight','bold', ...
	'Position',[0.0972569 0.1025 0.174564 0.0750001], ...
	'String','Compute', ...
	'Tag','Pushbutton_oscL_compute');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.6, ...
	'FontWeight','bold', ...
	'Position',[0.142762 0.920001 0.726625 0.05], ...
	'String','Local Holder exponent (oscillation method)', ...
	'Style','text', ...
	'Tag','StaticText6');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_oscL_compute(''help'');', ...
	'FontSize',0.399999466667378, ...
	'FontWeight','bold', ...
	'Position',[0.408979 0.1025 0.174564 0.0750001], ...
	'String','Help', ...
	'Tag','Pushbutton1_oscL');
  
   
    
%  Regression type choice window
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.166666666666667, ...
	'Position',[0.0498754 0.27 0.91 0.18], ...
	'Style','frame', ...
	'Tag','Frame_reg_oscL');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.6, ...
	'FontWeight','bold', ...
	'Position',[0.40 0.39 0.206983 0.05], ...
	'String','Regression', ...
	'Style','text', ...
	'Tag','StaticText_reg_oscL');
    
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.6, ...
	'Position',[0.0673317 0.30 0.124688 0.05], ...
	'String','Type', ...
	'Style','text', ...
	'Tag','StaticTextf_regtype_oscL');
    
matreg{1}='Least Square';
matreg{2}='Weighted Least Square';
matreg{3}='Penalized Least Square';
matreg{4}='Lepskii Adaptive Procedure';
matreg{5}='Maximum Likelihood';
matreg{6}='Lim inf';
matreg{7}='Lim sup';

b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_oscL_compute(''ppm_regtype'');', ...
	'FontSize',0.5999988000024, ...
	'Max',2, ...
	'Min',1, ...
	'Position',[0.182045 0.30 0.5 0.0500001], ...
	'String',matreg, ...
	'Style','popupmenu', ...
	'Tag','PopupMenu_regtype_oscL', ...
   'Value',6);
%  ENDOF : Regression type choice window
  
%b = uicontrol('Parent',a, ...
%	'Units','normalized', ...
%	'FontUnits','normalized', ...
%	'FontSize',0.6, ...
%	'Position',[0.0673317 0.285 0.124688 0.05], ...
%	'String','Range', ...
%	'Style','text', ...
%	'Tag','StaticTextf_regrange');

%matrange{1}='Specify';
%matrange{2}='full';
%b = uicontrol('Parent',a, ...
%	'Units','normalized', ...
%	'FontUnits','normalized', ...
%	'Callback','fl_oscL_compute(''ppm_regrange'');', ...
%	'FontSize',0.5999988000024, ...
%	'Max',2, ...
%	'Min',1, ...
%	'Position',[0.182045 0.285 0.344139 0.0500001], ...
%	'String',matrange, ...
%	'Style','popupmenu', ...
%	'Tag','PopupMenu_regrange', ...
%	'Value',1);
    
%b = uicontrol('Parent',a, ...
%	'Units','normalized', ...
%%	'FontUnits','normalized', ...
%	'Callback','fl_oscL_compute(''radiobutton_reg'');', ...
%	'FontSize',0.5999988000024, ...
%	'Position',[0.182045 0.285 0.344139 0.0500001], ...
%	'String','Specify', ...
%	'Style','radiobutton', ...
%	'Tag','Radiobutton_reg', ...
%	'Value',1);
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.272727272727273, ...
	'Position',[0.0298754 0.771251 0.947755 0.11], ...
	'Style','frame', ...
	'Tag','Frame_input_oscL');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.6, ...
	'FontWeight','bold', ...
	'HorizontalAlignment','left', ...
	'Position',[0.08 0.79425 0.25 0.05], ...
	'String','Input data name', ...
	'Style','text', ...
	'Tag','StaticText_input_oscL');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_oscL_compute(''refresh'');', ...
	'FontSize',0.4, ...
	'FontWeight','bold', ...
	'Position',[0.77 0.78625 0.175 0.075], ...
	'String','Refresh', ...
	'Tag','Pushbutton_refresh_oscL');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',0.6, ...
	'HorizontalAlignment','left', ...
	'Position',[0.34 0.79925 0.4 0.05], ...
	'String','', ...
	'Style','edit', ...
	'Enable','inactive',...
	'Tag','EditText_sig_nname_oscL');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_oscL_compute(''radiobutton_time'')', ...
	'FontSize',0.533333333333332, ...
	'Position',[0.35 0.48 0.34 0.05], ...
	'String','Holder Function', ...
	'Style','Checkbox', ...
	'Tag','Radiobutton_adv_track_time', ...
   'Value',1);
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.551723999999999, ...
	'Position',[0.66 0.47 0.15 0.05], ...
   'String','Time Instant', ...
   'Enable','off', ...
	'Style','text', ...
   'Tag','StaticText1');
[SigIn_name error_in] = fl_get_input ('vector') ;
eval(['global ' SigIn_name]) ;
SigIn = eval(SigIn_name) ;
N = length(SigIn) ;
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','fl_oscL_compute(''edit_time'')', ...
   'FontSize',0.533333333333332, ...
   'Enable','off', ...
	'Position',[0.82 0.475 0.12 0.05], ...
	'String',num2str(floor(1+N*rand(1))), ...
	'Style','edit', ...
	'Tag','EditText_adv_oscL_time');

fl_window_init(a);

fl_oscL_compute('refresh');
