function gui_fl_longrange()
% This is the machine-generated representation of a MATLAB object
% and its children.  Note that handle values may change when these
% objects are re-created. This may cause problems with some callbacks.
% The command syntax may be supported in the future, but is currently 
% incomplete and subject to change.
%
% To re-open this system, just type the name of the m-file at the MATLAB
% prompt. The M-file and its associtated MAT-file must be on your path.
             
% FracLab 2.05 Beta, Copyright © 1996 - 2009 by INRIA
% -- --
% For details on use and redistribution refer to $fraclab/licence.txt
%--------------------------------------------------------------------------

a = figure( ...
	'Colormap',[], ...
	'HandleVisibility','callback', ...
	'MenuBar','none','IntegerHandle','off','NumberTitle','off', ...
	'Position',[20 50 300 250], ...
	'Name','cwt-based Estimation - global','Tag','Fig_gui_fl_longrange');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_longrange_compute(''advanced_compute'') ;', ...
	'FontSize',0.399999999999999, ...
	'Position',[0.246667 0.5 0.466667 0.12], ...
	'String','Advanced compute', ...
	'Tag','Pushbutton_longrange_advanced');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_longrange_compute(''compute'') ;', ...
	'FontSize',0.399999999999999, ...
	'FontWeight','bold', ...
	'Position',[0.0633333 0.276 0.233333 0.12], ...
	'String','Compute', ...
	'Tag','Pushbutton_longrange_compute');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_longrange_compute(''help'')', ...
	'FontWeight','bold', ...
	'FontSize',0.399999999999999, ...
	'Position',[0.363333 0.276 0.233333 0.12], ...
	'String','Help', ...
	'Tag','Pushbutton1');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_longrange_compute(''close'')', ...
	'FontSize',0.399999999999999, ...
	'FontWeight','bold', ...
	'Position',[0.663333 0.276 0.233333 0.12], ...
	'String','close', ...
	'Tag','Pushbutton_longrange_close');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.551723999999999, ...
	'FontWeight','bold', ...
	'Position',[0.03 0.07 0.53 0.076], ...
	'String','Global Scaling Exponent', ...
	'Style','text', ...
	'Tag','StaticText_track_HofT');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',0.533333333333332, ...
	'Position',[0.596667 0.07 0.333333 0.08], ...
	'Style','edit', ...
	'Tag','EditText_longrange_H');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.258063999999999, ...
	'Position',[0.0474933 0.731916 0.902377 0.204255], ...
	'Style','frame', ...
	'Tag','Frame1');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.390243999999999, ...
	'FontWeight','bold', ...
	'Position',[0.111926 0.74468 0.80198 0.123404], ...
	'String','Global Scaling Exponent Estimation', ...
	'Style','text', ...
	'Tag','StaticText1');

fl_window_init(a);
set(findobj(a,'Tag','StaticText_track_HofT'),'BackgroundColor',fl_getOption('BackGroundColor'));
set(findobj(a,'Tag','StaticText_track_HofT'),'ForegroundColor',fl_getOption('AltFontColor'));
	