function gui_fl_DWTestim()
% This is the machine-generated representation of a MATLAB object
% and its children.  Note that handle values may change when these
% objects are re-created. This may cause problems with some callbacks.
% The command syntax may be supported in the future, but is currently 
% incomplete and subject to change.
%
% To re-open this system, just type the name of the m-file at the MATLAB
% prompt. The M-file and its associtated MAT-file must be on your path.
                   
% FracLab 2.05 Beta, Copyright © 1996 - 2009 by INRIA
% -- --
% For details on use and redistribution refer to $fraclab/licence.txt
%--------------------------------------------------------------------------

a = figure('HandleVisibility','callback', ...
	'MenuBar','none','IntegerHandle','off','NumberTitle','off', ...
	'Position',[20 50 300 250], ...
	'Name','dwt-based Estimation','Tag','Fig_gui_fl_DWTestim');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','eval([''global '' fl_DWTestim_compute(''compute_advanced'',who)]);', ...
	'FontSize',0.551723999999999, ...
	'Position',[0.196667 0.596 0.3 0.076], ...
	'String','Estimation time', ...
	'Style','text', ...
   'Tag','StaticText2');
[SigIn_name error_in] = fl_get_input ('vector') ;
eval(['global ' SigIn_name]) ;
SigIn = eval(SigIn_name) ;
N = length(SigIn) ;

b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','fl_DWTestim_compute(''edit_time'')', ...
	'FontSize',0.533333333333332, ...
	'Position',[0.53 0.596 0.166667 0.08], ...
	'String',num2str(floor(1+N*rand(1))), ...
	'Style','edit', ...
	'Tag','EditText_DWTestim_time');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_DWTestim_compute(''advanced_compute'') ;', ...
	'FontSize',0.399999999999999, ...
	'Position',[0.246667 0.416 0.466667 0.12], ...
	'String','Advanced compute', ...
	'Tag','Pushbutton_DWTestim_advanced');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_DWTestim_compute(''compute'') ;', ...
	'FontSize',0.399999999999999, ...
	'FontWeight','bold', ...
	'Position',[0.0633333 0.236 0.233333 0.12], ...
	'String','Compute', ...
	'Tag','Pushbutton_DWTestim_compute');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_DWTestim_compute(''help'')', ...
	'FontSize',0.399999999999999, ...
	'FontWeight','bold', ...
	'Position',[0.363333 0.236 0.233333 0.12], ...
	'String','Help', ...
	'Tag','Pushbutton2');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_DWTestim_compute(''close'')', ...
	'FontSize',0.399999999999999, ...
	'FontWeight','bold', ...
	'Position',[0.663333 0.236 0.233333 0.12], ...
	'String','close', ...
	'Tag','Pushbutton1');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.551723999999999, ...
	'FontWeight','bold', ...
	'Position',[0.0533333 0.076 0.566667 0.076], ...
	'String','Pointwise Exponent', ...
	'Style','text', ...
	'Tag','StaticText_DWTestim_HofT');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',0.533333333333332, ...
	'Position',[0.63 0.076 0.306667 0.08], ...
	'Style','edit', ...
	'Tag','EditText_DWTestim_HofT');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.280701333333333, ...
	'FontWeight','bold', ...
	'Position',[0.0666667 0.769532 0.877333 0.1875], ...
	'Style','frame', ...
	'Tag','Frame1');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.551723999999999, ...
	'FontWeight','bold', ...
	'Position',[0.075333 0.82422 0.8 0.0781248], ...
	'String','Pointwise Holder Exponent Estimation', ...
	'Style','text', ...
	'Tag','StaticText1');

fl_window_init(a);
set(findobj(a,'Tag','StaticText_DWTestim_HofT'),'BackgroundColor',fl_getOption('BackGroundColor'));
set(findobj(a,'Tag','StaticText2'),'BackgroundColor',fl_getOption('BackGroundColor'));

set(findobj(a,'Tag','StaticText_DWTestim_HofT'),'ForegroundColor',fl_getOption('AltFontColor'));
set(findobj(a,'Tag','StaticText2'),'ForegroundColor',fl_getOption('AltFontColor'));
