function fig = gui_fl_estimirs()
% This is the machine-generated representation of a MATLAB object
% and its children.  Note that handle values may change when these
% objects are re-created. This may cause problems with some callbacks.
% The command syntax may be supported in the future, but is currently
% incomplete and subject to change.
%
% To re-open this system, just type the name of the m-file at the MATLAB
% prompt. The M-file and its associtated MAT-file must be on your path.

% Author Christian Choque Cortez, April 2009
% Modified by Pierrick Legrand, November 2016

% FracLab 2.05 Beta, Copyright © 1996 - 2009 by INRIA
% -- --
% For details on use and redistribution refer to $fraclab/licence.txt
%--------------------------------------------------------------------------

a = figure('Name','irs Estimation','Tag','Fig_gui_fl_estimirs',...
    'MenuBar','none','IntegerHandle','off','NumberTitle','off', ...
    'Position',[20 50 320 200]);

%%%%%%%%%%%%%%%%%%% CREATE FRAME %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
uicontrol('Parent',a,'Style','frame','Tag','Frame_title', ...
    'Units','normalized','Position',[0.03 0.75 0.95 0.2]);

uicontrol('Parent',a,'Style','frame','Tag','Frame_input', ...
    'Units','normalized','Position',[0.03 0.34 0.95 0.38]);

%%%%%%%%%%%%%%%%%%% TITLE FRAME %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
uicontrol('Parent',a,'Style','text','Tag','Static_title1', ...
    'Units','normalized','Position',[0.2 0.83 0.6 0.1], ...
    'FontUnits','normalized','FontWeight','bold','FontSize',0.6, ...
    'String','Estimation of Hurst parameter');

uicontrol('Parent',a,'Style','text','Tag','Static_title2', ...
    'Units','normalized','Position',[0.15 0.76 0.7 0.1], ...
    'FontUnits','normalized','FontWeight','bold','FontSize',0.6, ...
    'String','Increment Ratio Statistic method');

%%%%%%%%%%%%%%%%%%% INPUT SIGNAL %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
uicontrol('Parent',a,'Style','text','Tag','StaticText_input', ...
    'Units','normalized','Position',[0.05 0.52 0.22 0.1], ...
    'FontUnits','normalized','FontWeight','bold','FontSize',0.6, ...
    'String','Input Signal');

uicontrol('Parent',a,'Style','edit','Tag','EditText_input', ...
    'Units','normalized','Position',[0.3 0.54 0.4 0.1], ...
    'FontUnits','normalized','FontSize',0.6, ...
    'String','');

uicontrol('Parent',a,'Tag','Button_refresh', ...
    'Units','normalized','Position',[0.73 0.52 0.23 0.15], ...
    'FontUnits','normalized','FontWeight','bold','FontSize',0.4, ...
    'String','Refresh', ...
    'Callback','fl_estimirs_compute(''refresh'')');

%%%%%%%%%%%%%%%%%%% INPUT PARAMETERS %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
uicontrol('Parent',a,'Style','text','Tag','StaticText_tolerence', ...
    'Units','normalized','Position',[0.5 0.36 0.2 0.1], ...
    'FontUnits','normalized','FontSize',0.6, ...
    'String','Tolerence');

uicontrol('Parent',a,'Style','edit','Tag','EditText_tolerence', ...
    'Units','normalized','Position',[0.73 0.38 0.22 0.1], ...
    'FontUnits','normalized','FontSize',0.6, ...
    'String','1e-005', ...
    'Callback','fl_estimirs_compute(''edit_tolerence'')');

%%%%%%%%%%%%%%%%%%% OUTPUT RESULT %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
uicontrol('Parent',a,'Style','text','Tag','StaticText_output', ...
    'Units','normalized','Position',[0.01 0.01 0.53 0.1], ...
    'FontUnits','normalized','FontWeight','bold','FontSize',0.6, ...
    'String','Global Scaling Exponent');

uicontrol('Parent',a,'Style','edit','Tag','EditText_output', ...
    'Units','normalized','Position',[0.68 0.03 0.3 0.1], ...
    'FontUnits','normalized','FontSize',0.6, ...
    'Enable','inactive');

%%%%%%%%%%%%%%%%%%%% COMPUTE/HELP/CLOSE %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
uicontrol('Parent',a,'Tag','Button_compute', ...
    'Units','normalized','Position',[0.03 0.16 0.23 0.15], ...
    'FontUnits','normalized','FontWeight','bold','FontSize',0.4, ...
    'String','Compute', ...
    'Callback','eval([''global '' fl_estimirs_compute(''compute'',who)])');

uicontrol('Parent',a,'Tag','Button_help', ...
    'Units','normalized','Position',[0.39 0.16 0.23 0.15], ...
    'FontUnits','normalized','FontWeight','bold','FontSize',0.4, ...
    'String','Help', ...
    'Callback','fl_estimirs_compute(''help'')');

uicontrol('Parent',a,'Tag','Button_close', ...
    'Units','normalized','Position',[0.75 0.16 0.23 0.15], ...
    'FontUnits','normalized','FontWeight','bold','FontSize',0.4, ...
    'String','Close', ...
    'Callback','fl_estimirs_compute(''close'')');

fl_window_init(a);

set(findobj(a,'Tag','StaticText_output'),...
    'BackgroundColor',fl_getOption('BackGroundColor'));

if nargout > 0, fig = a; end

fl_estimirs_compute('refresh');

