function gui_fl_adv_DWTestim()
% This is the machine-generated representation of a MATLAB object
% and its children.  Note that handle values may change when these
% objects are re-created. This may cause problems with some callbacks.
% The command syntax may be supported in the future, but is currently 
% incomplete and subject to change.
%
% To re-open this system, just type the name of the m-file at the MATLAB
% prompt. The M-file and its associtated MAT-file must be on your path.

% Modified by Pierrick Legrand, November 2016
                 
% FracLab 2.05 Beta, Copyright © 1996 - 2009 by INRIA
% -- --
% For details on use and redistribution refer to $fraclab/licence.txt
%--------------------------------------------------------------------------

[SigIn_name error_in] = fl_get_input ('vector') ;
eval(['global ' SigIn_name]) ;
SigIn = eval(SigIn_name) ;
N = length(SigIn) ;

a = figure( ...
	'Colormap',[], ...
	'HandleVisibility','callback', ...
	'MenuBar','none','IntegerHandle','off','NumberTitle','off', ...
	'Position',[20 50 400 500], ...
	'Name','dwt advanced Estimation','Tag','Fig_gui_fl_adv_DWTestim');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.3, ...
	'Position',[0.025 0.8 0.95 0.08], ...
	'Style','frame', ...
	'Tag','Frame_input');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.48, ...
	'FontWeight','bold', ...
	'HorizontalAlignment','left', ...
	'Position',[0.06 0.805 0.25 0.05], ...
	'String','Input Signal', ...
	'Style','text', ...
	'Tag','StaticText_input');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',0.48, ...
	'HorizontalAlignment','left', ...
	'Position',[0.32 0.815 0.4 0.05], ...
	'Style','edit', ...
	'Enable','inactive',...
	'Tag','EditText_sig_nname');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_adv_DWTestim_compute(''refresh'');', ...
	'FontSize',0.4, ...
	'FontWeight','bold', ...
	'Position',[0.75 0.81 0.175 0.06], ...
	'String','Refresh', ...
	'Tag','refresh_input');
%b = uicontrol('Parent',a, ...
%	'Units','normalized', ...
%	'FontUnits','normalized', ...
%	'FontSize',0.3, ...
%	'Position',[0.025 0.37 0.95 0.08], ...
%	'Style','frame', ...
%	'Tag','Frame_inputdwt');
%b = uicontrol('Parent',a, ...
%	'Units','normalized', ...
%	'FontUnits','normalized', ...
%	'FontSize',0.48, ...
%	'FontWeight','bold', ...
%	'HorizontalAlignment','left', ...
%	'Position',[0.0525 0.38 0.25 0.05], ...
%	'String','Input dwt', ...
%	'Style','text', ...
%	'Tag','StaticText_inputdwt');
%b = uicontrol('Parent',a, ...
%	'Units','normalized', ...
%	'FontUnits','normalized', ...
%	'BackgroundColor',[1 1 1], ...
%	'FontSize',0.48, ...
%	'HorizontalAlignment','left', ...
%	'Position',[0.3225 0.386 0.4 0.05], ...
%	'Style','text', ...
%	'Tag','EditText_dwt_nname');
%b = uicontrol('Parent',a, ...
%	'Units','normalized', ...
%	'FontUnits','normalized', ...
%	'Callback','fl_adv_DWTestim_compute(''refresh_dwt'');', ...
%	'FontSize',0.4, ...
%	'FontWeight','bold', ...
%	'Position',[0.75 0.38 0.175 0.06], ...
%	'String','Refresh', ...
%	'Tag','refresh_dwt');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.24, ...
	'Position',[0.025 0.67 0.95 0.1], ...
	'Style','frame', ...
	'Tag','Frame_param');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.06, ...
	'Position',[0.025 0.2 0.95 0.4], ...
	'Style','frame', ...
	'Tag','Frame_param');
%b = uicontrol('Parent',a, ...
%	'Units','normalized', ...
%	'FontUnits','normalized', ...
%	'BackgroundColor',[1 1 1], ...
%	'FontSize',0.533333333333332, ...
%	'HandleVisibility','callback', ...
%	'Position',[0.0425 0.696 0.1825 0.04], ...
%	'String','0.015625', ...
%	'Style','edit', ...
%	'Tag','EditText_dwt_fmin');
%b = uicontrol('Parent',a, ...
%	'Units','normalized', ...
%	'FontUnits','normalized', ...
%	'BackgroundColor',[1 1 1], ...
%	'Callback','fl_adv_DWTestim_compute(''dwt_editf'');', ...
%	'FontSize',0.533333333333332, ...
%	'Position',[0.575 0.696 0.185 0.04], ...
%	'String','0.5', ...
%	'Style','edit', ...
%   'Tag','EditText_dwt_fmax');
matreg{1}='Least Square';
matreg{2}='Weighted Least Square';
matreg{3}='Penalized Least Square';
matreg{4}='Lepskii Adaptive Procedure';
matreg{5}='Maximum Likelihood';
matreg{6}='lim inf';
matreg{7}='lim sup';

b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.551723999999999, ...
	'FontWeight','demi', ...
	'Position',[0.13 0.7 0.2 0.038], ...
	'String','Wavelet Type', ...
	'Style','text', ...
	'Tag','StaticText_dwt_wavelet');
%b = uicontrol('Parent',a, ...
%	'Units','normalized', ...
%	'FontUnits','normalized', ...
%	'FontSize',0.551723999999999, ...
%	'Position',[0.0575 0.578 0.125 0.038], ...
%	'String','Size', ...
%	'Style','text', ...
%	'Tag','StaticTextf_dwt_wsize');
%b = uicontrol('Parent',a, ...
%	'Units','normalized', ...
%	'FontUnits','normalized', ...
%	'BackgroundColor',[1 1 1], ...
%	'FontSize',0.533333333333332, ...
%%	'HandleVisibility','callback', ...
%	'Position',[0.34 0.578 0.1825 0.04], ...
%	'String','10', ...
%	'Style','edit', ...
%	'Tag','EditText_dwt_wsize');
%b = uicontrol('Parent',a, ...
%	'Units','normalized', ...
%	'FontUnits','normalized', ...
%	'FontSize',0.551723999999999, ...
%	'Position',[0.0575 0.516 0.125 0.038], ...
%	'String','Type', ...
%	'Style','text', ...
%  'Tag','StaticTextf_dwt_wtype');
matond{1}='daubechies  2';
matond{2}='daubechies  4';
matond{3}='daubechies  6';
matond{4}='daubechies  8';
matond{5}='daubechies 10';
matond{6}='daubechies 12';
matond{7}='daubechies 14';
matond{8}='daubechies 16';
matond{9}='daubechies 18';
matond{10}='daubechies 20';
matond{11}='coiflet  6';
matond{12}='coiflet 12';
matond{13}='coiflet 18';
matond{14}='coiflet 24';
matond{15}='Spline 1';

b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_adv_DWTestim_compute(''dwt_ppm_wtype'');', ...
	'FontSize',0.516129333333332, ...
	'Max',3, ...
	'Min',1, ...
	'Position',[0.38 0.7 0.3425 0.042], ...
	'String',matond, ...
	'Style','popupmenu', ...
	'Tag','PopupMenu_dwt_wtype', ...
	'Value',5);
%b = uicontrol('Parent',a, ...
%	'Units','normalized', ...
%	'FontUnits','normalized', ...
%	'Callback','fl_adv_DWTestim_compute(''dwt_rb_mirror'');', ...
%	'FontSize',0.533333333333332, ...
%	'Position',[0.6075 0.552 0.35 0.04], ...
%	'String','Mirror', ...
%	'Style','Checkbox', ...
%	'Tag','Radiobutton_dwt_mirror', ...
%	'Value',1);
%b = uicontrol('Parent',a, ...
%	'Units','normalized', ...
%	'FontUnits','normalized', ...
%	'FontSize',0.551723999999999, ...
%	'Position',[0.5775 0.646 0.1825 0.038], ...
%	'String','Voices', ...
%	'Style','text', ...
%	'Tag','StaticText_dwt_voices');
%b = uicontrol('Parent',a, ...
%	'Units','normalized', ...
%	'FontUnits','normalized', ...
%	'BackgroundColor',[1 1 1], ...
%	'Callback','fl_adv_DWTestim_compute(''dwt_edit_voices'');', ...
%	'FontSize',0.533333333333332, ...
%	'Position',[0.575 0.6 0.185 0.04], ...
%	'String','128', ...
%	'Style','edit', ...
%	'Tag','EditText_dwt_voices');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_adv_DWTestim_compute(''close'')', ...
	'FontSize',0.399999999999999, ...
	'FontWeight','bold', ...
	'Position',[0.6725 0.092 0.175 0.06], ...
	'String','Close', ...
	'Tag','Pushbutton_dwt_wclose');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','eval([''global '' fl_adv_DWTestim_compute(''compute_HofT'',who)]) ;', ...
	'FontSize',0.399999999999999, ...
	'FontWeight','bold', ...
	'Position',[0.1175 0.092 0.175 0.06], ...
	'String','Compute', ...
	'Tag','Pushbutton_HofT_compute');
%b = uicontrol('Parent',a, ...
%	'Units','normalized', ...
%	'FontUnits','normalized', ...
%	'Callback','fl_adv_DWTestim_compute(''dwt_ppm_voices'');', ...
%	'FontSize',0.516129333333332, ...
%	'Max',8, ...
%	'Min',1, ...
%	'Position',[0.7775 0.602 0.18 0.042], ...
%	'String',mat4, ...
%	'Style','popupmenu', ...
%	'Tag','PopupMenu_dwt_voices', ...
%	'Value',7);
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','fl_adv_DWTestim_compute(''edit_time'')', ...
	'FontSize',0.533333333333332, ...
	'Position',[0.3225 0.496 0.11 0.04], ...
	'String','1', ...
   'Style','edit', ...
   'Enable','off',...
	'Tag','EditText_adv_DWTestim_time');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','fl_adv_DWTestim_compute(''edit_radius'')', ...
	'FontSize',0.533333333333332, ...
	'Position',[0.3225 0.436 0.11 0.04], ...
	'String','1', ...
	'Style','edit', ...
   'Tag','EditText_adv_DWTestim_radius', ...
   'enable','off');

b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','fl_adv_DWTestim_compute(''edit_deepscale'')', ...
	'FontSize',0.533333333333332, ...
	'Position',[0.3225 0.386 0.11 0.04], ...
	'String','1', ...
	'Style','edit', ...
   'Tag','EditText_adv_DWTestim_deepscale', ...
   'Enable','Off');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_adv_DWTestim_compute(''radiobutton_findmax'')', ...
	'FontSize',0.533333333333332, ...
	'Position',[0.8275 0.378 0.1375 0.04], ...
	'String','No', ...
	'Style','Checkbox', ...
	'Tag','Radiobutton_adv_DWTestim_findmax', ...
   'Value',0);
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_adv_DWTestim_compute(''checkbox_tol'')', ...
	'FontSize',0.533333333333332, ...
	'Position',[0.09 0.3 0.3 0.04], ...
	'String','Without Tolerance', ...
	'Style','Checkbox', ...
	'Tag','checkbox_adv_DWTestim_tol', ...
   'Value',0);

b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.533333333333332, ...
	'Position',[0.4+0.12 0.29 0.15 0.04], ...
	'String','Scale Min', ...
	'Style','text', ...
	'Tag','text_adv_DWTestim_scaleMin', ...
   'Value',0);


b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_adv_DWTestim_compute(''scaleMin'')', ...
	'FontSize',0.533333333333332, ...
	'Position',[0.55+0.12 0.3 0.05 0.04], ...
	'String','1', ...
	'Style','edit', ...
	'Tag','edit_adv_DWTestim_scaleMin', ...
   'Value',0);


b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.533333333333332, ...
	'Position',[0.6+0.15 0.29 0.15 0.04], ...
	'String','Scale Max', ...
	'Style','text', ...
	'Tag','text_adv_DWTestim_scaleMax', ...
   'Value',0);


b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_adv_DWTestim_compute(''scaleMax'')', ...
	'FontSize',0.533333333333332, ...
	'Position',[0.75+0.15 0.3 0.05 0.04], ...
	'String','1', ...
	'Style','edit', ...
	'Tag','edit_adv_DWTestim_scaleMax', ...
   'Value',0);


b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_adv_DWTestim_compute(''slider_tol'');', ...
   'FontSize',0.533333333333332, ...
   'Min',0,...
	'Max',0.9, ...
	'Position',[0.09 0.23 0.32 0.04], ...
   'Style','slider', ...
   'Enable','Off',...
	'Tag','Slider_adv_DWTestim_tol', ...
   'Value',0.5);
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.533333333333332, ...
	'Position',[0.41 0.23 0.15 0.038], ...
	'String','Gamma', ...
   'Style','text', ...
   'Enable','Off',...
	'Tag','StaticText_tol');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
   'FontUnits','normalized', ...
   'Callback','fl_adv_DWTestim_compute(''edit_tol'');', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',0.516129333333332, ...
   'Position',[0.60 0.23 0.1 0.04], ...
   'String','0.5',...
   'Style','edit', ...
   'Enable','Off',...
	'Tag','EditText_adv_DWTestim_tol');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.551723999999999, ...
	'Position',[0.0475 0.496 0.25 0.038], ...
	'String','Time Instant', ...
	'Style','text', ...
	'Tag','StaticText1');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.551723999999999, ...
	'Position',[0.0475 0.436 0.25 0.038], ...
	'String','Radius', ...
	'Style','text', ...
	'Tag','StaticText2');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.551723999999999, ...
	'Position',[0.0475 0.386 0.25 0.038], ...
	'String','Scale-Depth', ...
	'Style','text', ...
	'Tag','StaticText3');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.551723999999999, ...
	'Position',[0.525 0.378 0.2125 0.038], ...
	'String','Local Maxima', ...
	'Style','text', ...
	'Tag','StaticText4', ...
	'Value',1);
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.551723999999999, ...
	'FontWeight','bold', ...
	'Position',[0.1 0.028 0.4 0.038], ...
	'String','Local Scaling Exponent', ...
	'Style','text', ...
	'Tag','StaticText7');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',0.516129333333332, ...
	'Position',[0.575 0.028 0.28 0.042], ...
	'Style','edit', ...
	'Tag','EditText_adv_DWTestim_HofT');
%b = uicontrol('Parent',a, ...
%	'Units','normalized', ...
%	'FontUnits','normalized', ...
%	'Callback','eval([''global ''fl_adv_DWTestim_compute(''dwt_compute'',who)]);', ...
%	'FontSize',0.399999999999999, ...
%	'FontWeight','bold', ...
%	'Position',[0.605 0.48 0.35 0.064], ...
%	'String','Compute WT', ...
%	'Tag','Pushbutton_dwt_compute');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_adv_DWTestim_compute(''radiobutton_time'')', ...
	'FontSize',0.533333333333332, ...
	'Position',[0.525 0.51 0.44 0.04], ...
	'String','Holder Function', ...
	'Style','Checkbox', ...
	'Tag','Radiobutton_adv_DWTestim_time', ...
	'Value',0);
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_adv_DWTestim_compute(''radiobutton_reg'')', ...
	'FontSize',0.533333333333332, ...
	'Position',[0.525 0.465 0.44 0.04], ...
	'String','Full Regression Range', ...
	'Style','Checkbox', ...
   'Tag','Radiobutton_adv_DWTestim_reg', ...
   'Enable','off',...
	'Value',0);
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
   'FontUnits','normalized', ...
   'Callback','fl_adv_DWTestim_compute(''reg_type'')', ...
	'FontSize',0.533333333333332, ...
	'ListboxTop',0, ...
	'Min',1, ...
	'Position',[0.524 0.422 0.441 0.04], ...
	'String',matreg, ...
	'Style','popupmenu', ...
	'Tag','Radiobutton_adv_DWTestim_monolr', ...
	'Value',1);    
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.296295999999999, ...
	'Position',[0.025 0.898052 0.95 0.0884558], ...
	'Style','frame', ...
	'Tag','Frame1');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.551723999999999, ...
	'FontWeight','bold', ...
	'Position',[0.143119 0.92 0.72844 0.038], ...
	'String','Pointwise Holder exponent/function estimation', ...
	'Style','text', ...
	'Tag','StaticText6');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'Callback','fl_adv_DWTestim_compute(''help'')', ...
	'FontSize',0.399999999999999, ...
	'FontWeight','bold', ...
	'Position',[0.4 0.092 0.175 0.06], ...
	'String','Help', ...
	'Tag','Pushbutton1');


fl_window_init(a);
fl_adv_DWTestim_compute('refresh');

set(findobj(a,'Tag','StaticText7'),'BackgroundColor',fl_getOption('BackGroundColor'));
set(findobj(a,'Tag','StaticText7'),'ForegroundColor',fl_getOption('AltFontColor'));
