#!/bin/bash

# MUST BE RUN AS:
# . waitfor_quiet 4
# NOT
# waitfor_quiet 4

#echo -n "Waiting $1 "

it=0
while [[ `jobs | grep Running | wc -l` -gt $1 ]]; 
do
	echo -n '.'
	sleep 0.5 
done

#echo 'OK'

